### ISSUE TITLE
📌📚📕 Migration instructions from oh-my-fish to fisherman?

### ISSUE THREAD

**Issue by FabioAntunes** [jorgebucaran/fisher#223]
It's somehow related to https://github.com/fisherman/fisherman/issues/110 but I think that would be nice to have a migration guide, explaining how to migrate all the plugins and stuff from omf to fisherman.

**Comment by bucaran** [comment]
Yes, this is exactly what we were just discussing on Slack. 

Ping @laughedelic

**Comment by bucaran** [comment]
### Sticky 🍍 

If you are running anything before 2.0

```
curl -L git.io/fisher-up-me | fish
```

use `curl -L git.io/fisher-up-me | fish_indent --ansi` to inspect the script first if you like.

> This will _not_ delete your configuration, but it will move the directory to a different name. You can choose to start over or copy the plugin directories back into the new ~/.config/fisherman.

**Comment by pickfire** [comment]
@bucaran, I thought it is in the wiki page. :scream: When did the ultimate wiki page just disappeared like that?

**Comment by bucaran** [comment]
@pickfire I feel we don't need a wiki anymore. With fisherman 2.0 there is little or nothing the user needs to know, let's keep it that way and not complicate our lives with more tutorials :)

**Comment by pickfire** [comment]
Okay

**Comment by FabioAntunes** [comment]
@bucaran Thanks, I'm going to give fisherman a try I will post the results.

**Comment by bucaran** [comment]
@FabioAntunes Wonderful! I'll keep this open for a while :)

**Comment by FabioAntunes** [comment]
So for those who are running the latest omf version, here are the steps:

### :pushpin: Instructions 


##### 1. Just install fisherman

```sh
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
```

##### 2. If you happen to be also running any fisherman _before_ 2.0 alongside omf

```fish
curl -L git.io/fisher-up-me | fish
```

use `curl -L git.io/fisher-up-me | fish_indent --ansi` to inspect the script first if you like.

> This will _not_ delete your configuration, but it will move the directory into a different name. You can then choose to start over _or_ copy the plugin directories back into the new ~/.config/fisherman.

##### 3. Add omf plugin names to `~/.config/fish/fishfile` and run `fisher`
Add the plugins manually `oh-my-fish/plugin--<name-of-the-plugin>` and for themes add `oh-my-fish/theme--<name-of-the-theme>`, to install the git flow plugin and theme agnoster we will add these two lines:
```
oh-my-fish/plugin-git-flow
oh-my-fish/theme-agnoster
```

then run `fisher`

> If you are using the new omf version this script will add your omf plugins to the fisherman file and then installs them, if you are using the old omf version this script will only this only installs plugins, for themes you must add `oh-my-fish/theme-<name-of-the-theme>` to the fishfile


```bash
if test -f ~/.config/omf/bundle
  set bundle (cat ~/.config/omf/bundle)
  cd ~/.config/fish
  for plugin in $bundle
    set pluginName (echo $plugin |  sed "s/ /\n/g")

    if [ $pluginName[1] = "theme" ]
      set baseName "oh-my-fish/theme-"
    else if [ $pluginName[2] = "nvm" ]
      set baseName "fisherman/"
    else if [ $pluginName[2] = "bass" ]
      set "edc/"
    else
      set baseName "oh-my-fish/plugin-"
    end

    echo $baseName$pluginName[2] >> fishfile
  end
else
  cd ~/.config/fish
  for plugin in $OMF_CONFIG/*
    echo "$plugin" >> fishfile
  end
end
fisher
```

##### 4. Remove omf directories and files
If you are using the new omf just run

```fish
omf destroy
```

Else you will have to remove it manually
```fish
rm -rf "$OMF_PATH" "$OMF_CONFIG"
$EDITOR ~/.config/fish/config.fish

### ERASE LINE   set -gx OMF_PATH "{{OMF_PATH}}"
### ERASE LINE   set -gx OMF_CONFIG "{{OMF_CONFIG}}"
### ERASE LINE   source $OMF_PATH/init.fish
```

**Comment by bucaran** [comment]
Thank your for writing this @FabioAntunes.
