### ISSUE TITLE
Unload functions on uninstall

### ISSUE THREAD

**Issue by franciscolourenco** [jorgebucaran/fisher#368]
After uninstalling fisherman/done I get these errors:

```
$ fisher uninstall done
Done in 85ms
fish: Unknown command 'humanize_duration'
~/.config/fish/conf.d/done.fish (line 1): echo "$CMD_DURATION" | humanize_duration
                                                                 ^
in command substitution
	called on line 40 of file ~/.config/fish/conf.d/done.fish

in function '__done_ended'
	called on standard input

in event handler: handler for generic event 'fish_prompt'


user at unknown in ~
$ fisher list
cache
fish: Unknown command 'humanize_duration'
~/.config/fish/conf.d/done.fish (line 1): echo "$CMD_DURATION" | humanize_duration
                                                                 ^
in command substitution
	called on line 40 of file ~/.config/fish/conf.d/done.fish

in function '__done_ended'
	called on standard input

in event handler: handler for generic event 'fish_prompt'
```

I guess this happens because the functions are still loaded and executed on `fish_prompt` hook, but humanize_duration is no longer available?

**Comment by jbucaran** [comment]
@aristidesfl 

fisherman already erases/unloads functions when you uninstall a plugin:
* https://github.com/fisherman/fisherman/blob/master/fisher.fish#L841

In the case of `done` that would be impractical, because (didn't we had this conversation before?) the functions are eagerly loaded inside conf.d/done.fish and fisherman can't guess the names of the functions by looking at the plugin's name `done` or other files (there aren't any) inside the plugins's directory.

**Comment by aristidesfl** [comment]
Right, makes sense. So this problem was introduced in 2.3.0 and would not occur if functions were not unloaded at all..

**Comment by jbucaran** [comment]
For the record, I contemplated doing stuff like looking at the environment for functions named like so
```
^_+($plugin_name)_+[A-Za-z0-9]+$
```

and erase them. Hacky.

**Comment by aristidesfl** [comment]
Even if imperfect, sounds like an incremental improvement over not unloading anything. What is the probability of unloading a function which doesn't belong to the plugin? 

`^_+`

**Comment by jbucaran** [comment]
Low. The reason I didn't implement this was "lock in", but now in hindsight, why not?

This is _possibly_ just a matter of unloading related names during plugin disable.

**Comment by pjeby** [comment]
As of fish 2.6, it's possible to at least verify (via `functions -D funcname`) whether it came from that file, so you could literally do:

```fish
function remove_funcs_for_file --argument removed_file
    for f in (functions --all)
        if test (functions -D $f) = $removed_file
            functions -e $f
        end
    end
end
```
to remove any function that came from the file.

**Comment by jbucaran** [comment]
@pjeby Very nice trick!

Would love to add a note to the cookbook about this.

- https://github.com/jbucaran/fish-shell-cookbook#how-to-create-a-private-function-in-fish

**Comment by jorgebucaran** [comment]
@franciscolourenco I just released [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉  

V3 introduces a mechanism for packages to provide custom uninstall logic via an event handler. You can place this event handler in your <samp>done.fish</samp> file inside the <samp>conf.d</samp> directory as follows.

```fish
function done_uninstall -e done_uninstall
  # Erase all __done_* functions
  functions -e __done_ended
  functions -e __done_started
  functions -e __done_get_focused_window_id
  functions -e __done_is_tmux_window_active
  functions -e __done_is_process_window_focused

  # Erase __done variables
  set -e __done_version
end
```



See [configuration snippets](https://github.com/jorgebucaran/fisher#configuration-snippets) in the new documentation for full details.

**Comment by franciscolourenco** [comment]
Is this name scheme still relevant in V3?

If so should it be `function _done_uninstall -e done_uninstall`?

**Comment by jorgebucaran** [comment]
@franciscolourenco As it turns out, fish only cares about the symbol after the `-e` or `--on-event` flag. So, it's up to you what you name that function. I still recommend using your package name as a prefix.

My personal preference is to use `done_uninstall` for the event handler defined in the configuration snippet and `_done_xxx_xxx` for everything else.

```fish
function done_uninstall -e done_uninstall
    # ...
end
```
