### ISSUE TITLE
Persist the results of dependency resolution

### ISSUE THREAD

**Issue by Fuco1** [jorgebucaran/fisher#381]
Hi.

It is a very good practice to keep builds reproducible: if I version my config and install it on another system, I want to get the same result.

Right now, because fisherman just pulls the master if I don't specify the versions I can get a broken setup or config in an unknown state.

You can read more here: https://blog.ometer.com/2017/01/10/dear-package-managers-dependency-resolution-results-should-be-in-version-control/

**Comment by jbucaran** [comment]
> Right now, because fisherman just pulls the master if I don't specify the versions I can get a broken setup or config in an unknown state.

Yes. This would be nice to have.

**Comment by jbucaran** [comment]
@Fuco1 I'd be happy to merge a PR, but I don't really have a critical need for this feature at the moment.

**Comment by Fuco1** [comment]
Well, I'm not really great with fish programming.  I tried couple weeks ago briefly to go over the code to see how things work and haven't got very far :/

Maybe I'll give it another shot one day, but we also need to understand that doing this would likely need to result in some breaking UI changes:
y
- running `fisher` would look into the lock file and pull stuff from that, so adding things to `fishfile` and then running `fisher` should do nothing
- running `fisher up` should consult the `fishfile` and update all dependencies accordingly, then dump a new lock file
- running `fisher <package>` should probably add it to the fishfile, pull and install it and then update the lock file

**Comment by jbucaran** [comment]
@Fuco1 Thanks for the useful report. 

Fisherman would be much faster if it was written in a real language like go, rust, node.js, etc. 
Then we could use .json or .yml for the fishfile instead of the current naive approach.

Perhaps I should consider this again. 🤔

**Comment by Fuco1** [comment]
I kind of like the approach of writing the package manager for X in X because that ensures you definitely have X installed if you want to use it :D If we rewrote this in say ruby then people who don't use ruby much (like myself) would moan about having to install ruby just to manage X (fish in this case).

On the other hand, I don't know how high the entry barrier for contributing is in fish, certainly high enough for me (while I have written couple smaller helpers fishers is many orders of magnitude bigger).

If a rewrite would be in order then I would probably go with python as that is probably available by default on 99% of boxes out there, is an easy language to work with even for non-experts and is sort of universal in its general philosophy.

**Comment by jbucaran** [comment]
> I kind of like the approach of writing the package manager for X in X because that ensures you definitely have X installed if you want to use it. 

Exactly. Also, it's "fair" to the language, or so I felt when I first wrote this.

> If a rewrite would be in order then I would probably go with python as that is probably available by default on 99% of boxes out there, is an easy language to work with even for non-experts and is sort of universal in its general philosophy.

Noted. Another take is to use a compiled language and distribute a binary.

**Comment by jbucaran** [comment]
@Fuco1 Oh, how I love to write fish plugin managers. There's also https://github.com/fisherman/fin, which I like more than fisherman, but unfortunately didn't become as popular.

**Comment by jorgebucaran** [comment]
@Fuco1 I just released [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉  

You can specify a tag or branch when installing your package such as a `foo/bar@v3` and it will be written to your fishfile, allowing you to create a reproducible installation in another system.
