### ISSUE TITLE
Installing and removing a theme doesn't restore custom prompt

### ISSUE THREAD

**Issue by Tyilo** [jorgebucaran/fisher#404]
I had a custom prompt function for fish.
I then installed the `omf/theme-default` package with fisherman and uninstalled it again.
After that I got the default fish prompt, instead of my custom prompt.

After running the following commands, your shell configuration really shouldn't be altered:
```
fisher install foo
fisher rm foo
```

**Comment by jorgebucaran** [comment]
@Tyilo You are completely right. Fisher uses your ~/.config/fish configuration directory by default, as that is what will work best for most users, but you can customize the installation prefix if you want too. 

See [changing the installation prefix](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix) in the new documentation.
