### ISSUE TITLE
Package resolution 

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fisher#410]
Hi,
How does package resolution work during install?

@heyarne [reported installing the wrong package](https://github.com/rafaelrinaldi/pure/issues/55#issuecomment-370450863), same name different organization hence his issue:

> Oh wow... this is a bit embarassing. `fisher install pure` doesn't install [`rafalrinaldi/pure`](https://github.com/rafaelrinaldi/pure) but instead pure from [`vkovtash/pure`](https://github.com/vkovtash/pure). Indeed, couldn't reproduce the issue after executing `fisher rm pure; fisher install rafaelrinaldi/pure`. I'm going to close this, thanks for the effort and sorry! I assumed there was just one port.

**Comment by jorgebucaran** [comment]
@edouard-lopez V3 has immutable package resolution, so this problem should not occur again unless you use an incorrect URL. TL;DR V3 will create a new installation (reinstall everything from scratch) everytime changes are committed to the fishfile either by editing the fishfile manually and committing changes by running `fisher` or by using the facade `add` or `rm` commands.
