### ISSUE TITLE
fisher update just spins forever

### ISSUE THREAD

**Issue by Tyilo** [jorgebucaran/fisher#411]
When running `fisher update`, nothing happens. If I press ctrl-C, I can see that there is a job in the background:

```
$ fisher update
^C
$ jobs
Job	Group	CPU	State	Command
7	30970	0%	stopped	fish -c "curl --max-time 5 -sS '$raw_url?$fake_qs' > $file.$fake_qs" &
```

fisher version: `2.13.2`
fish version: `2.7.1`
OS: Arch Linux
Installed fisher plugins:
```
bobthefish	errno		getopts		z
bang-bang	fish_logo	pipenv
```

**Comment by bondmike** [comment]
Nice post,i want to play with you .Please contact me at.:
annalisa13763.@gmail.com . i hope you are real..

**Comment by Markcial** [comment]
Hi, if there issue still persists, do you mind to profile the fish shell with the `fish -p <log-file>` command?

If you get to the part where the `spin` command is stuck and you paste it here would be awesome, thanks.

**Comment by Pyrepenol** [comment]
I've come across this issue today as well, here's the log of it you asked for.

https://gist.github.com/69c8f3b0a0e30c207f79db7b4a14333a

**Comment by Tyilo** [comment]
A weird thing I just noticed is that

```
fish -c 'fisher update'
```

works.

It is still an issue for me when just running `fisher update`.
Here is my log: https://gist.github.com/Tyilo/e8dc442310064a9cf8e8914d1e324a75

**Comment by aureooms** [comment]
I've had this issue [since 2016](https://github.com/aureooms/dotfiles/commit/5103ab8628cf5322148b5747a7f9c1a3a5118e9c)! I usually don't run `fisher update` manually. However, since I was installing on a new device, I had to run `fisher` manually to first install the plugins. The command `fisher` alone loops forever. Running `fish -c 'fisher'` just works.

**Comment by jorgebucaran** [comment]
Is this still happening? It seems the spinner works well for most people, it definitely works well for me, but I never tested https://github.com/fisherman/await on Arch either. 🤔

**Comment by Tyilo** [comment]
This is still happening with fisherman version 2.13.3 and fish version 2.7.1.

**Comment by jorgebucaran** [comment]
The spinner has been removed in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0).

For more information see the [new documentation](https://github.com/jorgebucaran/fisher/blob/34b5257c5beaaf37f7d1988a6a9a62f8a0b1196c/README.md).
