### ISSUE TITLE
fisher ls reports invalid integer ''

### ISSUE THREAD

**Issue by elman22** [jorgebucaran/fisher#421]
Hi,

when I try to execute `fisher up`, I get error `invalid integer ''`

Other commands like `fisher up` or `fisher ls-remote` work fine. 

I'm using fish 2.7.1 and fisherman 2.8.0 on Manjaro Linux.

**Comment by jorgebucaran** [comment]
Fixed in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉
