### ISSUE TITLE
Allow local functions to override package functions

### ISSUE THREAD

**Issue by paride** [jorgebucaran/fisher#423]
If a package installs a function, e.g. `~/.config/fish/functions/fish_greeting.fish`, there is no way to override it. Background: https://github.com/oh-my-fish/theme-bobthefish/issues/158.

(Further background: https://github.com/fisherman/metro/issues/15#issuecomment-393197397.)

**Comment by jorgebucaran** [comment]
@paride How?

**Comment by jorgebucaran** [comment]
@paride I just released [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉

Fisher uses your ~/.config/fish configuration directory by default, as that is what will work best for most users, but you can customize the installation prefix if you want too. 

See [changing the installation prefix](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix) in the new documentation.
