### ISSUE TITLE
Fisherman self-uninstall doesn't remove plugins :'(

### ISSUE THREAD

**Issue by BarbzYHOOL** [jorgebucaran/fisher#428]
That's kind of annoying when doing tests. It's hard to distinguish my own functions from the plugins I need to delete.

**Comment by jorgebucaran** [comment]
@BarbzYHOOL You are right, [`self-uninstall`](https://github.com/fisherman/fisherman/blob/master/fisher.fish#L2185) doesn't uninstall plugins. This command is not documented either, though. 😉 

Don't you think uninstalling plugins would be unexpected behavior? Perhaps I could add a flag to the command.

**Comment by BarbzYHOOL** [comment]
Yes, need a flag or better, a prompt? The text could be something like "Delete your plugins? if not, you will only need to reinstall fisher to reactivate them"

And yes self-uninstall is not documented, I found it on github

**Comment by jorgebucaran** [comment]
A flag sounds good. 👍

**Comment by jorgebucaran** [comment]
I agree it doesn't make sense for `self-uninstall` to not remove installed plugins. V3 now removes all installed plugins before removing `fisher` itself. 

For more information see [Uninstalling](https://github.com/jorgebucaran/fisher#uninstalling) in the new documentation.
