### ISSUE TITLE
annoying background colour of fisher output

### ISSUE THREAD

**Issue by znculee** [jorgebucaran/fisher#435]
When I install a new plugin or run (fisher up), there is an output like the following figure.
![image](https://user-images.githubusercontent.com/15342165/42725936-effe3894-87be-11e8-87b3-c6004f7ddad2.png)
Obviously, there's a background colour in some of the output text. I can temporally check it with selection, as the following figure.
![image](https://user-images.githubusercontent.com/15342165/42725949-299d2984-87bf-11e8-80dc-f8151dfd1861.png)
However, this is really annoying. Could you cancel this background colour? I'll appreciate that.
I also tried to revised the fisher.fish, but I haven't made it done.

**Comment by FabioAntunes** [comment]
Wow, I was just looking into this and trying to find a solution. There was a ticket related to this that was closed. https://github.com/fisherman/fisherman/issues/378

I also found these related issues:
https://github.com/mochajs/mocha/issues/802
https://github.com/altercation/solarized/pull/240
https://github.com/altercation/solarized/issues/220#issuecomment-17191676
https://github.com/altercation/solarized/issues/164

One of the possible solutions is increasing the contrast by one third on your iTerm2 but that is far from great

**Comment by FabioAntunes** [comment]
I have tested a couple of themes all of them 256 colors, there some that are better than others but on the overall I would say there isn't a perfect one:

**solarized-dark**
<img width="292" alt="solarized-256" src="https://user-images.githubusercontent.com/2544673/42726601-1c6b5d6a-878f-11e8-97ba-2baeb80aed56.png">

**materia**
<img width="246" alt="materia-256" src="https://user-images.githubusercontent.com/2544673/42726602-1c832490-878f-11e8-84dd-19f10129745a.png">

**solarflare**
<img width="270" alt="solarflare-256" src="https://user-images.githubusercontent.com/2544673/42726603-1cbcfc7e-878f-11e8-9b87-262604c545d5.png">

**flat**
<img width="257" alt="flat-256" src="https://user-images.githubusercontent.com/2544673/42726604-1cd52420-878f-11e8-9bcc-823aa814b57c.png">

**oceanicnext**
<img width="279" alt="oceanicnext-256" src="https://user-images.githubusercontent.com/2544673/42726605-1cf44abc-878f-11e8-9268-3360f5324385.png">

**nord**
<img width="266" alt="nord-256" src="https://user-images.githubusercontent.com/2544673/42726606-1d0acb34-878f-11e8-90da-48cd972c4b50.png">


All of these themes are from [base16](https://github.com/chriskempson/base16)

**Comment by znculee** [comment]
@FabioAntunes Great survey! I think it would be better if there is just no background colour.

**Comment by jorgebucaran** [comment]
I agree this is quite annoying. What's odd is, I don't recall having added a background color to this output. Incredible.

**Comment by jorgebucaran** [comment]
@znculee @FabioAntunes  The CLI output has been redesigned in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0), removing all colorized and special characters. 

Here is an example of what you get now:

```console
$ fisher
fetching https://codeload.github.com/fisherman/getopts/tar.gz/master
fetching https://codeload.github.com/fisherman/spin/tar.gz/master
linking ~/.config/fish/functions/getopts.fish
linking ~/.config/fish/completions/spin.fish
linking ~/.config/fish/functions/spin.fish
linking ~/.config/fish/conf.d/keybinder.fish
fetching https://codeload.github.com/fisherman/getopts/tar.gz/master
linking ~/.config/fish/functions/getopts.fish
added 1 package, updated 3 packages, removed 7 packages in 1.82s
```
