### ISSUE TITLE
fish autocomplete suggestions breaks after fisher update

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#437]
Repro steps
1. try typing some command and tabbing to make sure autocomplete suggestions work (e.g. git branch \TAB)
2. fisher update (doesn't matter if nothing is updated)
3. try the same tabbing to complete the same command again and notice no suggestions show up

**Comment by jorgebucaran** [comment]
@patrickf3139 Fixed in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉

---

See the [new documentation](https://github.com/jorgebucaran/fisher#fisher) for details.

**Comment by patrickf3139** [comment]
Nice work
