### ISSUE TITLE
ls-remote should also show plugins found in fisherman/index

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#438]
There are many plugins added to the index can be found at https://fisherman.github.io/ but not the `fisher ls-remote` command simply because they were not moved to the fisherman org. I think that's a shame because ls-remote might be used more and so we should also support finding those plugins listed in index.

**Comment by jorgebucaran** [comment]
The `ls-remote` command has been removed in V3. See [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0).
