### ISSUE TITLE
Plugin key bindings aren't merged with my key bindings if fish_path is set

### ISSUE THREAD

**Issue by r-darwish** [jorgebucaran/fisher#442]
[This](https://github.com/r-darwish/fish/tree/fzf) is my current configuration. I've tried to add `fisherman/fzf`. It placed a file in `/home/roeyd/.config/fish-plugins/functions/fish_user_key_bindings.fish` which contains only the fzf key binding, and not the bindings defined in `/home/roeyd/.config/fish/functions/fish_user_key_bindings.fish`.

As I understand from #289, fisherman is supposed to merge these files. However, I suspect that it didn't happen since I set `fish_path`

**Comment by jorgebucaran** [comment]
@r-darwish Key bindings support have been re-implemented in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉

Please see https://github.com/jorgebucaran/fisher/issues/448 for details.
