### ISSUE TITLE
The Future of Fisherman

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#443]
👋 Hello everyone!

I want to _rewrite_ Fisherman with a more limited, non-backward compatible scope. I want to remove flimsy features like plugin man-pages, plugin key binding reconciliation, oh-my-fish plugin compatibility, etc. The purpose of this issue is to discuss how and why. I appreciate your feedback!

## Background

I have been using Fisherman to great success for the past couple of years, but I've also grown displeased with a few things. I'd like to survey the community to see how many people are using Fisherman and try to measure how much opposition (or support) there is to start over from scratch.

The following sections describe the things I'd like to change.

### Themes

- One prompt to rule them all
- We say _theme_ when we mean prompt
  - `fish_promt.fish` (and `fish_right_prompt.fish`) === **promt**; !== _theme_
  - What's a theme? A configuratioh (env vars) to customize a prompt

Most packages in the Fisherman organization (and Oh My Fish!) are ~~themes~~ prompts. Most prompts do essentially the same, some more poorly than others. I dare to say that most people only want a nice prompt and don't care about the other features.

I don't want to continue promoting the proliferation of superficial prompts. The alternative I suggest is a single _master_ prompt and the ability to customize extensively via configuration. Your prompt configuration is essentially a theme.

A prompt is a `fish_prompt` and `fish_right_prompt` function files. A theme is a configuration, e.g., environment variables that tell the prompt the colors, symbols, styles, powerline glyphs to use.

> If you still want to create your own prompt put it in your ~/.confiffg/functions.

### Concurrency

Fisherman installs plugins concurrently. This is evidently useful if you are installing several plugins, but we could avoid this problem right off the bat if we changed Fisherman to a centralized or monolithic architecture.

What am I talking about?

- A centralized architecture consists of all packages in the same repository
- A monolithic architecture consists of all packages in the same file

I created this organization believing that it would make it easier for people to contribute their packages, but this is not how it worked out in practice. Most people prefer to create and manage their own repositories and provide custom installation options, including instructions for Fisherman, Oh My Fish!, etc.

What if Fisherman downloaded with akk the plugins built-in (disabled by default)?

### Dependencies

I don't see dependencies used much in the wild. The packages that do depend on other packages are always ~~themes~~ promps. Many plugins depend on getopts. Newer versions of fish ship with argparse, fish-shell built-in alternative. If we change plugins using getopts to use argparse, we're one step closer to a zero dependency ecosystem. Managing dependencies, specially with concurrency in picture is part of the complexity I want to avoid.

Fish-shell lacking private functions makes the whole idea of managing dependencies extremely flimsy too. This is especially true with the proliferation of non-official packages. Name collisions are bound to happen and there's nothing we can do to prevent them other than not letting youff install a such-and-such plugin.

### Plugins

Fisherman has its own plugin spec. In addition, it supports plugins written for tacklebox and Oh My Fish!. I want to define a simpler spec that is smaller in scope and closer to fish-shell defaults (and not backward compatible). The gist of the idea is that a plugin should consist of one function (the name of the plugin), completions for this function and a conf.d script (which fish-shell runs on startup by default). All of them optional (either a conf.d script or a function only should be possible too). The difference with the current Fisherman spec is that a plugin can consist of one function only.

---

Your comments and feedback are welcome! Please note this issue is still a WIP and I haven't decided anything just yet.

Cheers!

**Comment by patrickf3139** [comment]
@jorgebucaran , so glad you are coming back to the fisherman project!

> The alternative I suggest is a single master prompt and a redefinition of the concept of themes. A prompt is a fish_prompt and fish_right_prompt function while a theme is a configuration, e.g., environment variables that tell the prompt about what colors, symbols, styles, powerline glyphs to use or how to behave.

YES I love it!

> Fisherman installs plugins concurrently. This is evidently very useful if you are installing several plugins, but we could avoid this problem right off the bat if we changed fisherman to a centralized or monolithic architecture.

Isn't this how oh-my-zsh does it and some people don't like it. I'm not sure why though. I just know many people use something else to manage their plugins for zsh.

>  I'd like to remove the idea of dependencies altogether.

I was actually planning on developing a new plugin that has a dependency on another plugin. I think removing dependencies would hamstring the development of quality plugins.

>  I want to define a simpler spec that is smaller in scope and closer to fish-shell defaults (and not backward compatible).

If the new fisherman is not backwards compatible, then doesn't that mean we'd have to start with a COMPLETELY NEW ecosystem for plugins. We'd have to wait for everyone to port existing plugins to support the new fisherman before we can use them. This would make adoption extremely hard.

**Comment by jorgebucaran** [comment]
> @patrickf3139 Isn't this how oh-my-zsh does it and some people don't like it.

It's similar, yes. I created fisherman because I thought so too, but I believe the scope was too broad now. Your shell shouldn't need a plugin manager. I'm trying to evaluate if I can save fisherman or I need to create a new project. It's not an easy decision :)

> I was actually planning on developing a new plugin that has a dependency on another plugin.

Please, I recommend you use a real programming language instead.

> If the new fisherman is not backwards compatible, then doesn't that mean we'd have to start with a COMPLETELY NEW ecosystem for plugins. 

Yes, you are right.

**Comment by sijad** [comment]
I'm very happy you're back.

I'm fan of removing dependencies and by removing them concurrency seems redundant, it only make things complicated I guess.

**Comment by jorgebucaran** [comment]
😄Hi, @sijad! I was thinking of a centralized architecture, where each plugin would have its own directory in the repo or a one-file monolithic architecture, where each plugin would be defined as one or more functions. 

A monolithic architecture would make it easier to handle issues, labels, CI, builds, versions, and other things. It would make it harder to contribute new plugins, but there aren't many plugins to begin with and the number of new plugins haven't significantly increased in the last 3 years (including ohmyfish plugins).

**Comment by alexbepple** [comment]
> I don't see dependencies used much in the wild, so I'd like to remove the idea of dependencies altogether.

I am a huge fan of the dependency resolution in Fisherman. I use to modularize the config: https://github.com/alexbepple/fish-config

> Managing dependencies, specially with concurrency in mind makes fisherman very complex.

Would removing concurrency make it sufficiently simple?

**Comment by jorgebucaran** [comment]
> @alexbepple I am a huge fan of the dependency resolution in Fisherman.

Yes, it's nice and must-have in any package manager, but then I go back to what I said earlier: Your shell shouldn't need a plugin manager. There aren't enough plugins to justify it. 


From _fish-config_:

> (Fisherman) ...provides mechanism for merging, e.g. fish_user_key_bindings.

Implementing this without a fish-shell language parser, which we don't have, is complex. That's why fisherman only gets this approximately done. It works for the most part, but not without [issues](https://github.com/fisherman/fisherman/issues?utf8=%E2%9C%93&q=bindings).

> Would removing concurrency make it sufficiently simple?

A bit yes.

**Comment by jethrokuan** [comment]
I only have comment wrt to plugins and themes.

For themes, I think fish has already provided a sufficient level of abstraction, that is `fish_prompt` and `fish_right_prompt`, and I think it'll become messier if Fisherman tries to create one on top of it. However, I'd really like to see lower-level theme plugins that can be composed to form powerful prompts. E.g. a function displaying node version if any, or git branch if any etc.

For plugins, I'd always been under the impression that fisherman had been using fish's default plugin loading behaviour. What about the plugin spec would have to change?

I'm not against the removal of dependencies, I haven't seen much use for them either, except only in my own themes, which depend on low-level plugins I have written.

**Comment by kopischke** [comment]
As a user who relies on fisherman’s current feature set (notably: its ability to install OMF plugins, its dependency management and its support for key bindings) I sincerely hope today’s fisherman is not simply going to away under. I can perfectly empathise with @jorgebucaran  being unhappy with the design of fisherman and wishing to do something new, but that something new should be a different project. It’s OK to call for a new maintainer for fisherman and put your energy to use somewhere else (been there a few times myself); effectively removing the current implementation and replacing it with an incompatible one with less features under the current user bases’ collective butts, not so much.

**Comment by jorgebucaran** [comment]
> @patrickf3139 When you say, "Your shell shouldn't need a plugin manager." what do you mean by plugin manager? What does the future of fish mean if it is not going to be a plugin manager?

Fisherman is a plugin manager, but I don't believe fish-shell needs one.

**Comment by jorgebucaran** [comment]
> @jethrokuan However, I'd really like to see lower-level theme plugins that can be composed to form powerful prompts. 

Absolutely.

> For plugins, I'd always been under the impression that fisherman had been using fish's default plugin loading behaviour. What about the plugin spec would have to change?

True. The changes I have in mind are one function per plugin, no key_bindings, no special treatment of fish_prompt and friends and no copying of other files like .py, .awk files over to the install path.

**Comment by jorgebucaran** [comment]
Hi @kopischke! I'm glad you still find Fisherman useful. You've been against all my attempts to change Fisherman since 2016: https://github.com/fisherman/fisherman/issues/307. Time flies or what? :)

I can empathize with you too. Perhaps you should fork Fisherman and maintain your own fork.

**Comment by jorgebucaran** [comment]
@jethrokuan Yes, embedding the awk file, like fisher.fish itself does.

**Comment by alexbepple** [comment]
From a quick glance, [fundle](https://github.com/tuvistavie/fundle) seems to be offering a feature set very similar to Fisherman right now (including dependencies and bindings, @kopischke). So, if @jorgebucaran really decides to take Fisherman elsewhere, this might be a solution for some. And while I disagree with @jorgebucaran on whether a shell needs a dependency manager, we would probably agree that it does not need two, if one is well done. :wink:

**Comment by jorgebucaran** [comment]
@alexbepple When I say remove key bindings, I only mean removing "plugin key binding reconciliation" (like I said in the OP). This is a fisherman unique feature at the moment, definitely not in fundle.

**Comment by alexbepple** [comment]
@jorgebucaran I was being imprecise and only meant the merging of key bindings. While I am not sure, I believe Fundle achieves sth similar by referencing the original files: https://github.com/tuvistavie/fundle/pull/30.

A comment there, https://github.com/tuvistavie/fundle/pull/30#issuecomment-312912875, suggests that oh-my-fish does something similar.

**Comment by jorgebucaran** [comment]
Interesting.

**Comment by jorgebucaran** [comment]
#445

**Comment by jorgebucaran** [comment]
Not exactly what I had in mind, but a mixed approach, taking some ideas from the OP and changing modifying the CLI as originally proposed in #307 could work too and I would be willing to compromise for that.

**Comment by jethrokuan** [comment]
Some comments wrt to fisherman v3:

> Internally, fisherman 3 should use a cache/config directory layout similar to fin to prevent name collisions.

I like this, but this turns out to be a non-issue thus far. In most cases, we don't want to install a plugin with the same name, it's usually when someone forks a plugin and tries to develop it locally.

> Be silent by default please (maybe only show the spinner?).

I think the progress output format is perfectly fine as is now.

> Installing should always try to fetch a new copy of the plugin even if one already exists in the cache. The purpose of the cache should be similar to fin's, i.e, use as a fallback if there is no network.

Yes please, i usually have to `fisher rm -f` to make sure i'm not on a cached version when developing plugins.

> Drop dep ref counting. Instead, update the config from scratch every time a new item is installed or removed.

Sounds good.

**Comment by jorgebucaran** [comment]
> @jethrokuan I like this, but this turns out to be a non-issue thus far.

This is a non-breaking change, so it shouldn't matter to users.

> I think the progress output format is perfectly fine as is now.

CLI changes are not going to dramatically affect users, but let's see what I can do. I could make it verbose by default too.

**Comment by jorgebucaran** [comment]
I may be able to accomplish some goals in the OP without extreme changes. I'll start simple, and can add features like key_binding reconciliation back later. 

Please follow #445 for an actual summary of changes and the current TODO.
