### ISSUE TITLE
Installing jethrokuan/z fails to install a required z.awk file

### ISSUE THREAD

**Issue by arkadyan** [jorgebucaran/fisher#452]
I tried to install jethrokuan/z after upgrading to fisher v3, but I'm getting an error about a missing z.awk file from the z codebase.

    > fisher add jethrokuan/z
    fetching https://codeload.github.com/edc/bass/tar.gz/master
    fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
    linking ~/.config/fish/functions/bass.fish
    linking ~/.config/fish/functions/__z.fish
    linking ~/.config/fish/functions/__z_add.fish
    linking ~/.config/fish/functions/__z_clean.fish
    linking ~/.config/fish/functions/__z_complete.fish
    linking ~/.config/fish/conf.d/z.fish
    added 1 package, updated 1 package in 0.69s
    > z
    awk: can't open file /Users/arkadyan/.config/fish/functions/z.awk
     source line number 1 source file /Users/arkadyan/.config/fish/functions/z.awk
     context is
    	 >>>  <<<

**Comment by amir20** [comment]
Same issue. I did a clean install with `fisher self-remove` and `z` doesn't work.

**Comment by jorgebucaran** [comment]
@amir20 @arkadyan Acknowledged. Only `.fish` files provided by packages are copied to the installation directory.

@jethrokuan We have two options (1) embed the AWK script into z, much like I do with fisher itself or (2) put the AWK files in a place where the z function can always access them.

I'd prefer (1) as that is how I use awk myself, but what are your thoughts on this?

**Comment by amir20** [comment]
I like 1 too because its simplers and overall less files.

**Comment by jorgebucaran** [comment]
https://github.com/jethrokuan/z/commit/f3145adedffb3ab7b6203f947bb9c6eb2784ef32 🎉
