### ISSUE TITLE
Missing perl module after upgrading

### ISSUE THREAD

**Issue by vrischmann** [jorgebucaran/fisher#458]
Hello,

after upgrading to v3.0.3 I got a perl error:

    [I] ~ $ fisher add z
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    cannot install "z" -- should be <owner>/z
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    done in 0.00s
    [I] ~ $ fisher add jethrokuan/z
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    cannot install "z" -- should be <owner>/z
    fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
    linking ~/.config/fish/functions/__z.fish
    linking ~/.config/fish/functions/__z_add.fish
    linking ~/.config/fish/functions/__z_clean.fish
    linking ~/.config/fish/functions/__z_complete.fish
    linking ~/.config/fish/conf.d/z.fish
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    added 1 package in 0.00s
    [I] ~ $ fisher
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    To completely erase z's data, remove:
    /home/vincent/.local/share/z/datacannot install "z" -- should be <owner>/z
    fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
    linking ~/.config/fish/functions/__z.fish
    linking ~/.config/fish/functions/__z_add.fish
    linking ~/.config/fish/functions/__z_clean.fish
    linking ~/.config/fish/functions/__z_complete.fish
    linking ~/.config/fish/conf.d/z.fish
    Can't locate Time/HiRes.pm in @INC (you may need to install the Time::HiRes module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
    BEGIN failed--compilation aborted.
    updated 1 package in 0.00s

I'm on Fedora so I installed the module with `dnf install perl-Time-HiRes` and it works ok now.
[This](https://github.com/jorgebucaran/fisher/blob/master/fisher.fish#L7) seems to assume that if perl is installed, Time::HiRes is too but on Fedora 28 it doesn't seem to be the case.

**Comment by jorgebucaran** [comment]
@vrischmann Thank you, for reporting it. Let me fix this up. Could you tell me what is the output of:

```
uname
```

on your system?

---

BTW `z` is an invalid package specifier. Starting from V3 every package must have an owner. In this case `jethrokuan/z`.

Open your fishfile:
```
vim ~/.config/fish/fishfile
```
```diff
- z
+ jethrokuan/z
```
```
fisher
```

**Comment by vrischmann** [comment]
`uname` alone doesn't say much:

    [I] ~ $ uname
    Linux
    [I] ~ $ uname -a
    Linux thor 4.18.11-200.fc28.x86_64 #1 SMP Sun Sep 30 15:31:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jorgebucaran** [comment]
Thanks, @vrischmann. That's what I wanted to know! :)

**Comment by vrischmann** [comment]
Cool, that works. Thanks !
