### ISSUE TITLE
Official website?

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#461]
https://fisherman.github.io is still up and if anyone is still linking to it / searching there, that could be really confusing.

I think it should be taken down. BUT what if we repurposed it for an official site for fisher? I think fisher really needs it.
1) Jorge, you are often posting announcements or gathering feedback through GitHub issues. But just how many people check GH issues? You'd reach a much wider audience through an official page.
2) It'd make the fisher framework way more professional looking and we'd get more of fish users on fisher.
3) You can include some fisher history, fisher philosophy, release notes (VERY IMPORTANT), FAQ, instructions, documentation there. You were saying in the other thread about upgrading that you don't want to pollute the README too much. I agree though I think it's necessary. But if you could post it on an official website that'd be win-win!

I understand it'd be a lot of work but I and I'm sure other people would be down to help out.

**Comment by jorgebucaran** [comment]
@patrickf3139 Thanks. It's down.

<img width="1280" alt="screen shot 2018-10-07 at 15 12 51" src="https://user-images.githubusercontent.com/56996/46578931-80f59d80-ca43-11e8-9c00-e077254dc011.png">

**Comment by jorgebucaran** [comment]
@patrickf3139 Agreed. It's down now.

**Comment by patrickf3139** [comment]
> You seem to imply that not many people check GitHub issues.
Yeah I think the general assumption is to check an open source's GH issues only when you want to file a bug or are looking for tips on debugging. People generally don't assume to look in the GH issues for announcements, requests for feedback, installation instructions as you do. Given how often you post announcements through issues, I think it's worth finding a different outlet for them.

> I don't know if fisher "really" needs a website, but I agree—it would be nice to have a website.
Yeah I don't think every website really needs a website. It depends on how serious it is. I guess for a plugin framework, maybe not, but certainly many plugin frameworks do, such as oh-my-zsh.

> What alternatives to an "official" site do we have? What about a post on medium? Just curious.
I think Medium is an unusual medium (no pun intended) for hosting content related to a framework as small as fisher. BUT I do think that for what we want: announcements, instructions, even in-depth release notes, it makes sense. I can even see you, assuming you want to, write articles about the design philosophy or history of fisher, which I was very interested in (and had to look really hard for).

**Comment by jethrokuan** [comment]
I think wrt to release notes, Github's interface works fine. https://github.com/jorgebucaran/fisher/releases

Maybe this repo should have a wiki to cover the following points?

1. Migrating from v2 to v3
2. List of available plugins (to replace the search functionality)
3. Comparisons to other fish frameworks

**Comment by patrickf3139** [comment]
I totally forgot about GH wiki. I think that's enough to cover all that we want except announcements, but at least it'll be much better than issues. I think even release notes should go into wiki. Not many people check the release notes in the releases page since most open-source projects don't include them there (but rather in some kind of blog or website). Anyway we can also include FAQ and full documentation in the wiki and just link to them from the readme.

**Comment by jorgebucaran** [comment]
> @patrickf3139 It depends on how serious it is.

Lack of a website does not equate to unserious in my book. 

> I think Medium is an unusual medium (no pun intended) for hosting content related to a framework as small as fisher.

I think it would be acceptable for writing about the history and philosophy of the project in a light-hearted manner. Some of that information can make it to the README later. I agree with everything else.

The README already covers migrating from v2 to v3, but I will eventually remove this information. I will keep #450 open for a while though.

The README has no mention of existing plugins, but I can remedy that by adding a section with links to https://github.com/jorgebucaran/awesome-fish-shell and other resources. 

There is no comparison to Oh My Fish! or fundle, but perhaps there should be.

**Comment by jorgebucaran** [comment]
@patrickf3139 One more thing I need to clarify. 

Fisher is not a fish framework. It is a package manager.

Examples of package managers include npm, yarn, RubyGems, pip and homebrew. Fisher is not exactly like them, e.g., there is no central package database. Fisher is a decentralized package manager. 

The README mentions this. Fisher is *not* a package registry. Its function is to fetch fish scripts and put them in place so that your shell can find them. To publish a package we put our code online. On GitHub, GitLab, BitBucket, and so on.

On the other hand, frameworks can take over your configuration, run code on shell startup, add new functions to your shell, modify environment variables, etc. They also create framework lock-in and dependency.

**Comment by patrickf3139** [comment]
> Fisher is not a fish framework. It is a package manager.

Thank you for the clarification 👍

**Comment by jorgebucaran** [comment]
Closing due to lack of feedback. Maybe one day. 

In the meantime: https://jorgebucaran.com/fisher :)
