### ISSUE TITLE
Updated time incorrect on fisher v3.0.8

### ISSUE THREAD

**Issue by norcalli** [jorgebucaran/fisher#463]
![image](https://user-images.githubusercontent.com/296363/46627071-1baab680-caee-11e8-9b5c-403668d457ac.png)

Recently updated fisher to 3.0.8 (which seemed to fix the `--complete` issues), but a minor bug is that the time displayed seems to be not subtracting `date +%s` epoch, and shows what looks like a timestamp.

**Comment by jorgebucaran** [comment]
@norcalli OS and  fish version, please.

**Comment by jorgebucaran** [comment]
> @norcalli ...which seemed to fix the --complete issues

That's a V2 to V3 upgrade issue. I'll add it to the guide. If you still see it remove the completions file:

```fish
rm -f ~/.config/fish/completions/fisher.fish
```

**Comment by norcalli** [comment]
```
OS: Arch Linux x86_64
Host: Inspiron 5675 1.1.2
Kernel: 4.18.10-arch1-1-ARCH
Shell: fish 2.7.1
fisher version 3.0.8 ~/.config/fish/functions/fisher.fish
```

**Comment by jorgebucaran** [comment]
Thank you. Does your OS support `date +%s%N` to retrieve the epoch in milliseconds?

**Comment by jorgebucaran** [comment]
@norcalli Please run and show me the output of the following command.

```fish
date +%s%N
```

**Comment by norcalli** [comment]
```
~
❯ date +%s%N
1539045791962453044

~
❯ date +%s%3N
1539045796379

~
❯ bash
[ashkan@ashkan ~]$ date +%s%3N
1539045800006
[ashkan@ashkan ~]$ date +%s%N
1539045804881464253
```

**Comment by jorgebucaran** [comment]
@norcalli Interesting. Could you also run this and show me the output?

```fish
set -l start (command date "+%s%3N" | command awk '{ sub(/%?3N$/,"000"); print $0 }')
command date "+%s%3N" | command awk "{ sub(/%?3N\$/,\"000\"); print (\$0 - 0$start)/1000 }"
```

**Comment by norcalli** [comment]
I created a user for you on my machine if you'd like to play around with. I authorized it with your public github keys, so you should be able to ssh in from any machine that has github access.

```
ssh guest@kiani.io
```

**Comment by jorgebucaran** [comment]
@norcalli Time should be displayed correctly now (55b543e). Please update to the latest fisher.

```
fisher self-update
```

**Comment by norcalli** [comment]
Works! Thanks!
