### ISSUE TITLE
List of fisher supported prompts?

### ISSUE THREAD

**Issue by pablocrivella** [jorgebucaran/fisher#466]
Where can i find a list of themes supported by fisher? I already tried some of omf without any luck.

**Comment by jorgebucaran** [comment]
@pablocrivella There isn't one at the moment. Which themes (they are not "themes", but prompts—fish has no concept of themes) didn't work?

**Comment by jorgebucaran** [comment]
@pablocrivella There isn't one yet. Which ~~themes~~ prompts didn't work? 

> **Note**: They are incorrectly referred to as "themes" when _prompts_ is what they are.

**Comment by pablocrivella** [comment]
Thanks for the quick response and clarification @jorgebucaran :)

This one for example didn't work: 
- https://github.com/oh-my-fish/theme-chain

And i found one prompt that worked nicely: 
- https://github.com/fisherman/sol

Should those prompts that work need to be added to:  https://github.com/jorgebucaran/awesome-fish-shell#simple-prompts?

**Comment by jorgebucaran** [comment]
oh-my-fish/theme-chain uses the Oh My Fish `bundle` file to list dependencies. I still haven't decided whether I am going to support their `bundle` file in fisher. You can usually get around this by installing whatever package is listed in that file. Unfortunately, in this case, https://github.com/oh-my-fish/plugin-vcs uses an unorthodox directory structure which fisher doesn't support (nested directories). 



> @pablocrivella Should those prompts that work need to be added to https://github.com/jorgebucaran/awesome-fish-shell#simple-prompts? 

Yes, I'd like that. Now that fisher V3 is out, I want to improve the awesome-\* repo with this kind of information.

Tangentially related → https://github.com/jorgebucaran/fisher/issues/461#issuecomment-427638774

**Comment by pablocrivella** [comment]
Alright! Since we will probably have that list there i'll close this issue! Thanks!
