### ISSUE TITLE
Fisher add doesn't work at all

### ISSUE THREAD

**Issue by Tyilo** [jorgebucaran/fisher#469]
I think this is basically the same problem as in #411 

Running
```
$ fisher add jethrokuan/z
To completely erase z's data, remove:
/home/tyilo/.local/share/z/data
```

Hangs after the the first two lines of output.

Running
```
$ fish -c 'fisher add jethrokuan/z'
To completely erase z's data, remove:
/home/tyilo/.local/share/z/data
fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
linking ~/.config/fish/functions/__z.fish
linking ~/.config/fish/functions/__z_add.fish
linking ~/.config/fish/functions/__z_clean.fish
linking ~/.config/fish/functions/__z_complete.fish
linking ~/.config/fish/conf.d/z.fish
updated 1 package in 1538974327.59s
```

works.

As this seems like a bug that will never be fixed in fisher, I will switch to another fish package manager.

**Comment by jorgebucaran** [comment]
@Tyilo So, it seems fisher is just broken for you. We know that the problem is possibly around the jobs wait algorithm. Are you willing to work with me to debug this and help me fix the bug?

**Comment by jorgebucaran** [comment]
@Tyilo Are you still using Arch?

cc @Pyrepenol @aureooms Are you two also using Arch? Please confirm your OS and fish versions.

**Comment by jorgebucaran** [comment]
@Pyrepenol @aureooms @Tyilo Is your OS Arch? I need a profile log using fish -p like you did for me last time. Also, could you try running `fisher` with only one package in your fishfile?

**Comment by Tyilo** [comment]
I found the problematic line in my `config.fish` that causes this:

```
stty werase undef
```

Having only this line in your `config.fish` makes fisher hang. Can you reproduce this?

**Comment by jorgebucaran** [comment]
@Tyilo Actually, yes. I was able to reproduce it on macOS with that line added to my `config.fish`. Do you know what it does?

**Comment by jorgebucaran** [comment]
It appears as if `stty` causes background jobs to stop for some reason.

**Comment by jorgebucaran** [comment]
@Tyilo The following too causes fisher to exit correctly without having to remove `stty werase undef` from your `config.fish`.

```fish
if status --is-interactive
    stty werase undef
end
```

**Comment by jorgebucaran** [comment]
@krader1961 @faho `stty` is config.fish causes process sent to the background to stop, causing `fisher` to hang. Do you know if there's anything we can do to remedy this situation?

**Comment by jorgebucaran** [comment]
@Tyilo Running stty in your config.fish stops background processes. Fisher downloads packages in the background, so this makes it hang. This is a fish bug. This is not a fisher bug.

Wrapping your `stty` commands in `if status --is-interactive` in your `config.fish` will fix the issue and I recommend you do that, whether you end up using fisher or not.

Good luck!

**Comment by jorgebucaran** [comment]
@Tyilo Running `stty` in your config.fish stops background processes. Fisher downloads packages in the background, so this makes it hang. This is not a fisher bug.  This is a fish bug (https://github.com/fish-shell/fish-shell/issues/2980). 

Wrapping your `stty` commands in `if status --is-interactive` in your `config.fish` will fix the issue and I recommend you do that, whether you are using fisher or not.
