### ISSUE TITLE
The removal of the `update` command

### ISSUE THREAD

**Issue by bbuck** [jorgebucaran/fisher#474]
I noticed in the V3 release notes you removed the `update` command and run updates on all packages when adding a new one. I think this behavior is fine, since you also allow locking versions.

That being said, I don't add/remove packages constantly, as a matter of fact the last time I changed packages was months ago. I have a set of packages and theme that I use and depend on -- but now I've lost the ability to update them, if I want to update to their latest version it seems I need to add and then remove some other random package.

I think it best to reinstate an update command for those that aren't making regular package changes.

**Comment by jorgebucaran** [comment]
> @bbuck I've lost the ability to update them, if I want to update to their latest version it seems I need to add and then remove some other random package.

No, you didn't lose that ability. To update all your packages run `fisher`. See [updating packages](https://github.com/jorgebucaran/fisher#updating-packages). 

I'll try to add this knowledge to the `help` command from which is currently missing.

**Comment by bbuck** [comment]
My apologies, thanks for the prompt reply. I was looking at your upgrade guides and IIRC you didn't mention using `fisher` in place of `fisher update`.

**Comment by jorgebucaran** [comment]
@bbuck I'll update them right away. I've also a brief mention in the usage help that `fisher help` prints.

Thanks!

**Comment by jorgebucaran** [comment]
Added more information to the help in 207ccf00b6edb8def26c9514ee8b07419a51c7c2. 👋
