### ISSUE TITLE
oh my fish compatibility

### ISSUE THREAD

**Issue by Globegitter** [jorgebucaran/fisher#475]
oh my fish compatibility is mentioned but then not described. How can I install e.g. am oh my fish theme with fisher?

**Comment by jorgebucaran** [comment]
> @Globegitter How can I install e.g. am oh my fish theme with fisher?

The same way you install any other package—there are no special instructions to install an Oh My Fish! package.

```
fisher add oh-my-fish/theme-bobthefish
```

The [3.0.0 release notes](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0) talk about this, but that didn't make it to the documentation.

- Packages that include `init.fish`, `uninstall.fish`, `key_bindings.fish` or recursive directories should work out of the box
- `init_` events, hooks, Oh My Fish! core library functions and Oh My Fish! environment variables such as `$OMF_PATH`, `$package`, `$path` and `$dependencies` are not currently supported

**Comment by Globegitter** [comment]
ok great thanks for clearing that up in detail got it working now.

**Comment by jorgebucaran** [comment]
@Globegitter Cheers! 👋
