### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GratefulDave** [jorgebucaran/fisher#476]
I am trying to install this on a brand new MacBook Pro with Mojave.

I executed this cmd line: $ curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher. This was the response:

% Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 15694 100 15694 0 0 30893 0 --:--:-- --:--:-- --:--:-- 30893
Davids-MBP-2018:bin davidandrews$ fisher pyenv

to which I get cmd not found.

I am trying to install multiple environments for a data science class I am taking and following these directions:

https://weknowinc.com/blog/running-multiple-python-versions-mac-osx

I was unable to figure out how to remove Python either.

I apologize. I am a noob. The statistics & math of data science and using the Python IDE/Jupiter Notebooks but this really new to me. 

Any help would be greatly appreciated.

**Comment by jorgebucaran** [comment]
@GratefulDave Your shell [may take a few seconds](https://github.com/fish-shell/fish-shell/blob/35c01bcba225a1341abf5a96b7fb9fa80715025c/src/autoload.cpp#L25) before refreshing your functions path.

I'll find a space to mention this in the documentation. Thanks! 🙌 

Related: https://github.com/jorgebucaran/fisher/issues/439

---

One thing you could do if you encounter this problem again in the future, e.g. when installing Fisher on a new system is to start a new session or replace the running shell with a new one after the download is complete.

```
exec fish
```

**Comment by jorgebucaran** [comment]
@GratefulDave FYI https://github.com/jorgebucaran/fisher/issues/477

**Comment by jorgebucaran** [comment]
@GratefulDave Can you please confirm that your problem was solved?

**Comment by jorgebucaran** [comment]
@GratefulDave Can you please confirm that the problem is gone?

**Comment by jorgebucaran** [comment]
@GratefulDave Can you please confirm that the problem was solved?

**Comment by jorgebucaran** [comment]
@GratefulDave One more thing I just noticed the installation and usage instructions in https://weknowinc.com/blog/running-multiple-python-versions-mac-osx are outdated. 

To install Fisher follow the [instructions](https://github.com/jorgebucaran/fisher#installation) in the README. 

To install a package with Fisher use the [`add`](https://github.com/jorgebucaran/fisher#adding-packages) command followed by:

- the path to the repository on GitHub

_OR_

- the address of the server and the path to the repository for packages hosted elsewhere
