### ISSUE TITLE
Do we need an installer?

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#477]
An installer can prevent #439 or #476. Additionally, it can register completions before having to run `fisher` once, show warnings if the user is running an old version of fish or if the system requirements aren't met, show a link to the documentation, collect analytics data, etc.

On the other hand, installing Fisher is easy and if `fisher` is not immediately available after downloading it (due to fish autoload [delay](https://github.com/fish-shell/fish-shell/blob/35c01bcba225a1341abf5a96b7fb9fa80715025c/src/autoload.cpp#L25)), you can launch a new shell. Not a problem for me.

The other issue is distributing the installer. Should it be an additional script one has to download first and then run or a curlpipe? The first alternative plays it safe, but it's more work. The curlpipe option is neat, but curlpipe installers are usually frowned upon by the community. They also open the door to a category of bugs we currently don't need to worry about, e.g. installer failure.

I say no installer.

**Comment by patrickf3139** [comment]
I am a weak no to the installer. I like keeping fisher light and simple. Perhaps just a bit more documentation in the GH Wiki or read me to tell users the things you listed above will do. Probably only technically competent power users who can do research use fish anyway.

**Comment by jorgebucaran** [comment]
Thanks for your feedback @patrickf3139.

> Probably only technically competent power users who can do research use fish anyway.

I can only speak for myself. When I found fish, I was attracted to its philosophy vision and ease of use. I also enjoy the fish language grammar more than that of sh. I don't think every fish user is  a power user and I am definitely not a power user. 

I like Fisher's minimal, non-invasive, no bells & whistles approach as opposed to yielding power to a magical installer.
