### ISSUE TITLE
fisher rm should  print an error message when the package name is invalid or not found

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#478]
`fisher rm blahblahblah` should probably given an error message or some indication that `blahblahblah` is not a package currently installed.
WIth `fisher add blahblahblah` it at least outputs `cannot install github.com/blahblahblah -- is this a valid package?`

**Comment by jorgebucaran** [comment]
@patrickf3139 Something like this would be nice.

```console
fisher rm blahblahblah
cannot remove blahblahblah -- package not found
```

Because of how we remove everything before installing or updating new packages, this is actually harder than it seems. I'll see what I can do.

**Comment by jorgebucaran** [comment]
@patrickf3139 By the way, how did this come up? Did you type the package name incorrectly or was it something else?

**Comment by patrickf3139** [comment]
This came up because I was used to fisher V2 conventions of not needing to specify the org name when specifying the prefix. e.g. bass instead of edc/bass when trying to remove.

**Comment by jorgebucaran** [comment]
@patrickf3139 Thanks.

Be sure to update to the latest Fisher with `self-update` to try this out.

Cheers!

**Comment by patrickf3139** [comment]
works great, thanks for the quick patch!
