### ISSUE TITLE
fisher key_bindings support

### ISSUE THREAD

**Issue by jethrokuan** [jorgebucaran/fisher#482]
I get the following error using the latest fisher and the fzf plugin:

```
fish: The function call stack limit has been exceeded. Do you have an accidental infinite loop?
            fish_user_key_bindings_copy
            ^
in function 'fish_user_key_bindings_copy'
	called on standard input
```

**Comment by jorgebucaran** [comment]
@jethrokuan This indicates that there already was a `fish_user_key_bindings` function defined on your system calling `fish_user_key_bindings_copy`. Creating a copy of that function and calling it will cause an inifite loop. 

Maybe you were (inadvertently or not) trying to shim `fish_user_key_bindings` yourself. This could be the result of faulty upgrade to V3 or code in your fish configuration. I suspect you have some code in your `config.fish` making copies of `fish_user_key_bindings`.

**Comment by jorgebucaran** [comment]
@jethrokuan It's possible that you copied some outdated code from https://github.com/jorgebucaran/fisher/issues/448 to your `config.fish` before built-in support for custom key bindings was added in [3.1.0](https://github.com/jorgebucaran/fisher/releases/tag/3.1.0#custom-key-bindings) (https://github.com/jorgebucaran/fisher/commit/c9974efc1275c27d5ee065afbd1610de55fae108).

You should be able to fix this problem by removing that code from your `config.fish` if that was the case. I've already updated https://github.com/jorgebucaran/fisher/issues/448 to reflect the current state of affairs.

**Comment by jorgebucaran** [comment]
@jethrokuan Ping

**Comment by jorgebucaran** [comment]
@jethrokuan Any chance you can confirm the solution I gave you above?

**Comment by jethrokuan** [comment]
I can only look at it a few hours later, sorry for the wait

**Comment by jethrokuan** [comment]
my `config.fish` had a snippet that sourced all fish files in the `conf.d` folder. I can't remember when I added this in, but removing it resolved the issue.
