### ISSUE TITLE
fisher add with invalid package still results in that package in fishfile

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#484]
Repro
```
$ fisher add invalid-package
$ cat fishfile | grep invalid-package
invalid-package
```

**Comment by jorgebucaran** [comment]
@patrickf3139 Using the command line to add and remove packages is a facade for modifying and committing changes to your fishfile in a single step. 

Running `add invalid-package` is equivalent to opening your fishfile, adding `invalid-package` to it, and then running `fisher`. If Fisher can't install any packages from it, it will tell you so. But it will not remove invalid entries from the fishfile.

**Comment by patrickf3139** [comment]
Oh interesting. I understand that the CLI is just a wrapper around adding the package to the file and trying to update, but can't it also have an ending callback/hook/function to remove the package if it knew it was invalid?
Anyway, I guess I need to change my mindset about fisher. Fisher is not really a CLI but a wrapper around manual interaction with the fishfile

**Comment by jorgebucaran** [comment]
@patrickf3139 We could but what if the package installation fails because the server is not available or because you are offline? Could you elaborate on your use case?

**Comment by patrickf3139** [comment]
Oh I see--that's a good point.
No use case--I was just surprised by the behavior because for most tools, if they can verify that the operation is bad, they don't commit any changes.

**Comment by jorgebucaran** [comment]
@patrickf3139 I think I misunderstood this issue. It seems you only wanted Fisher to avoid adding invalid packages to the fishfile like "foo" (instead of foo/foo) or "--bad-name--"—essentially #492.

**Comment by patrickf3139** [comment]
Yes!

**Comment by patrickf3139** [comment]
How about for (2), we not add it but also output something like "Could not connect to the repository. Please double check your Internet connection or the repository address" and not add it. My idea is only add it when we are for sure that the package name is valid.

**Comment by jorgebucaran** [comment]
@patrickf3139 Yeah, we already say something along those lines: "cannot connect to server -- searching in ../cache/".

Now, I'm going to improve (2) as follows. If a package fails to install, it will not be added to the fishfile unless it was already in it. So, packages that fail to install via the command line (`fisher add ...`) will not be added.

**Comment by patrickf3139** [comment]
Sweet! Love the idea!
