### ISSUE TITLE
confused on relationship between fisher and fisherman

### ISSUE THREAD

**Issue by lee2sman** [jorgebucaran/fisher#485]
background:
fisher --version prints:
```fisher version 3.1.1 ~/.config/fish/functions/fisher.fish```

When I run ```fisher ls``` it comes back empty

When I run ```fisher``` I get:

fetching https://codeload.github.com/z/tar.gz/master
fetching https://codeload.github.com/bass/tar.gz/master
cannot install github.com/bass -- is this a valid package?
cannot install github.com/z -- is this a valid package?
done in 0.78s

Is this because I previously had *fisherman*? I don't understand how the two relate.

In my ```~/.config/fisherman``` directory I have ```free getopts git-util host_info humanize_duration joker last_job_id wd_info pwd_is_home segment z```

Should I delete this directory and then reinstall things with ```fisher add``` ?

Thanks for any insight you can give.

**Comment by lee2sman** [comment]
Note that I recently did fisher self-update

**Comment by lee2sman** [comment]
My fishfile had just two lines:

```
z
bass
```

so I deleted these lines then did ```fisher add jethrokuan/z``` and ```fisher add edc/bass``` so hopefully this will clear up any issues. Still i don't understand how packages listed under the fisherman folder are used (seems like they're not)

**Comment by jorgebucaran** [comment]
@lee2sman Did you see https://github.com/jorgebucaran/fisher/issues/450?

**Comment by jorgebucaran** [comment]
@lee2sman See [Migrating from V2 to V3](https://github.com/jorgebucaran/fisher/issues/450).

> Is this because I previously had *Fisherman*? 
> Should I delete this directory and then reinstall things with `fisher add` ?

Yes, and yes. This is explained in the migration guide.
