### ISSUE TITLE
Custom install prefix guidance results in no custom prompt or default function overrides

### ISSUE THREAD

**Issue by cormacrelf** [jorgebucaran/fisher#487]
The suggested code for a separate fisher install has:

```fish
set -g fish_function_path $fish_function_path $fisher_path/functions
set -g fish_complete_path $fish_complete_path $fisher_path/completions
```

Because `prefix/functions` is appended to `fish_function_path`, the system default function directories prevail.

```
$ type fish_prompt
fish_prompt is a function with definition
# Defined in /usr/local/Cellar/fish/2.7.1/share/fish/functions/fish_prompt.fish @ line 5
...
```

A better version, that lets the fisher functions override, lets you override them with your own in ~/.config/fish/functions, and does the same for completions:

```fish
# separate fisher install
set -l normal_fish $HOME/.config/fish
set -g fisher_path $HOME/.config/fish/erman
mkdir -p $fisher_path
set -g fish_function_path $normal_fish/functions $fisher_path/functions $fish_function_path 
set -g fish_complete_path $normal_fish/completions $fisher_path/completions $fish_complete_path
function source_confd
  for file in $fisher_path/conf.d/*.fish
    builtin source $file 2> /dev/null
  end
end
# fisherman bootstrap
if not test -f $fisher_path/functions/fisher.fish
  echo "... installing fisherman to $fisher_path ..."
  curl https://git.io/fisher --create-dirs -sLo $fisher_path/functions/fisher.fish
  fisher
end
source_confd
```

This seems like a lot of code for a pretty simple requirement -- is there any way to build some of it into the tool?

**Comment by jorgebucaran** [comment]
> @cormacrelf ...is there any way to build some of it into the tool?

No, I don't think so, but I'm always open to suggestions.

**Comment by cormacrelf** [comment]
Ok, but still probably allow ~/.config/fish/functions to beat the fisher ones. It's pretty useful for customizing a theme without forking the associated repo and changing your fishfile. Like `fish_mode_prompt`, which is fairly clunky in quite a lot of themes.

**Comment by jorgebucaran** [comment]
@cormacrelf I agree we should prepend.

```fish
set fish_function_path $fisher_path/functions $fish_function_path
set fish_complete_path $fisher_path/completions $fish_complete_path
```

Can you send me a PR with that?

**Comment by cormacrelf** [comment]
That's not what I mean. I mean

```
set -g fisher_path /path/to/other
set -l my_fish ~/.config/fish
set fish_function_path $my_fish/functions $fisher_path/functions $fish_function_path
set fish_complete_path $my_fish/completions $fisher_path/completions $fish_complete_path
```

Basically, this is because the whole point of separate fisher installs is to maintain your own function defs from ones managed by fisher without name collisions, because fisher tries to own whatever fisher_path you tell it to and will delete or overwrite anything it finds in there. Also because maintaining a Git repository over your fish root is really annoying if you have to write `*\n!.gitignore` + `!my_function.fish` for every single user-defined function you want Git to actually track.

There are **3** groups of fish_function_path elements that are being reordered here.

Current README's guidance has the following precedence, 1 is searched first:

1. **User-defined** `~/.config/fish/functions`
2. **System**  the various native fish directories put there when you `brew/apt install`
3. **Fisher** `$fisher_path/functions`

You're suggesting:

1. *fisher*
2. **user-defined** -- AFTER fisher! So you can't override anything.
3. *system*

I'm suggesting

1. **user-defined**
2. *fisher*
3. *user-defined* again (because no point removing it)
4. *system*

**Comment by jorgebucaran** [comment]
@cormacrelf Sounds good. The documentation should propose the configuration that gives users the highest priority as you recommend.

**Comment by jorgebucaran** [comment]
@cormacrelf The custom installation instructions let you override both Fisher-installed and system-wide functions.

1. User-defined -- Can override everything!
2. System
3. Fisher

**Comment by jorgebucaran** [comment]
Related #479.

**Comment by jorgebucaran** [comment]
@cormacrelf Took me a while, but I see what you mean now. You want Fisher to override the system, but allow the user to override Fisher. 

I don't use `$fisher_path` myself, and I rarely override system-defined functions, so either way (prepending or appending) works for me. 

The custom installation instructions let you override both Fisher-installed and system-wide functions.

1. User-defined
2. System
3. Fisher

Related #479.

**Comment by cormacrelf** [comment]
@jorgebucaran Really?

* The suggestion in the readme doesn't include the ability to use themes. Core feature. And it's right up the top where new users are going to see it and use it.
* I'm pretty good at this (read: [my dotfiles](https://github.com/cormacrelf/dotfiles) are huge) and it took me a *long* time, including digging into how prompts are made/defined, to work out what was wrong. For a while I just used the convoluted `.gitignore` described above and it was pretty painful.
* The amount of detail in the readme increased by ~1.5 LOC and one sentence. At least enable Wikis on the repo so it can live there.

**Comment by jorgebucaran** [comment]
@cormacrelf It's possible I missed something. Why can't you use themes?

**Comment by cormacrelf** [comment]
> Current README's guidance has the following precedence, 1 is searched first:
> 1.    User-defined ~/.config/fish/functions
> 2.   System the various native fish directories put there when you brew/apt install
> 3.   Fisher $fisher_path/functions

You know how themes work right? Themes are defined by `fish_prompt`, which is a function that may be autoloaded from the system fish function direcetory. Or any fish function path entry.

```fish
# in plain fish, without any configuration or fisher or anything
$ type fish_prompt
fish_prompt is a function with definition
# Defined in /usr/local/Cellar/fish/2.7.1/share/fish/functions/fish_prompt.fish @ line 5
...
```

That's a system path, which if you follow the README means it prevails over any installed themes in fisher. So fisher-installed themes don't work at all. I did put it in the title of the issue, after all.

**Comment by jorgebucaran** [comment]
@cormacrelf I don't use `$fisher_path`, that's why I didn't notice.

Don't be rude. I know how prompts work. Your question only shows you don't have patience (or gratitude). Nevertheless, thank you, for helping me improve Fisher for everyone. 



Here is one way to solve it the issue:

```fish
set -g fisher_path /path/to/another/location

set fish_function_path $fish_function_path[1] $fisher_path/functions $fish_function_path[2..-1]
set fish_complete_path $fish_complete_path[1] $fisher_path/completions $fish_complete_path[2..-1]
```

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/fisher/commit/a8d7fb78305888dda75f93ae05086caa620047f6 🎉

**Comment by jorgebucaran** [comment]
@cormacrelf
