### ISSUE TITLE
nitro prompt

### ISSUE THREAD

**Issue by laughedelic** [jorgebucaran/fisher#491]
Who was the author of the nitro prompt? https://github.com/fisherman/nitro doesn't redirect anywhere. I really liked this prompt.. I guess it just got deleted in #446, but probably someone still has the repo locally and can recreate it?

**Comment by jorgebucaran** [comment]
@laughedelic I was. The prompt is basically (if not exactly) https://github.com/jorgebucaran/fish-metro with a different color palette. My plan is to rewrite Metro and introduce environment variables that allow users to customize the color palette. So, you can have them all in one.

**Comment by jorgebucaran** [comment]
@laughedelic I was. The prompt is basically a copy of [jorgebucaran/fish-metro](https://github.com/jorgebucaran/fish-metro) with a different color palette. My plan is to rewrite Metro and introduce environment variables that allow users to customize the color palette.

**Comment by laughedelic** [comment]
Yeah, the colors were exactly what I liked about nitro... So could you post that color palette somewhere (probably just in a gist)?

**Comment by jorgebucaran** [comment]
@laughedelic I can't remember what colors I used, but it seems that the colors were not hardcoded in the file, so there is no "palette" like I said. See this fork I found: https://github.com/lanzafame/nitro. The colors are the result of tweaking with the terminal.

**Comment by laughedelic** [comment]
Oh great! I'll just use this fork, it works as before. And this explains why I liked the colors: they fitted with my terminal color palette 😄

**Comment by jorgebucaran** [comment]
Awesome! 🎉
