### ISSUE TITLE
Don't add invalid packages to fishfile

### ISSUE THREAD

**Issue by fikovnik** [jorgebucaran/fisher#492]
I'm not sure how to properly describe this, but here is what is happening. I ran the following:

```
> fisher add --help
```

which failed complaining that no such repository exists. Fair point, my bad, but since then it keeps appearing in any action I do:

```
> fisher rm smh/base16-shell-fish
...
fetching https://codeload.github.com/--help/tar.gz/master
...
```

To get rid of it, I had to run 
```
> fisher rm --help
cannot remove "--help" -- package not found
``` 
so there is some inconsistency. It would be great if the arguments are checked perhaps a regex for a valid repo name?

Btw: every time I install a new package it seems like all the already installed packages get reinstalled. Is that on purpose?

**Comment by jorgebucaran** [comment]
@fikovnik Sounds reasonable. Yes, can do! 👍

**Comment by fikovnik** [comment]
Amazing, could you please also comment on the last question? Thank you!

**Comment by jorgebucaran** [comment]
Just did.

**Comment by jorgebucaran** [comment]
@fikovnik Should be fixed now. 🙌

See: 49785a134be87dd3a85db9268206cc5aec755db8 39e9f3f34079a1705f4580fa232fe15d10b632c0
