### ISSUE TITLE
Install the packages in differents location

### ISSUE THREAD

**Issue by dancespiele** [jorgebucaran/fisher#493]
Hello again Jorge :)

Is there a way to install the packages in another location?

for example:

`fisher add github.com/jorgebucaran/superfine ~/my-folder`

**Comment by jorgebucaran** [comment]
Hola @dancespiele :)

See [changing the installation prefix](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix) in the documentation.

Also related: https://github.com/jorgebucaran/fisher/issues/479.

**Comment by dancespiele** [comment]
I read but has it to be before of the installation? is the file .config/fish/config.fish that I have to write it. Sorry I didn't understand very well

**Comment by jorgebucaran** [comment]
Yes, just add the code from that section to your `~/.config/fish/config.fish`. 

Let me know if you still encounter any problems. I'm here to help.

**Comment by dancespiele** [comment]
And to download would be it like this? 
`curl https://git.io/fisher`
or is the same
`curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish`

**Comment by jorgebucaran** [comment]
Fisher installation instructions are described in the README [here](https://github.com/jorgebucaran/fisher#installation). Please try to stay on topic.

**Comment by jorgebucaran** [comment]
Follow the [installation instructions](https://github.com/jorgebucaran/fisher#installation) in the README.

And please try to stay on topic. 😉
