### ISSUE TITLE
Would it make any sense to link to #443 from outdated fisherman resources?

### ISSUE THREAD

**Issue by waynew** [jorgebucaran/fisher#498]
I don't know if you still have access to the fisherman/fisherman org/repo, but I was *suuuuuper* confused for the last couple of weeks when I installed a new system and tried to get fisherman... but it was entirely gone? To  maybe be replaced by this thing called fisher??

I finally decided to start digging into the issues because I thought it probably might have been but it was definitely not clear why everything I had used a couple of months ago was all gone.

Maybe it's not necessary for most people (probably irrelevant to newcomers), but it was definitely a mystery to me.

**Comment by jorgebucaran** [comment]
> Would it make any sense to link to #443 from outdated fisherman resources?

Sure. If you think that will help your package users, feel free to link to that issue or to the following summary.

## Summary

- [(#443) The Future of Fisherman](https://github.com/jorgebucaran/fisher/issues/443)
- [(#446) I will dissolve the organization!](https://github.com/jorgebucaran/fisher/issues/446)
- [(#475) How can I install an Oh My Fish! package with Fisher?](https://github.com/jorgebucaran/fisher/issues/475)

**Comment by jorgebucaran** [comment]
## Further Clarifications

1. This repository is the same old repository. You can verify this by the fact it has the same issues, watchers, stars and forks. In addition, GitHub redirects URLs, so even old links will find their way home here. Try it.

     - [fisherman/**fisherman**](https://github.com/fisherman/fisherman)
     - [jorgebucaran/**fisher**](https://github.com/jorgebucaran/fisher)

2. Not everything you had been using is gone. Most packages is the organization has been transferred to their original owners. [`z`](https://github.com/jethrokuan/z) is back to @jethrokuan, [fish-nvm](https://github.com/FabioAntunes/fish-nvm) is back to @FabioAntunes, and so on.
