### ISSUE TITLE
Info on when plugins get updated

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#499]
I think right now updating fisher ~~plugins~~ **packages** doesn't really tell you if any packages got updated. It just says all the packages have been updated even if no package has actually changed. I think this is a potential problem because there might be a breaking change in my packages that I should know about. Or maybe I'm just curious which packages have been updated recently and I want to see the changelog.

**Comment by jorgebucaran** [comment]
@patrickf3139 You can look at your fishfile or run `fisher ls` before running `fisher` to see what will be updated.

> It just says all the packages have been updated even if no package has actually changed. 

It tells you how many packages were added, removed and updated, e.g:
- added 6 packages in 1.27s
- added 1 package, updated 7 packages in 2.11s
- updated 2 packages, removed 7 packages in 1.82s

> I think this is a potential problem because there might be a breaking change in my packages that I should know about.

Use a brach, tag or commit-ish next to the name followed by a `@` in your fishfile to lock a specific version of a package. 

```
deepblue/mermaid@1.1.5
```

**Comment by patrickf3139** [comment]
Thanks for explaining. But sorry, I'm still a bit confused. When I run fisher, all I see at the bottom is
```
updated 8 packages in 2.56s
```
Surely not all 8 packages had updates. So if one of them did upgrade to a new version, how do I know?

**Comment by jorgebucaran** [comment]
@patrickf3139 There is no feasible way to know at the moment. Package versioning is not enforced either. Perhaps the fishfile usage can be extended to carry version information about your own package. 

If you think a package was updated, go to the repository and look for a CHANGELOG yourself.

**Comment by patrickf3139** [comment]
Yeah, this is what I was referring to when I first opened my ticket. Think this is a weakness of fisher.

**Comment by jorgebucaran** [comment]
@patrickf3139 I suppose you are familiar with other language ecosystems, e.g. node, python, rust, ruby, and so on? Could you present a practical example of what you were looking for in Fisher that you already take for granted in other ecosystems?

**Comment by patrickf3139** [comment]
Yeah, bundle handles Ruby gems (libraries) and when you run update, it outputs gems that weren't updated in white and gems that were updated in green.

**Comment by jorgebucaran** [comment]
And what do you suggest Fisher do? What would you like to see when you run `fisher`? Can you provide multiple full console output examples?

The issue tracker is not a feature request list. If you create an issue I expect you to elaborate thoroughly, use examples, suggest implementation options, etc. If it's difficult to explain, then create a PR and I'll consider it.
