### ISSUE TITLE
I have mirrored 'simple'

### ISSUE THREAD

**Issue by fisxoj** [jorgebucaran/fisher#500]
Hello!  I recently started a new job and found I couldn't install the 'simple' prompt that was formerly at fisherman/simple.  So, I found a copy of the git repo on another machine and threw it up at https://github.com/fisxoj/simple, mostly for myself, but I'm happy for someone else to use it as well!  It seemed to install correctly from there, though I won't claim to know what I'm doing with fish scripting or hosting a fisher package, but I'm happy to try to fix it if it ever breaks.

Feel free to close this or whatever you deem best, just wanted to put the information out there in a place someone else might find it.  I thought I was crazy for a few days since I couldn't find any trace of it for a few days.

Thanks for fisher!

**Comment by jorgebucaran** [comment]
@fisxoj  🎉Glad you're taking over the `simple` prompt. I removed the original as part of https://github.com/jorgebucaran/fisher/issues/446.

Feel free to rebrand, change and/or improve the presentation/documentation of that project as you wish. `simple` is now yours. 

And send me a PR to https://github.com/jorgebucaran/awesome-fish-shell if you want to add it there.

**Comment by jorgebucaran** [comment]
@fisxoj Great! Thanks for letting us know. 🎉
