### ISSUE TITLE
Local packages are not installed using symbolic links 

### ISSUE THREAD

**Issue by FabioAntunes** [jorgebucaran/fisher#502]
> You can also install packages from a local directory. Local packages are managed through symbolic links so that they can be developed and used at the same time.

Just installed a local package and to see the changes I need to keep doing

```
fisher add ~/path/to/my/local/plugin
```

**Comment by FabioAntunes** [comment]
Sorry, I'm confused by this

> Local packages are installed in your fisher configuration as symlinks, but we create hard copies we move them to your functions directory. I still the think the documentation is confusing about this.

So they are actually hard copied to our `$HOME/.config/fish/functions` if they are hard copied they never get updated without running `fisher` right? so this has nothing to do with fish autoload interval.

**Comment by jorgebucaran** [comment]
@FabioAntunes Yep, you are right. I was thinking about something else. This behavior has changed over the years and my mind was in a different place in time. We are not symlinking the original files, but I think we should. I'll include this in 3.2.0. 💯 

Now, even if we do that, the docs are still wrong! Here's the problem: we source function files after installing a package. We are essentially telling the shell to forget about those files—they won't get watched for changes. So, after modifying a local package you'll have to run `fisher` or launch a new session.

**Comment by jorgebucaran** [comment]
@FabioAntunes 39e9f3f34079a1705f4580fa232fe15d10b632c0 🎉
