### ISSUE TITLE
Unable to install packages starting with `t`

### ISSUE THREAD

**Issue by tough-griff** [jorgebucaran/fisher#506]
After updating to `fisher` 3.2.1, I am seeing the following error when attempting to install a package from my own github repository. The first character of my username is being removed, thus pointing to an invalid package.

```
gyourick@hermes-sp ~/dotfiles> fisher add tough-griff/pure
fetching https://codeload.github.com/ough-griff/pure/tar.gz/master
cannot add github.com/ough-griff/pure -- is this a valid package?
done in 0.41s
```

The above occurs when running `fisher add` as well as when manually appending the package name to `fishfile`.

Any leading `t`s appears to be removed from a package name, see below:
```
gyourick@hermes-sp ~/dotfiles> fisher add tedc/bass tttttttttttttttttough-griff/pure
fetching https://codeload.github.com/ough-griff/pure/tar.gz/master
fetching https://codeload.github.com/edc/bass/tar.gz/master
cannot add github.com/ough-griff/pure -- is this a valid package?
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
added 1 package in 0.44s
```

**Comment by jorgebucaran** [comment]
@tough-griff Thanks! It was a buggy regex expression (64a812e).

You can update Fisher now. 👋

**Comment by Scrumplex** [comment]
Can you please create a new release tag? My AUR package only downloads the latest release tag

**Comment by jorgebucaran** [comment]
[Done!](https://github.com/jorgebucaran/fisher/releases/tag/3.2.2) 💯
