### ISSUE TITLE
oh-my-fish cannot find column program

### ISSUE THREAD

**Issue by italomaia** [jorgebucaran/fisher#507]
Just installed termux and fish. After installing oh-my-fish, calling omf list will show a error message complaining "column" is not available. Should I install an extra package or it is just not there yet? Thanks.

**Comment by jorgebucaran** [comment]
@italomaia [Install Fisher instead](https://github.com/jorgebucaran/fisher#installation).

**Comment by jorgebucaran** [comment]
@italomaia Try Fisher instead. 😉 

```
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
```

**Comment by jorgebucaran** [comment]
Whoops, wrong repo. But now that you're here, I'd recommend Fisher instead. 😉 

```
curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
```
