### ISSUE TITLE
Can't install local directory using a `.'

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#513]
Fisher fails to install a local directory using a `.` (current directory) as it was possible in V2.

**Comment by Scrumplex** [comment]
Can't we just use `(pwd)` instead?

**Comment by Scrumplex** [comment]
Or is this issue about relative paths in general?

**Comment by jorgebucaran** [comment]
@Scrumplex We are (actually using $PWD, which is the same) but not when the package name is `.`, only if it's `./`.

I think the solution is improving this regex:

https://github.com/jorgebucaran/fisher/blob/f1890a54d2e5f7b0b4e9aa6959085fd8184dc4e4/fisher.fish#L112-L114
