### ISSUE TITLE
Unable to install plugin dependencies: is this a valid package?

### ISSUE THREAD

**Issue by Pajk** [jorgebucaran/fisher#515]
```
> fish -v
3.0.0
> fisher -v
3.2.4
> fisher ls
empty
> fisher add jorgebucaran/fnm (or any other plugin):
fetching https://codeload.github.com/jorgebucaran/fnm/tar.gz/master
linking ~/.config/fish/functions/__fnm_index_update.fish
... more linking
fetching https://codeload.github.com/fisherman/menu/tar.gz/master
fetching https://codeload.github.com/fisherman/get_file_age/tar.gz/master
fetching https://codeload.github.com/fisherman/await/tar.gz/master
fetching https://codeload.github.com/fisherman/last_job_id/tar.gz/master
cannot add github.com/fisherman/get_file_age -- is this a valid package?
cannot add github.com/fisherman/menu -- is this a valid package?
cannot add github.com/fisherman/await -- is this a valid package?
cannot add github.com/fisherman/last_job_id -- is this a valid package?
added 1 package in 1,85s

> fnm
fish: Unknown command 'menu'
~/.config/fish/functions/fnm.fish (line 93):
```

Fisher is not able to install any dependencies.

I followed the upgrade guide to v3. I tried to clean everything related and start from scratch but it's not helping.

**Comment by Pajk** [comment]
Ok so it seems only the outdated fnm plugin was causing this issue. It was added to fishfile and every time I tried to add another plugin fisher tried to install it again.

**Comment by jorgebucaran** [comment]
Hi @Pajk! The problem is those URLs are broken and fish-fnm is outdated and currently being rewritten. 

See: #446, https://github.com/jorgebucaran/fish-nvm/pull/79, https://github.com/jorgebucaran/fish-nvm/issues/75


> ...every time I tried to add another plugin Fisher tried to install it again.


Correct. Every time you run `fisher`, `fisher add PACKAGE`, or `fisher rm PACKAGE` everything will be installed from scratch.
