### ISSUE TITLE
Fisher overwrites fish prompt on installation

### ISSUE THREAD

**Issue by carlosssanchez** [jorgebucaran/fisher#521]
After installing fisher with /` curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish`
my fish prompt reverts to the original. This is the second time I've installed it and this happens, but at least this time I made a backup. Was my prompt configured incorrectly or is this expected from fisher? I don't understand why a plugin manager would affect the prompt.

**Comment by jorgebucaran** [comment]
@carlosssanchez Do you mean after installing a prompt with Fisher?

**Comment by jorgebucaran** [comment]
Please share all the information you can. Your inquiry doesn't make sense. It looks as if you are saying that `curl` reverts your prompt, but that's improbable.

**Comment by jorgebucaran** [comment]
@carlosssanchez Where is your `fish_prompt.fish` located? What directory?

**Comment by jorgebucaran** [comment]
@carlosssanchez Do you mean after installing a prompt with Fisher? Where is your `fish_prompt.fish` located? What directory?

**Comment by carlosssanchez** [comment]
Sorry I was just going over the backup to find out more. Just after running the curl command, it deleted fish_prompt.fish, fish_right_prompt.fish, humanize_duration.fish, pwd_info.fish, pwd_is_home.fish, basically several files all related to the prompt that I had as helper functions inside /config/fish/functions. All other fish files that don't manage the prompt are untouched.

**Comment by jorgebucaran** [comment]
@carlosssanchez But where was your `fish_prompt.fish` located?

**Comment by jorgebucaran** [comment]
> @carlosssanchez Just after running the curl command, it deleted...

What do you mean by _it_? `curl` or Fisher?

**Comment by carlosssanchez** [comment]
Both? I mean running the installation command, I was next greeted by the new "Welcome to fish" prompt. 
The first time I installed fisher and this happened was a few months ago, but I installed it from Arch's AUR. 
![fishpromptdeleted](https://user-images.githubusercontent.com/38301688/51663112-382f0980-1f8c-11e9-9579-f73fac535adc.png)

Here's a screenshot of my backup .config/functions in the D/f/functions folder (top terminal) and the current one (bottom). I just installed the fzf plugin so those files are irrelevant in the bottom.

**Comment by jorgebucaran** [comment]
@carlosssanchez What installation command? You didn't say anything about AUR before.

Now, let's break this down:

- `curl` is just copying a file to a directory, so it isn't the problem. 
- You haven't run `fisher` yet, so we know the problem can't be Fisher either. 

It must be the AUR package. I have no idea who is maintaining it, but the only installation method which I support is described in the [README](https://github.com/jorgebucaran/fisher#installation) and I recommend you use that and nothing else.

**Comment by jorgebucaran** [comment]
Ah, it seems @Scrumplex maintains a package in the AUR here: https://aur.archlinux.org/packages/fisher.

@carlosssanchez Login to the AUR and leave a comment for @Scrumplex there. You shouldn't mix installation methods, use one or the other. You may also be interested in https://github.com/jorgebucaran/fisher#changing-the-installation-prefix.
