### ISSUE TITLE
fisher shows wrong install time when adding packages

### ISSUE THREAD

**Issue by aa8y** [jorgebucaran/fisher#522]
`fisher` shows the wrong install time while installing packages (see [this conversation](https://github.com/jorgebucaran/fisher/issues/450#issuecomment-451633644)) for context. As asked, I've run the following commands on the machine which has the problem.
```
> cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
> date "+%s%3N"
1548548212110
```

To make sure this is not a problem with the package, I created a `Dockerfile` and tested the steps there.
```
FROM aa8y/core:ubuntu

USER root

RUN apt-add-repository -y ppa:fish-shell/release-3 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      curl \
      fish && \
    apt-get clean && \
    rm -rf \
      /tmp/* \
      /var/lib/apt/lists/* \
      /var/tmp/
      
RUN usermod --shell /usr/bin/fish docker
USER docker

RUN curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

CMD fish
```
The steps have been run in the directory where the `Dockerfile` is present.
```
docker build -t fisher:test .
Sending build context to Docker daemon  14.85kB
Step 1/7 : FROM aa8y/core:ubuntu
 ---> 7941f3844639
Step 2/7 : USER root
 ---> Using cache
 ---> 63c7b941c757
Step 3/7 : RUN apt-add-repository -y ppa:fish-shell/release-3 &&     apt-get update &&     apt-get install -y --no-install-recommends       curl       fish &&     apt-get clean &&     rm -rf       /tmp/*       /var/lib/apt/lists/*       /var/tmp/
 ---> Using cache
 ---> ab6a21a00ce5
Step 4/7 : RUN usermod --shell /usr/bin/fish docker
 ---> Using cache
 ---> 71a34f44b9b5
Step 5/7 : USER docker
 ---> Using cache
 ---> 401fd0f8dd7b
Step 6/7 : RUN curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
 ---> Using cache
 ---> ca71f161866e
Step 7/7 : CMD fish
 ---> Running in aa78556c37f1
Removing intermediate container aa78556c37f1
 ---> 8a43854617bc
Successfully built 8a43854617bc
Successfully tagged fisher:test
> docker run --rm -it fisher:test
Welcome to fish, the friendly interactive shell
docker@3fbeb02772cd /> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
docker@3fbeb02772cd /> date "+%s%3N"
1548548390821
docker@3fbeb02772cd /> fisher add edc/bass
created new fishfile in ~/.config/fish/fishfile
fetching https://codeload.github.com/edc/bass/tar.gz/master
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
added 1 package in 0.63s
```

As we can see, the problem cannot be reproduced in a Docker container.

**Comment by aa8y** [comment]
Looks like this could have just been due to an older version of `fisher`
```
> fisher self-update
fetching https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish
linking ~/.config/fish/functions/fisher.fish
updated to 3.2.6 -- hooray!
> fisher add edc/bass
fish: Unknown command 'bass'
fish: Unknown command 'source'
fish: Unknown command '/home/aa8y/.linuxbrew/opt/nvm/nvm.sh'
fish: Unknown command '--no-use'
fish: Unknown command '';''
fish: Unknown command 'nvm'
fish: Unknown command 'use'
fish: Unknown command 'stable'
~/.config/fish/functions/nvm.fish (line 5):
  bass source (brew --prefix nvm)/nvm.sh --no-use ';' nvm $argv
  ^
in function “nvm”
  called on line 32 of file ~/.config/fish/config.fish
  with parameter list “use stable”

from sourcing file ~/.config/fish/config.fish
  called during startup

fetching https://codeload.github.com/edc/bass/tar.gz/master
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
updated 1 package in 16.98s
```
It's showing up as **16.98s** now :) I guess you can close the issue, unless you want me to run any other diagnostics.

**Comment by jorgebucaran** [comment]
@aa8y Looks better now. Why is it so slow though? Installing a few packages on my machine takes 1 or 2 seconds. Are you behind a proxy; slow internet connection?

Or perhaps your `config.fish` is not configured "properly". Would you mind sharing it with me? If it's not for public eyes, then create a private gist and send me the link (I can the comment afterward). 

I'd be happy to take a look at it.

**Comment by jorgebucaran** [comment]
@aa8y Looks better now. Why is it so slow though? Installing a few packages on my machine takes 1 or 2 seconds. Are you behind a proxy; slow internet connection?

Or perhaps your `config.fish` is not configured "properly". Would you mind sharing it with me? If it's not for public eyes, then create a private gist and send me the link (I can delete the comment later). 

I'd be happy to take a look at it.

---


This is making your shell startup slow.

```console
fish: Unknown command 'bass'
fish: Unknown command 'source'
fish: Unknown command '/home/aa8y/.linuxbrew/opt/nvm/nvm.sh'
fish: Unknown command '--no-use'
fish: Unknown command '';''
fish: Unknown command 'nvm'
fish: Unknown command 'use'
fish: Unknown command 'stable'
```

Open your `config.fish` and wrap your `bass` code like this:

```fish
if functions -q bass
    # Code should go here...
end
```

**Comment by aa8y** [comment]
@jorgebucaran I made your suggested changes to my `nvm` function and reinstalled. It did get rid of the `bass` errors but the install time is still similar to what it was before, ~16s. Here's [what my config file looks like](https://github.com/aa8y/dotfiles/blob/de1a401dfdf83265d96411ed27e5ef57f1294eef/.config/fish/config.fish#L35-L74), **excluding** the _highlighted lines_ and _line 18_.

**Comment by jorgebucaran** [comment]
@aa8y We can solve this by strategically wrapping commands you only use in interactive mode inside `status --is-interactive` in your `config.fish`.

```fish
if status is-interactive
    # These commands need to run when I run fish interactively
end
```

**Comment by jorgebucaran** [comment]
@aa8y We can solve this by wrapping commands you only use in interactive mode inside `status --is-interactive` in your `config.fish`. This way, those commands only run when you start `fish` yourself, and not when evaluating an expression like `fish -c "echo Not interactive!"`.

```fish
if status is-interactive
    # These commands need to run when I run fish interactively
end
```

Let me know if that sounds confusing.

---

Closing as the time issue has been fixed.

**Comment by aa8y** [comment]
@jorgebucaran Thank you for the suggestion. This is pretty cool and not something I knew. I change my `config.fish` and wrapped its contents in
```fish
if status is-interactive
  ...
end
```
However, that didn't change the install time of fisher.
```
> fisher add edc/bass
fetching https://codeload.github.com/edc/bass/tar.gz/master
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
updated 1 package in 15.86s
> fish -c "echo Not interactive!"
Not interactive!
```
Also, if you'd rather I create a different issue for this, I can.

**Comment by jorgebucaran** [comment]
@aa8y Before you do: can you comment out everything in your `config.fish` and try running `fisher` again?

**Comment by aa8y** [comment]
It didn't make any difference.

_**Before** commenting out_
```
> fisher add edc/bass
fetching https://codeload.github.com/edc/bass/tar.gz/master
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
updated 1 package in 15.86s
```
_**After** commenting out_
```
> source ~/.config/fish/config.fish
> fisher add edc/bass
fetching https://codeload.github.com/edc/bass/tar.gz/master
linking ~/.config/fish/functions/__bass.py
linking ~/.config/fish/functions/bass.fish
updated 1 package in 15.76s
```

**Comment by jorgebucaran** [comment]
@aa8y Do you happen to be on a slow connection? I can't think of anything else. 

Try:

```
curl https://codeload.github.com/edc/bass/tar.gz/master
```

One more thing. What about local packages --  are those slow to install too?
