### ISSUE TITLE
Fetch hangs when there are other jobs

### ISSUE THREAD

**Issue by amiller27** [jorgebucaran/fisher#523]
The loop in `_fisher_fetch` at [line 320](https://github.com/jorgebucaran/fisher/blob/master/fisher.fish#L320) never terminates if there are jobs already running in the background before running fisher.  This seems like it could be fixed by running `_fisher_fetch` inside its own subshell.

**Comment by jorgebucaran** [comment]
@amiller27 Yes, I introduced this bug in a recent commit. I'll revert it.

**Comment by jorgebucaran** [comment]
@amiller27 We should be good now. Thanks!
