### ISSUE TITLE
Update specific packages without re-installing everything

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#527]
Let's add a new command to update packages: `fisher update <package...>`.

Why? Sometimes you want to update one or more packages without re-installing everything. One of such cases is when developing a local package. After doing it a few times, even waiting a few milliseconds can be annoying. 

Using `update` will download only the specified packages and their dependency trees, reducing the total number of network requests. Updating a package should not trigger a <code><i>pkg</i>_uninstall</code> event (#526). 

Still on the table is whether we should emit a new event like <code><i>pkg</i>_update</code>. Should we also emit a <code><i>pkg</i>_install</code> event for newly added packages? 

I'm not too keen on adding new events, but maintaining consistency is one argument in their favor. ~~If I decide to add them, they'll probably come in a future minor release after 3.3.0.~~ Coming in 4.0.

**Comment by tsdh** [comment]
Will that also allow for a more safe update mode?  The single complaint I have with just running `fisher` is that it leaves you with a broken setup in case you run it on a wonky network where deleting everything works but fetching and reinstalling won't.  It would be much better if it would first download to a temporary location and then remove and install.

Also a question related to this issue: it would be interesting to know if an update was a real update or the same version has simply been reinstalled.

**Comment by jorgebucaran** [comment]
> It would be much better if it would first download to a temporary location and then remove and install.

Hmm, interesting! Thanks for the idea.

> it would be interesting to know if an update was a real update or the same version has simply been reinstalled.

I agree that it would, but that's not part of my plan this time. Thanks for the suggestion, though!

**Comment by jorgebucaran** [comment]
Implemented in [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0). :tada:
