### ISSUE TITLE
Auto-configure fish for custom `fisher_path`

### ISSUE THREAD

**Issue by jgierer12** [jorgebucaran/fisher#529]
Hi, first off amazing work on fisher and all your other fish projects! I'm really enjoying using them.

Is there a reason for not setting up fisher automatically if a custom `fisher_path` is set? i.e.

```fish
if set -q fisher_path
  set fish_function_path $fish_function_path[1] $fisher_path/functions $fish_function_path[2..-1]
  set fish_complete_path $fish_complete_path[1] $fisher_path/completions $fish_complete_path[2..-1]

  for file in $fisher_path/conf.d/*.fish
    builtin source $file 2> /dev/null
  end
end
```

It feels a little unnecessary/boilerplate-y having to set these up manually.

**Comment by jorgebucaran** [comment]
@jgierer12 How would you do that?

**Comment by jgierer12** [comment]
Hmm, I just realized that the "official" way to install fisher puts the `fisher` function in the user config folder. I have installed [fisher from the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fisher) which installs the fisher function into `/usr/share/fish/vendor_functions.d`, so I assumed that it would simply be a matter of putting the above snippet into `/usr/share/fish/vendor_conf.d`. But of course if fisher itself lives in the `fisher_path` that isn't possible.

**Comment by jorgebucaran** [comment]
@jgierer12 Exactly. Fisher doesn't run any code on startup and it would be undesirable if it did as not everyone uses a custom `$fisher_path`. Heck, some people ( Hey! 🙋‍♂️) don't even use a `config.fish`.

**Comment by jgierer12** [comment]
> Create a configuration snippet (`conf.d/set_fisher_path.fish`) with the setup you need.

Yes, that is exactly what I do currently.

Would have still been nice if fisher could add that automatically since if people *do* have a custom `fisher_path`, they'll want to set up that stuff in 99% of cases anyways. But, I totally see that this wouldn't be worth the effort to implement (if possible in a cross-platform compatible way at all) hence why I closed the issue again.
