### ISSUE TITLE
Cannot install remote plugins/prompts ( -- is this a valid package?)

### ISSUE THREAD

**Issue by Scotsguy** [jorgebucaran/fisher#530]
Whenever I try to install a package (for example, `fisher add jorgebucaran/fish-spark`), I get the following output: `fisher: cannot add github.com/jorgebucaran/fish-spark -- is this a valid package?`. When I git clone the repo and install it locally, it works just fine.
Confusingly, the same error happened when I copied my ~/.config/fish/ to a remote machine - when I deleted that folder it worked fine. However, deleting that folder _locally_ didn't fix the issue.
I have an OMF install that potentially left remains, however I believe I've deleted mostly everything that could be loaded by fish.

Some info:
OS: Manjaro Linux
fish version 3.0.1
fisher version 3.2.7, ~/.config/fish/functions/fisher.fish

**Comment by jorgebucaran** [comment]
@Scotsguy Please run and post the output you get from running the following commands: 

```fish
type curl
echo $XDG_CONFIG_HOME
echo $XDG_CACHE_HOME
la ~/.config
la ~/.config/conf.d
la ~/.config/fisher
cat ~./config/fish/fishfile
```

It would also help me debug this issue if you can post the contents of your `config.fish`.

**Comment by Scotsguy** [comment]
I didn't upgrade, since I didn't use fish before recently

type curl
`curl is /bin/curl`

[$XDG_CONFIG_HOME and $XDG_CACHE_HOME are both empty]

[\~/.config has a lot of files from different programs in it, I don't want to post the entirety here. Did you mean \~/.config/fish?]
[~/.config/conf.d doesn't exist. ~/.config/fish/conf.d is empty]

la ~/.config/fisher
```
total 24K
drwxr-xr-x  4 liam liam 4,0K Mär  4 20:42 ./
drwxr-xr-x 99 liam liam  12K Mär  5 13:16 ../
drwxr-xr-x  3 liam liam 4,0K Mär  4 20:42 github.com/
drwxr-xr-x  3 liam liam 4,0K Mär  4 20:42 local/
```
[Where github.com/jorgebucaran is empty, and local/liam is empty aswell]

[~/.config/fish/fishfile is empty]
config.fish:
```
# If fisher doesn't exist, download it
if not functions -q fisher
    set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
    curl https://git.io/fisher --create-dirs -sLo $XDG_CONFIG_HOME/fish/functions/fisher.fish
    fish -c fisher
end
```

**Comment by Scotsguy** [comment]
I'm using curl 7.64.0 and tar 1.31 (which supports -C)

I did some testing, and noticed that tar fails silently - even with --verbose set - when the directory it wants to extract into doesn't exist.

Adding the $fisher_config/github.com/jorgebucaran/fish-spark directory didn't fix it, it actually gets removed.

**Comment by jorgebucaran** [comment]
@Scotsguy Can you reproduce the problem in a container? If you give me a Dockerfile, we could fix this in hearbeat.

Fisher works (I've tested it) on busybox where `tar` is `(busybox) 1.28.4` and Linux with GNU tar (1.31).

**Comment by Scotsguy** [comment]
I can sadly not reproduce this in a container - I'm having trouble tracking down what's breaking it. I had a "proven broken" config before, but it seems something else is breaking it now.

**Comment by jorgebucaran** [comment]
@Scotsguy Do you mean you're getting a different error message now?

**Comment by Scotsguy** [comment]
No, I mean that on my machine the error stayed even after removing my config entirely while on a remote machine the config caused the issue as well, so it's not the only thing causing it

**Comment by jorgebucaran** [comment]
@Scotsguy Try running this. I typed this from memory, so beware of bugs. Looks good, though.

```fish
set -l pkg github.com/jorgebucaran/fish-spark
set -l url https://codeload.$pkg/tar.gz/master

if set -q fisher_config[1]
  echo "Downloading package to: $fisher_config/$pkg"
  command curl -Ss $url 2>&1 | command tar -xzf- -C $fisher_config/$pkg 2>/dev/null
end

la $fisher_config
la $fisher_config/$pkg
```

**Comment by Scotsguy** [comment]
This doesn't output anything at first (except print the contents of my working directory) because $fisher_config isn't set. Running fisher once fixed that.

`Downloading package to: /home/liam/.config/fisher/github.com/jorgebucaran/fish-spark`
```
total 20K
drwxr-xr-x  3 liam liam 4,0K Mär  5 16:24 ./
drwxr-xr-x 99 liam liam  12K Mär  5 16:24 ../
drwxr-xr-x  3 liam liam 4,0K Mär  5 16:24 local/
ls: cannot access '/home/liam/.config/fisher/github.com/jorgebucaran/fish-spark': No such file or directory
```

**Comment by jorgebucaran** [comment]
@Scotsguy It seems something is failing in `curl | tar`. Do you have any idea of what that could be?

Okay. Let's try to break this up in different steps:

Download the tarball.

```fish
command curl https://codeload.github.com/jorgebucaran/fish-spark/tar.gz/master > spark.tar
la
```

Extract it.

```fish
command mkdir -p $fisher_config/github.com/jorgebucaran/fish-spark
command tar -xzf- -C $fisher_config/github.com/jorgebucaran/fish-spark < ./spark.tar
```

List the work done.

```fish
la $fisher_config
la $fisher_config/github.com
la $fisher_config/github.com/jorgebucaran
la $fisher_config/github.com/jorgebucaran/fish-spark
```

**Comment by Scotsguy** [comment]
I don't know of anything that could break a pipe
`-rw-r--r--  1 liam liam 3,5K Mär  5 16:39 spark.tar`
Aha:
```
> command tar -xzf- -C $fisher_config/github.com/jorgebucaran/fish-spark < ./spark.tar

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by jorgebucaran** [comment]
@Scotsguy Sounds like a corrupt download, but that's something I've never seen. It could be `tar` has gone mad?

Try this:

```fish
file ./spark.tar
```

Also, are you able to reinstall `tar`?

**Comment by Scotsguy** [comment]
`./spark.tar: gzip compressed data, from Unix, original size 167772240`

Reinstalling tar didn't change anything.

**Comment by jorgebucaran** [comment]
@Scotsguy Thanks. 

When I run `file ./spark.tar` it says:

```
/spark.tar: gzip compressed data, from Unix, original size 20480
```

That's odd. Can you even extract the file (anywhere) using `tar`?

**Comment by Scotsguy** [comment]
A quick test with an empty file worked just fine, so something seems to be corrupted here (`file ./testfile.tar.gz: testtar.tar.gz: gzip compressed data, from Unix, original size 10240`)

**Comment by jorgebucaran** [comment]
Did you try reinstalling `curl` as well?

**Comment by Scotsguy** [comment]
Reinstalling curl has no effect.

**Comment by jorgebucaran** [comment]
Let's go back to the basics. 

```console
$ curl https://codeload.github.com/jorgebucaran/fish-spark/tar.gz/master > obj
$ sha1sum obj
392d127b3b50acb3e8399fb6a45c7274ba39300e  obj
```

Do we get the same?

**Comment by jorgebucaran** [comment]
@Scotsguy Let's go back to the basics. 

```console
$ curl https://codeload.github.com/jorgebucaran/fish-spark/tar.gz/master > obj
$ sha1sum obj
392d127b3b50acb3e8399fb6a45c7274ba39300e  obj
```

Do we get the same?

**Comment by Scotsguy** [comment]
No: `88ce76a588d0858b6b664656a1dd49b7b58b9a31  obj`

**Comment by jorgebucaran** [comment]
@Scotsguy Try downloading the file by pasting the URL on your browser, then use `sha1sum` to get the hash. Still no match?

**Comment by Scotsguy** [comment]
`392d127b3b50acb3e8399fb6a45c7274ba39300e  fish-spark-master.tar.gz`
This is fine, so it's to do with curl

**Comment by jorgebucaran** [comment]
Do you have a `~/.curlrc`?

**Comment by jorgebucaran** [comment]
@Scotsguy Also run:

```fish
env | string match "CURL*"
```

**Comment by Scotsguy** [comment]
Yes, actually - `-w "\n"`. (I didn't create it myself). And that's also what's causing it -- calling curl with -q (to ignore .curlrc) doesn't return a malformed .tar!

**Comment by jorgebucaran** [comment]
@Scotsguy Let's add `-q` then! Want to send me a PR? 🙏

**Comment by Scotsguy** [comment]
I've found a better way, I'll PR in a sec

**Comment by jorgebucaran** [comment]
@Scotsguy Upgrade to 3.2.8 to get the latest goodies! 🎉 

Thank you! 👋
