### ISSUE TITLE
Sol theme

### ISSUE THREAD

**Issue by Arelav** [jorgebucaran/fisher#533]
What happens with Sol theme since moving to v3?
I didn't change my config for a while and now I see it's no `https://github.com/fisherman` anymore and no `sol` theme as the result and also in new repo as well.

**Comment by jorgebucaran** [comment]
@Arelav I removed Sol. I'm afraid that if you can't find a fork in the wild, you're temporarily out of luck.  The following issues have the information you're looking for re the organization dissolution and more. 

- https://github.com/jorgebucaran/fisher/issues/443
- https://github.com/jorgebucaran/fisher/issues/446

Cheers! :wave:
