### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by iamvvra** [jorgebucaran/fisher#538]
I have fisher install in the below way

`
~ ─╼ fisher
created new fishfile in ~/.config/fish/fishfile

fisher: nothing to commit -- try adding some packages
`

Then tried these
`
fisher add jethrokuan/z rafaelrinaldi/pure
fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
fetching https://codeload.github.com/rafaelrinaldi/pure/tar.gz/master
fisher: cannot add github.com/jethrokuan/z -- is this a valid package?
fisher: cannot add github.com/rafaelrinaldi/pure -- is this a valid package?
done in 0.26s
`
Then these
```
$ fisher add rodrigobdz/fish-apple-touchbar
$ fetching https://codeload.github.com/rodrigobdz/fish-apple-touchbar/tar.gz/master
fisher: cannot add github.com/rodrigobdz/fish-apple-touchbar -- is this a valid package?
done in 0.26s
```

I am not sure what causes this issue? I even set
`
noproxy
`
to avoid proxy

**Comment by jorgebucaran** [comment]
@iamvvra Fish/fisher version, and OS name and version, please. Also, do you happen to have a `.curlrc` file?

**Comment by iamvvra** [comment]
I am installing it in my new Mac pro, macOS version

`
System Version: macOS 10.14.5 (18F203)`
`
Kernel Version: Darwin 18.6.0
`

Fisher version
<img width="604" alt="Screenshot 2019-06-01 at 2 37 35 PM" src="https://user-images.githubusercontent.com/8179108/58746339-e424bc00-847a-11e9-88a7-f815d388de5f.png">

I do not have the `.curlrc` file, however I do use omf proxy plugin to switch on and off the proxy to work on different networks.

<img width="715" alt="Screenshot 2019-06-01 at 2 40 23 PM" src="https://user-images.githubusercontent.com/8179108/58746384-382fa080-847b-11e9-8384-23e7d2d8cc64.png">

**Comment by jorgebucaran** [comment]
@iamvvra I don't know if that package is the problem. I would disable/uninstall it and try again to use Fisher to be sure. I don't know if your Oh My Fish installation is the problem either. I don't think so, but it wouldn't hurt to uninstall it and try again to discard the idea.

It sounds like you do, but make sure you meet Fisher [system requirements](https://github.com/jorgebucaran/fisher#system-requirements).

I'm running macOS 10.14.4, but I doubt that's the problem either. Very, very few people have issues with Fisher, so this is likely a problem with your system that I can't diagnose without more information.

**Comment by iamvvra** [comment]
Yeah, I got the git, curl and fish as expected by the fisher.

**Comment by jorgebucaran** [comment]
@iamvvra Hmm, sorry, but nothing comes to mind. If you don't have further information to share, try to repro the issue inside a Docker container, or debug Fisher's source code to see if you can find the issue. As I said, this is most likely not a problem with Fisher.

**Comment by iamvvra** [comment]
The proxy variable was the culprit. The omf proxy plugin have set different proxy variables - I removed the variables with set -e looking all of them from fish_config.

**Comment by jorgebucaran** [comment]
@iamvvra Interesting. I'm going to look at that package now to see what it does. I'm glad you figured it out. 🎉
