### ISSUE TITLE
Command: "fisher add" hangs

### ISSUE THREAD

**Issue by mtjn** [jorgebucaran/fisher#540]
Action: run command `fisher add jorgebucaran/fish-nvm`

Expected result: plugin is downloaded and installed

Result: command hangs and never finishes. When running `fisher add` for the first time, only the following line is output: `created new fishfile in ~/.config/fish/fishfile`. Otherwise and on repeated run attempts, nothing is output.

Fisher version: 3.2.9
Fish version: 3.0.2
Environment: Ubuntu 19.04

Output of `jobs` after terminating hung `fisher add`:

```
Job	Group	CPU	State	Command
7	24667	0%	stopped	fish -c "
                echo fetching $url >&2
                command mkdir -p $fisher_config/$pkg $fisher_cache/(command dirname $pkg)
                if test ! -z \"$branch\"
                     command git clone $url $fisher_config/$pkg --branch $branch --depth 1 2>/dev/null
                     or echo fisher: cannot clone \"$url\" -- is this a valid url\? >&2
                else if command curl $curl_opts -Ss -w \"\" $url 2>&1 | command tar -xzf- -C $fisher_config/$pkg 2>/dev/null
                    command rm -Rf $fisher_cache/$pkg
                    command mv -f $fisher_config/$pkg/* $fisher_cache/$pkg
                    command rm -Rf $fisher_config/$pkg
                    command cp -Rf {$fisher_cache,$fisher_config}/$pkg
                else if test -d \"$fisher_cache/$pkg\"
                    echo fisher: cannot connect to server -- looking in \"$fisher_cache/$pkg\" | command sed 's|$HOME|~|' >&2
                    command cp -Rf $fisher_cache/$pkg $fisher_config/$pkg/..
                else
                    command rm -Rf $fisher_config/$pkg
                    echo fisher: cannot add \"$pkg\" -- is this a valid package\? >&2
                end
            " >/dev/null &
```

Contents of `~/.config/fish/config.fish`

```
set -gx fish_greeting ''
set -g PATH (yarn global bin) "$HOME/.local/bin" $PATH
fish_vi_key_bindings
. ~/.fishmarks/marks.fish

set -g __fish_git_prompt_show_informative_status 1
set -g __fish_git_prompt_showstashstate 1

set -g __fish_git_prompt_char_stagedstate ">"
set -g __fish_git_prompt_char_dirtystate '*'
set -g __fish_git_prompt_char_untrackedfiles '!'
set -g __fish_git_prompt_char_conflictedstate 'x'
set -g __fish_git_prompt_char_stashstate '$'

function fish_prompt
  set_color $fish_color_cwd
  printf '%s' (prompt_pwd)
  set_color normal

  printf '%s ' (__fish_git_prompt)
```

**Comment by jorgebucaran** [comment]
@mtjn Let's try a few things. First, comment out everything in your `config.fish` and try again. I want to discard that the problem is in your `config.fish`.

Also, can you check if there's anything "wrong" with your `curl` command? Do you use a `.curlrc` file?

**Comment by Scrumplex** [comment]
> I added this line to enable running globally installed yarn packages, c.f. https://yarnpkg.com/lang/en/docs/cli/global/ (syntax is obviously changed for fish)
Just as a heads-up: Fish officially supports a variable for user defined paths, so you don't interfere with the PATH variable and created unexpected things like this. Just use `set -U fish_user_paths (yarn global bin)` and fish will save this and add it automatically to your path in every shell

**Comment by mtjn** [comment]
Thanks for the tip! I have switched to this technique, everything works fine now. But perhaps fisher could be updated to handle a path modified in this manner, or at least find out what the issue is?

**Comment by Scrumplex** [comment]
The the POSIX way of doing PATH is just not compatible of fish's way of doing variables. That's why there is `fish_user_paths` I guess.

**Comment by jorgebucaran** [comment]
> @mtjn But perhaps fisher could be updated to handle a path modified in this manner, or at least find out what the issue is?

I want to find out too. Hmm, maybe one of your global Node packages is taking precedence over a fish builtin, e.g., `contains`, `source`, `jobs`. That's all I can think of at the moment.

**Comment by Scrumplex** [comment]
> Hmm, maybe one of your global Node packages is taking precedence over a fish builtin

Are you sure? Afaik binaries in PATH can't override fish functions or shell functions in general

**Comment by jorgebucaran** [comment]
@Scrumplex Yes, you are right, functions and builtins have precedence over executables, leaving my guess out of the equation.

**Comment by mtjn** [comment]
I tested manually setting `fish_user_paths` and `PATH` for the session like this:

`set fish_user_paths "DIR1 DIR2 ...DIRn"`
`set PATH "DIR1 DIR2 ...DIRn"`

Setting `fish_user_paths` has no impact and everything works fine, as expected. Setting `PATH` resulted in this error output (have included shell prompt lines for context, as immediately after the error fish enters a `read` prompt state:

```
[I] ~/p/frontend fisher add jorgebucaran/fish-nvm
Command 'test' is available in the following places
 * /bin/test
 * /usr/bin/test
The command could not be located because '/usr/bin:/bin' is not included in the PATH environment variable.
test: command not found
/usr/share/fish/functions/isatty.fish (line 30): 
    command test -t "$fd"
            ^
in function “isatty”
	called on line 67 of file ~/.config/fish/functions/fisher.fish

in function “fisher”
	called on standard input
	with parameter list “add jorgebucaran/fish-nvm”

[I] read> 
[I] ~/p/frontend 
```

I don't really understand what's causing this, but then I tried:

`set PATH "/usr/bin:/bin"`

`fisher add PACKAGE` worked fine after this.

**Comment by jorgebucaran** [comment]
@mtjn What seems to be happening is that you're inadvertently breaking the `$PATH`. This has the potential not only to break Fisher, but other utilities as well. There's nothing Fisher can do. It's like trying to run Fisher in bash. 

:)
