### ISSUE TITLE
Install single function from a repository

### ISSUE THREAD

**Issue by caalberts** [jorgebucaran/fisher#542]
Hi there. I'd like to create a package that contains multiple functions, each as an individual file. Is it possible to install individual files from a package?

for example, given the following functions, I'd like to just install `foo` or `bar`
```
owner/package/functions/
  foo.fish
  bar.fish
```

**Comment by jorgebucaran** [comment]
@caalberts Fisher can't do this. Here's a similar issue I opened for installing Gists but then closed without implementing the feature. https://github.com/jorgebucaran/fisher/issues/505

Alternative: write a new package that allows you to grab a specific function from a repository (including gists). 👋
