### ISSUE TITLE
old fisherman prompts

### ISSUE THREAD

**Issue by rapha8l** [jorgebucaran/fisher#544]
Hi, 
Arriving a bit late, I was wondering if there was somewhere I could retrieve the prompts seen here : 
https://github.com/iampeterbanjo/fisher-prompts

Thanks !

**Comment by jorgebucaran** [comment]
Hi @rapha8l. Afraid not. But you can find forks in the wild: https://github.com/lanzafame/nitro. 👋

**Comment by rapha8l** [comment]
What a shame, but thanks for the reply and the link
