### ISSUE TITLE
--event or --on-event for event handler in README?

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/fisher#548]
Hi!

The readme says:
```fish
function $name --event $name
    bind --erase \cg
end
```

I could not find `--event` in the fish documentation. Is it supposed to say `--on-event`?

https://fishshell.com/docs/current/commands.html#function

**Comment by jorgebucaran** [comment]
@thernstig Hmm, you're definitely right, but perhaps it used to be called `--event` and latest or recent fish changed it to `--on-event`. @faho Could you confirm?

**Comment by thernstig** [comment]
@jorgebucaran One option would be to use `-e` which is the same between versions, in case this changed between fish 2.0 and fish 3.0?

**Comment by jorgebucaran** [comment]
@thernstig Gotcha, thank you for checking. Let's go with `--on-event`.

**Comment by faho** [comment]
>perhaps it used to be called --event and latest or recent fish changed it to --on-event. @faho Could you confirm?

Always been --on-event, as far back as I recall.

**Comment by jorgebucaran** [comment]
Thank you, @faho. @thernstig I stand corrected then. Good job noticing! 😄
