### ISSUE TITLE
fisher ls doesn't specify which package version

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#550]
Repro:
```
fisher add patrickf3139/open_github@debug-mode
fisher ls
```
Result:
```
patrickf3139/open_github
```
Expected
```
patrickf3139/open_github@debug-mode
```

First off, I want to thank you, Jorge, for making fisher so flexible that I can easily add specific package versions. It's been quite useful for me, especially as I develop plugins! Now, this issue I'm describing, I think it's important that `fisher ls` specify the package version because
1) it will be reassuring for the user that the right package was retrieved
2) it will make sure the fishfile truly captures the environment, which is very helpful for re-creating one's fish environment exactly from their fishfile

Thanks for reading!

**Comment by jorgebucaran** [comment]
@patrickf3139 There's no easy way to do this for remote packages, as we'd need to ask authors to include a version file (or modify the fishfile format to let you specify a version number). For locally installed packages it's pretty easy; just ask git the branch for each package.

PR welcome!
