### ISSUE TITLE
Error when opening a new shell

### ISSUE THREAD

**Issue by HerveMARTIN** [jorgebucaran/fisher#552]
On macosx, when opening a new shell, I get an error : 
```
~/.config/fish/conf.d/pisces_key_bindings.fish (line 2): switch: Expected exactly one argument, got 0

switch $fish_key_bindings
       ^
from sourcing file ~/.config/fish/conf.d/pisces_key_bindings.fish
	called on line 305 of file /usr/local/Cellar/fish/3.0.2/share/fish/config.fish

from sourcing file /usr/local/Cellar/fish/3.0.2/share/fish/config.fish
	called during startup
```
It seems to be related with picses plugin but this plugin works well when installed with omf...
See my issue on picses project : https://github.com/laughedelic/pisces/issues/21
My dotfiles for fish are here : 
https://github.com/HerveMARTIN/dotfiles/tree/master/shells/fish

**Comment by jorgebucaran** [comment]
@HerveMARTIN What is your current fish version? and were you using an old Fisher version?

**Comment by HerveMARTIN** [comment]
fish, version 3.0.2
fisher version 3.2.9

**Comment by jorgebucaran** [comment]
@HerveMARTIN Let's diiscard this could be something in your configuration first. Try commenting everything in your `config.fish` and try again.

**Comment by HerveMARTIN** [comment]
Well, uninstall/install again solved the problem...
Sorry for that.

**Comment by jorgebucaran** [comment]
@HerveMARTIN Good to know! Could be related to https://github.com/jethrokuan/fzf/pull/85 and https://github.com/jorgebucaran/fisher/issues/465.
