### ISSUE TITLE
`fisher` install appears to stomp itself? 

### ISSUE THREAD

**Issue by Gastove** [jorgebucaran/fisher#553]
So, I curl fisher: 

```
$ curl https://git.io/fisher --create-dirs -sLo $HOME/.config/fisher/functions/fisher.fish
```

For debugging, I reduce my `fish/config.fish` to:
```
set fish_home $HOME/.config/fish
set -g fisher_path $HOME/.config/fisher

set fish_function_path $fish_function_path[1] $fisher_path/functions $fish_function_path[2..-1]
set fish_complete_path $fish_complete_path[1] $fisher_path/completions $fish_complete_path[2..-1]

for file in $fisher_path/conf.d/*.fish
    builtin source $file 2> /dev/null
end

# Bootstrapping
if not functions -q fisher
    set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
    curl https://git.io/fisher --create-dirs -sLo $HOME/.config/fisher/functions/fisher.fish
    fish -c fisher
end
```
I run fisher: 
```
$ fisher
created new fishfile in ~/.config/fisher/fishfile
<W> fish: An error occurred while redirecting file “/home/rdonaldson/.config/fisher/fishfile”
open: No such file or directory
fisher: nothing to commit -- try adding some packages

$ ls -la ~/.config/fisher
total 12
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 10:47 ./
drwxr-xr-x. 50 rdonaldson rdonaldson 4096 Oct  7 10:47 ../
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 10:47 local/
```
The fishfile has not been created. Ok, weird. (This happens if I `fish -c "fisher" also.)

So let's take the suggestion and try installing something:
```
$ fisher add jethrokuan/fzf
<W> fish: An error occurred while redirecting file “/home/rdonaldson/.config/fisher/fishfile”
open: No such file or directory
created new fishfile in ~/.config/fisher/fishfile
<W> fish: An error occurred while redirecting file “/home/rdonaldson/.config/fisher/fishfile”
open: No such file or directory
fisher: nothing to commit -- try adding some packages
fetching https://codeload.github.com/jethrokuan/fzf/tar.gz/master
linking ~/.config/fisher/functions/__fzf_cd.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_cd.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_complete.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_complete.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_complete_preview.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_complete_preview.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_find_file.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_find_file.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_get_dir.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_get_dir.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_open.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_open.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_parse_commandline.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_parse_commandline.fish': No such file or directory
linking ~/.config/fisher/functions/__fzf_reverse_isearch.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzf_reverse_isearch.fish': No such file or directory
linking ~/.config/fisher/functions/__fzfcmd.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/functions/__fzfcmd.fish': No such file or directory
linking ~/.config/fisher/conf.d/fzf.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/conf.d/fzf.fish': No such file or directory
linking ~/.config/fisher/conf.d/fzf_key_bindings.fish
cp: cannot create regular file '/home/rdonaldson/.config/fisher/conf.d/fzf_key_bindings.fish': No such file or directory
<W> fish: An error occurred while redirecting file “/home/rdonaldson/.config/fisher/fishfile”
open: No such file or directory
added 1 package in 1.47s

$ ls -la ~/.config/fisher
total 32
drwxr-xr-x.  7 rdonaldson rdonaldson 4096 Oct  7 11:05 ./
drwxr-xr-x. 50 rdonaldson rdonaldson 4096 Oct  7 11:05 ../
drwxr-xr-x.  2 rdonaldson rdonaldson 4096 Oct  7 11:05 completions/
drwxr-xr-x.  2 rdonaldson rdonaldson 4096 Oct  7 11:05 conf.d/
-rw-r--r--.  1 rdonaldson rdonaldson   15 Oct  7 11:05 fishfile
drwxr-xr-x.  2 rdonaldson rdonaldson 4096 Oct  7 11:05 functions/
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 11:05 github.com/
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 11:05 local/
```
Okay, weird: so something was installed, but nothing is working.

Also fisher is defined in memory, but the file is gone? 
```
$ ls -la ~/.config/fisher/functions/
total 8
drwxr-xr-x. 2 rdonaldson rdonaldson 4096 Oct  7 11:05 ./
drwxr-xr-x. 7 rdonaldson rdonaldson 4096 Oct  7 11:05 ../
```
And the fishfile is empty:
```
$ cat ~/.config/fisher/fishfile

```
I can manually write to the fish file:
```
$ cat ~/.config/fisher/fishfile
jethrokaun/fzf
fishpkg/fish-git-util
```
But when I try to run fisher:
```
$ fisher
<W> fish: An error occurred while redirecting file “/home/rdonaldson/.config/fisher/fishfile”
open: No such file or directory
fisher: nothing to commit -- try adding some packages

$ cat ~/.config/fisher/fishfile
cat: /home/rdonaldson/.config/fisher/fishfile: No such file or directory
```
Now my fishfile is gone? As is... almost everything else:
```
$ ls -la ~/.config/fisher/
total 12
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 11:12 ./
drwxr-xr-x. 50 rdonaldson rdonaldson 4096 Oct  7 11:12 ../
drwxr-xr-x.  3 rdonaldson rdonaldson 4096 Oct  7 11:12 local/
```
So, uh. I used fisherman happily for years; I was trying to update for `fisher`, and wound up, well, here. I'm on Fedora 30, using `fish` version 3.0.2. 

Any... suggestions?

**Comment by Gastove** [comment]
If I remove _all_ my configs and let it install in my `.config/fish` dir, everything... just works. 

I am _so confused_. Clearly I've screwed something up, but.... what?

**Comment by jorgebucaran** [comment]
@Gastove Could it be that your `XDG_CONFIG_HOME` are defined incorrectly? e.g., duplicated `/`, or something else.

**Comment by Gastove** [comment]
I don't _believe_ so; it doesn't appear to be set _at all_, outside of the bootstrapping block: 
```
set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
```
That said, `~/.config` is what I'd set it to, and I can try setting it explicitly in the environment.

**Comment by Gastove** [comment]
Does not appear to have changed anything :-/ 

I know fish stores a certain amount of local state; I wonder if there's a config I haven't successfully cleared out that's throwing everything off?

**Comment by jorgebucaran** [comment]
@Gastove There must be an error in your code:

```fish
set fish_home $HOME/.config/fish
set -g fisher_path $HOME/.config/fisher

set fish_function_path $fish_function_path[1] $fisher_path/functions $fish_function_path[2..-1]
set fish_complete_path $fish_complete_path[1] $fisher_path/completions $fish_complete_path[2..-1]

for file in $fisher_path/conf.d/*.fish
    builtin source $file 2> /dev/null
end
```

First, what's exactly `$fish_home`?

**Comment by Gastove** [comment]
Ah -- that's a relic of the `fisherman` days. I was using `fish_home` to
try and separate configs that go under version control from those that
don't.

**Comment by jorgebucaran** [comment]
If you just or recently migrated from fisherman to Fisher, something might have gone wrong. Please see https://github.com/jorgebucaran/fisher/issues/450 just in case.

**Comment by Gastove** [comment]
Can do -- thanks much!

**Comment by Gastove** [comment]
@jorgebucaran Okay, I think I've got it: I'm trying to use `~/.config/fisher` as my `fisher_path`; seems logical, right? Put my `fisher` configs in `.configs/fisher`.

Except: on [line 9](https://github.com/jorgebucaran/fisher/blob/master/fisher.fish#L9) of `fisher.fish`, fisher sets `$fisher_config` to that same path... and on [line 195](https://github.com/jorgebucaran/fisher/blob/master/fisher.fish#L195), `_fisher_commit` executes `command rm -Rf $fisher_config`. 

 So.

I don't know what the right answer is, and I'm quite happy to be guided by you. Off the top of my head, I'd be happy to open a PR implementing any of:

1. A note in the [installation prefix section](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix) of the README, specifying `~/.config/fisher` is reserved.
2. Changing line 9 of `fisher.fish` to be a `set -q fisher_config; or set -g fisher_config`, along with instruction updates.
3. Stop deleting `$fisher_config`.

Or... I dunno! Your thoughts?

**Comment by jorgebucaran** [comment]
> I think I've got it: I'm trying to use `~/.config/fisher` as my `fisher_path`; seems logical, right?

Well, not really! Fisher owns `fisher_path`, so let's go with 1, please.

**Comment by Gastove** [comment]
Great. I'll get that PR up soon. How do you feel about check early on in `fisher.fish` -- something along the lines of, "if `$fisher_path is $fisher_config or inside it, exit with a helpful error message"?

**Comment by jorgebucaran** [comment]
@Gastove Let's just go with docs for now, thanks!

**Comment by jorgebucaran** [comment]
@Gastove Did you ever get around that PR? Feel free to send it whenever you find the time. I'm just doing some cleanup around here. 👋

**Comment by Gastove** [comment]
@jorgebucaran yes, I did! It was merged some time ago: 

https://github.com/jorgebucaran/fisher/pull/554

Sorry for not annotating with `closes` correctly! We're all set here :+1:
