### ISSUE TITLE
Keep packages installed with git@ url installed

### ISSUE THREAD

**Issue by DrPhil** [jorgebucaran/fisher#555]
Running
```fish
fisher add git@github.com:edc/bass.git
```
works fine for the current shell. But the package is not added to the fishfile, so the package will be uninstalled on the next run of `fisher`. What's worse, the files are not actually removed - only the line in fishfile. 

I understand that https is preferable. The upside with using git means that private repos will be accessible with your normal ssl-keys. No config required.

I'm running the latest version. Let me know if you need anything else to reproduce.
```console
❯ fisher --version
fisher version 3.2.9 /usr/share/fish/vendor_functions.d/fisher.fish
```

**Comment by jorgebucaran** [comment]
@DrPhil My first reaction from what I remember from this part of the code base is that this isn't going to be easy to implement. But maybe I'm wrong. Maybe for 4.0 when I get to re-write Fisher again (always backward compatible).

Or you can take a stab at it if you want, of course. I'm happy to help and give hints.

**Comment by jorgebucaran** [comment]
Actually, I might actually remove this in a future version of Fisher. it's too difficult to maintain and I've never actually understood the use case as I put all my stuff on GitHub or GitLab.

Going to close here since there's nothing I'm going to do about it. 👋
