### ISSUE TITLE
Install packages from tarballs

### ISSUE THREAD

**Issue by reitzig** [jorgebucaran/fisher#558]
Please add a feature so that fisher can install packages from tarballs, e.g. like so:

```
fisher add https://github.com/reitzig/my-project/releases/download/latest/my-fisher-package.tar.gz
```
(not sure if that URL would actually work)

### Rationale

It is not always natural to use a full repository for a fisher package. For instance, Docker contains shell completions in their main repo; we can not install that one with fisher.
(In that case, something like `fisher add-completion https://..../docker.fish` would be enough.)

Or, in another scenario, you generate fish completion scripts programmatically. Ideally, you'd want to source-control the script, have build automation run it, and deliver the result -- such a repo wouldn't serve very well as a fisher package, but its release assets might.

### Alternative considered

Instead of arbitrary remote tarballs, you could specifically implement installing from e.g. GitHub release assets. You could

 - define which canonical path or name it would have to have,
 -  require the user to specify the asset name together with a version ,e.g. :owner/:repo/:asset@:release, or
  - pull information about the latest version assets.

_Nota bene:_ Even in the current full-repo mode, using the latest release instead of the latest commit by default would have other advantages like e.g. checking whether an update has to happen at all, but that's probably for another discussion.

**Comment by jorgebucaran** [comment]
Docker completions should not be there, but in the official fish-shell's repo. That's what the fish authors have always asked third party vendors to do.

Do you have another usecase? I'm quite stingy about adding more features to fisher right now. And I'm looking to simplify things more in 4.0. 

Let's keep this open so I can come back to it later. 

Thanks!

**Comment by reitzig** [comment]
> Docker completions should not be there, but in the official fish-shell's repo. That's what the fish authors have always asked third party vendors to do.
 
Are you sure? In https://github.com/fish-shell/fish-shell/issues/5516#issuecomment-457804041, the opposite seems to be suggested. :thinking: 

Anyhow, smaller projects will probably not have their completions accepted into fish. If they are at least (GitHub) orgs, they could have their own repos to be compatible with fisher; for your average one-man project, I doubt most would want to have separate repos for each shell completion.

> Do you have another usecase?

Testing maybe, using a local archive?

The reverse could also be true: say I wrote a tool that generated completions for a certain class of tools (maybe they use a certain flag parser or something). What are my options?

 - Push upstream to the individual projects and have them sort it out. (They won't. Also, lots of work.)
 - Create a single fisher-compatible repo with all compiled completion files. (Users will install many completions they don't need.)
 - Push to fish main repo. (Adoption unlikely?)

Not too attractive, imho. :/ 

What I'd _really_ like in such a case is to provide a GitHub Action that creates the completions and creates a Tarball release asset. That way, project contributers have little "noise" in their repo (they might not care about fish, at all) but can still offer  completions straight from the source.

I realize that's pretty much a vision at this point, but there it is.

Another alternative (though less attractive, imho, esp. in the CI-generation case) would be to accept subfolders, e.g. `fisher add user/project/folder/with/fisher/repo`.

**Comment by jorgebucaran** [comment]
@faho Have the fish-shell's stance on where command completions should live change in recent years? See https://github.com/fish-shell/fish-shell/issues/5516.

@reitzig If you are interested in this feature, send me a PR and let's discuss it over code! 🙏

**Comment by faho** [comment]
>Have the fish-shell's stance on where command completions should live changed recently?

@jorgebucaran They have not. They've always been: If the upstream project wants to maintain them, it should. That's where the know-how about the thing is. Docker does maintain them.

Whatever you're then using to install it (e.g. your package manager) should also install the completions to vendor_completions.d (or ~/.config/fish/completions if it's a non-root install). Arch manages to do this, for instance. If that doesn't, you should file a bug with the distro.

If the upstream project isn't interested or does in practice not maintain them well, we'll take them.

>Anyhow, smaller projects will probably not have their completions accepted into fish. 

Note: We have not, to my knowledge, ever rejected a completion script we got a PR for, unless it was maintained upstream.

I can see three reasons for rejecting a completion script:

- It's maintained upstream - in which case the solution is to bring your changes upstream

- It's worse than the generated script - in which case you should improve it

- The thing the completion is for is an internal thing of yours that isn't generally available to others

**Comment by jorgebucaran** [comment]
@faho That clarifies things a lot for me, thanks!

**Comment by jorgebucaran** [comment]
> @reitzig It is not always natural to use a full repository for a fisher package. For instance, Docker contains shell completions in their main repo; we can not install that one with fisher.

I suggest creating a mirror of [docker completions](https://github.com/docker/cli/blob/master/contrib/completion/fish/docker.fish) somewhere instead, e.g., `reitzig/docker-completions`.

```
reitzig/docker-completions
└── completions/
    └── docker.fish
```
