### ISSUE TITLE
Feature Request FR | Search for packages from CLI using a fisher sub command

### ISSUE THREAD

**Issue by ipatch** [jorgebucaran/fisher#561]
Please forgive my ignorance if I failed to see the mention of _searching_ for packages from a CLI using fisher, looked over the README and did not see a way to search for _fisher_ packages using the `fisher` command from a CLI.

For my specific use case I wanted to see if there were any fisher packages related to docker, and I didn't see any _search_ sub command or _flag_ / _option_ listed when running `fisher` <kbd>tab</kbd>

All I saw was

```shell
--help
--version
add
ls
rm
self-update
```

How would one know what packages they could install if there is no function / cmd to search / query an index of packages that can be installed?

cheers 🍩

**Comment by jorgebucaran** [comment]
Hi @ipatch, you're right, there's no way to search for packages from the CLI. 

> How would one know what packages they could install if there is no function / cmd to search / query an index of packages that can be installed?

Searching GitHub for fish packages and installing them is what I recommend.

**Comment by luxlogica** [comment]
How does oh-my-fish do it? I’d guess they’re probably keeping a (manual) list of installable packages somewhere? Perhaps the same could be done for Fisher, but in a way that adding/deleting/updating package listings can be (at least semi-)automated, so it doesn’t become a maintenance burden...

**Comment by jorgebucaran** [comment]
@luxlogica We used to use an index file to implement the same search feature @ipatch asked for here (Fisher <=2). It wasn't that bad, but I found it more difficult to maintain. I prefer the loner, self-contained approach taken here.
