### ISSUE TITLE
Migrate fisher dir from XDG_CONFIG_HOME to XDG_DATA_HOME

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/fisher#568]
To show case what I mean, I am going to paste the information another tool called direnv does in a recent release:

> Migrating the allow data to the new location
>
> The allowed .envrc permissions used to be stored in the XDG_CONFIG_HOME. It's
better to keep that folder for user-editable configuration so the data is
being moved to XDG_DATA_HOME.
>
> moving /home/userA/.config/direnv/allow to /home/userA/.local/share/direnv/allow
creating a symlink back from /home/userA/.local/share/direnv/allow to /home/userA/.config/direnv/allow for back-compat.
>
> All done, have a nice day!

As such, it would make sense for fisher to also migrate from `XDG_CONFIG_HOME` to `XDG_DATA_HOME`. The config is used for user-editable config whereas the data dir should be used for data written by the program such as fisher.

One of many reasons to do this is that a lot of users utilize dotfile support to backup configuration data, and that is often done for the `XDG_CONFIG_HOME` dir.

See also https://github.com/jorgebucaran/fish-nvm/issues/108

**Comment by jorgebucaran** [comment]
@thernstig Sounds good. Do you want to work on a PR for this?

**Comment by jorgebucaran** [comment]
@thernstig Sounds good! Would you like to work on a PR for this?

**Comment by thernstig** [comment]
I am swamped right now, but if it lingers for a long while and no-one picks it up I might give it a go!

**Comment by james-r-smith** [comment]
@jorgebucaran, I can have a go at this. 😊
