### ISSUE TITLE
Bootstrap installation hangs if there's a file named 'functions' at XDG_CONFIG_HOME/fish

### ISSUE THREAD

**Issue by JasonMFry** [jorgebucaran/fisher#570]
I misunderstood something and created `XDG_CONFIG_HOME/fish/functions` as a file not a directory. Then I added the bootstrap installation code to `XDG_CONFIG_HOME/fish/config.fish`. Sourcing config.fish just hangs until I press `ctrl + c`. Better error handling or instructions would have helped. I tried to `mkdir XDG_CONFIG_HOME/fish/functions` before removing the functions file and I got this output `mkdir: functions: File exists`. Which is surprising that fish can't create a directory with the same name as a file, that doesn't seem right.

**Comment by jorgebucaran** [comment]
> @JasonMFry Better error handling or instructions would have helped.

You're more than welcome to send me a patch with better error handling or a better installation instructions! 👍  

> Which is surprising that fish can't create a directory with the same name as a file, that doesn't seem right.

Hmm, `mkdir` is not a fish shell built-in.
