### ISSUE TITLE
failed to install plugin

### ISSUE THREAD

**Issue by psychomelet** [jorgebucaran/fisher#575]
```
fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
fish: No matches for wildcard '/Users/psychoapple/.config/fisher/github.com/jethrokuan/z/*'. See `help expand`.
                    command mv -f /Users/psychoapple/.config/fisher/github.com/jethrokuan/z/* /Users/psychoapple/.cache/fisher/github.com/jethrokuan/z
                                  ^
cp: cannot stat '/Users/psychoapple/.cache/fisher/github.com/jethrokuan/z': No such file or directory
done in 0.98s
```

**Comment by jorgebucaran** [comment]
@psychomelet Do you have any more information?

**Comment by psychomelet** [comment]
confirmed it's a network issue, `wget https://codeload.github.com/jethrokuan/z/tar.gz/master` was redirected and returned 404.

close as not an fisher issue, maybe we can make the error message more friendly showing the git fetch failed.

**Comment by jorgebucaran** [comment]
Fisher doesn't use `wget`?

> close as not an fisher issue, maybe we can make the error message more friendly showing the git fetch failed.


Suggestions welcome!
