### ISSUE TITLE
Be specific about 'fish configuration file'

### ISSUE THREAD

**Issue by silenc3r** [jorgebucaran/fisher#576]
Readme suggests to configure fisher by adding code to 'fish configuration file'. It is not specified what 'fish configuration file' is precisely, so most users would assume it is `~/.config/fish/config.fish`.

In my opinion this is the wrong place, especially when you're using custom `$fisher_path`. In that case any plugin can override user defined functions and keybindings, unless they're defined in `config.fish` after fisher config code. Even if `$fisher_path` is not defined, all functions/keybindings provided by plugins that are lexicographically greather than user's take precedence.

This, in my opinion should not be the case. User's code should always override plugin's code.

I think it would be better to suggest to store fisher configuration in `~/.config/fish/conf.d/00_fisher.fish` file or similar (00 at the beginning is crucial so it is the first file sourced at shell start). With that and custom `$fisher_path` we could have predictable startup order - plugins are always sourced before user code. That way user can override functions/keybindings provided by plugins easily.

It may be a good idea to set `$fisher_path` by default as well (`~/.config/fish/plugins` or something).

**Comment by jorgebucaran** [comment]
@silenc3r Fisher's only available configuration is changing the installation prefix `$fisher_path`, what other configuration are you referring to?
