### ISSUE TITLE
Add hook for an install.fish that is run only once when the plugin is installed

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#577]
As a fisher plugin developer, I'd like to have functionality for executing a script only once when the plugin is first installed, similar to how uninstall.fish is executed when the plugin is uninstalled. Yes, I could totally achieve the same functionality with a script in `conf.d` plus an if statement to check if it's already been run. But I find that inefficient and confusing. What do you think about adding support to execute a `install.fish` or similar on plugin install? Thanks Jorge for creating and maintaining Fisher! I truly enjoy using it a lot more than OMF!

**Comment by jorgebucaran** [comment]
I think there's a PR to add just that. I don't want to complicate the package API, but I guess this makes sense. You can leave your review there. Thanks. #573

**Comment by patrickf3139** [comment]
Hi, sorry for reopening this. Reopening because #573 was closed.
I just want to add support for doing this because as a fish package author, I want to be able to notify my users of backwards incompatible changes when they upgrade to new versions. Right now, I don't have a non-hacky way of doing this without spamming the user about the backwards incompatible changes.

**Comment by jorgebucaran** [comment]
@patrickf3139 I'm planning on adding this in Fisher 4. Please share your feedback and comments in #582. 👋
