### ISSUE TITLE
self-update: Add ability to fail unless we get a HTTP OK response from GitHub?

### ISSUE THREAD

**Issue by guihkx** [jorgebucaran/fisher#578]
Funny thing, I tried to update fisher some minutes ago, while GitHub was going through a [power outage](https://twitter.com/githubstatus/status/1282575172223016960).

After I ran `fisher self-update`, my `fisher.fish` script ended up being overwritten by this:

```
$ cat ~/.config/fish/functions/fisher.fish
500: Internal Server Error
```

I've already fixed it, but it would be nice to prevent this in the future... 😄

**Comment by jorgebucaran** [comment]
@guihkx How?

**Comment by guihkx** [comment]
I'm on my phone right know so I can't test this properly, but I believe curl's `--fail` option should prevent it. If you can test it:

```
$ curl --fail httpstat.us/500
```

IIRC, curl will return a non-zero code unless you gey 200 OK as a response. Better check the manual first just to be sure :)

**Comment by jorgebucaran** [comment]
@guihkx Thanks, will look into it soon. 👋

**Comment by guihkx** [comment]
Hi again!

I've implemented this feature on my local repo, so I wanted to ask you if you're also working on it, so that I don't step on your toes. 👍 

Otherwise, I could just open a PR for you to review. So, let me know!

Thanks.

**Comment by jorgebucaran** [comment]
@guihkx No problem, send me a PR! 🎉
