### ISSUE TITLE
Dont recursively move contents in plugin

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#581]
Consider the following `~/.config/fish` structure:

```
fish
└── functions
   ├── dir
   │  └── bar.fish
   └── foo.fish
```

Fish doesn't autoload from directories within `functions`, so `foo` is a recognized command, but `bar` is not.

If we have a package with the same structure however:

```
package
└── functions
   ├── dir
   │  └── bar.fish
   └── foo.fish
```

Upon adding the package, fisher will place `bar.fish` directly in the functions folder, without the dir folder:

```
fish
└── functions
   ├── bar.fish
   └── foo.fish
```

This seems odd as if the package creator placed a directory in `functions`, they would have expected it's contents not to be autoloaded by the shell.

Fisher overrides this expectation and places `bar.fish` in the wrong place. I propose that fisher should not recursively add contents in directories but instead place the directories as expected.

**Comment by jorgebucaran** [comment]
I don't disagree, but I did this in order to support existing packages that place `*.fish` files inside arbitrary directories under `functions`. This may have been one of those things I did to offer compatibility with Oh My Fish. I'd be happy to simplify things by removing this "feature", but what's the reward?

**Comment by IlanCosman** [comment]
Well the reward for _me_ is adding fisher support to Tide. I can simply move the `tide_theme` folder into functions and call it a day.

The reward for _you_ I'm not really sure about. I suppose getting back at all those weirdos who did that in the first place 😂 For real though which packages place functions that they want to be autoloaded in subdirectories of functions? That just doesn't make any sense. Can you point out any packages that do this so I can go file an issue or pull request?

It's totally up to you but it may be best to encourage package developers to use good practices, and sometimes that involves twisting the arm a little bit. I'm not sure. It's a tough call. I know it would benefit me though 😃 , hopefully not at the expense of others.

**Comment by jorgebucaran** [comment]
@IlanCosman What about packages with one or more `*.fish` files in the root directory?

```console
foobar
  └── foobar.fish
  └── README.md
  └── LICENSE.md
```

Fisher adds them to `functions` right now. I don't think this interferes with this issue, but I wanted to bring it up to make sure. I use this feature for all my packages that are just a single file.

**Comment by IlanCosman** [comment]
Shouldn't interfere with this issue no.

**Comment by jorgebucaran** [comment]
Implemented in [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0). :tada:
