### ISSUE TITLE
main branch compatibility with packages

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#583]
With github transitioning to using `main` as the default `default branch`, Fisher should default to `main` first and then `master` if that is not available.

**Comment by jorgebucaran** [comment]
Done. It would be nice to come up with a different idea for the package in the https://github.com/jorgebucaran/fisher#creating-your-own-package mini tutorial. That didn't age well!

**Comment by IlanCosman** [comment]
Oh @jorgebucaran I believe you misinterpreted me. I don't care whether fisher uses master or main, but that when installing a package it will accept both. Right now it default to master, but it should also accept main.

**Comment by jorgebucaran** [comment]
I was planning on doing that someday anyway. But you are absolutely right, support for this soon should land soon, before Fisher 4.

**Comment by neersighted** [comment]
I would also like to note that install and self-update are broken right now because of the branch name change...

**Comment by IlanCosman** [comment]
Yah fisher cant be installed right now that should probably be hotfixed.

**Comment by jorgebucaran** [comment]
Hotfix landing soon. As for the branch issue, people can always install from a different branch or tag using:

```console
fisher add username/repo@branch_or_tag
```

The easiest way to handle this would be to install from `main` by default without a fallback to `master` as users that want to install from master can just:

```console
fisher add username/repo@master
```

**Comment by jorgebucaran** [comment]
Please upgrade to [3.3.0](https://github.com/jorgebucaran/fisher/releases/tag/3.3.0) and help me identify any bugs. 💯
