### ISSUE TITLE
Fisher self-update fails after fisher switched to main branch

### ISSUE THREAD

**Issue by DivineGod** [jorgebucaran/fisher#584]
I noticed `fisher self-update` failed with the following:

```fish
ᚦ fisher self-update                                                             
fetching https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish
fisher: cannot update fisher -- are you offline?
```

Changing `master` to `main` in `~/.config/fish/functions/fisher.fish` resolved the issue.

**Comment by meetaco** [comment]
https://git.io/fisher redirection have to be fixed as well.

**Comment by jorgebucaran** [comment]
@DivineGod @meetaco Working on it with GitHub as we speak! Thank you all for reporting. 🙏

**Comment by maparent** [comment]
for the record: your fix allows the next self-update to work, but updating to the version with the fix still needs a hand-edit as proposed by @DivineGod . I suggest leaving the issue open until most users have been over that hump.

**Comment by ovv** [comment]
Keeping a master branch pointing to https://github.com/jorgebucaran/fisher/commit/c20d1b3ec3b020c1c8846286fb12fd772b8f390f for a bit would allow for seamless self-updates

You can then remove the branch if a few days/weeks/months

**Comment by jorgebucaran** [comment]
@ovv @maparent @DivineGod Whoops, good point! I restored `master` and it has the latest changes now. It's just a matter of time now. 👍

**Comment by DivineGod** [comment]
Awesome, thanks for the quick response :)

**Comment by anisse** [comment]
Hey, I just hit this; was the old master deleted again ?

**Comment by anisse** [comment]
Not only was it deleted, the script was moved to functions/ sub-directory. Changing both the branch and path allowed updating. Then I had to delete all installed plugins and reinstall them again.

**Comment by jorgebucaran** [comment]
I originally deleted the `master` branch after switching to `main`, which was a careless mistake. Then restored it to allow for seamless self-updates from older Fisher versions. 

It's been a while since I published [4.x](https://github.com/jorgebucaran/fisher/releases), and I needed to proceed with #651, which required moving the top-level `fisher.fish` file into a `functions` directory, thus invalidating the deprecated `self-update` command. 

Fortunately, Fisher 3.x fails to upgrade if it can't download `fisher.fish`. That means we no longer have to maintain a tricky built-in migration script. It's true you can't self-update from `3.x` anymore, though, so I created a step-by-step guide to help you all migrate to 4.x (#652). ✨💖

**Comment by anisse** [comment]
@jorgebucaran Thanks, I wish I had read that before complaining here. Would you be open to linking to this tutorial from the README.md ? Maybe something like this at the end of the README:

[How do I upgrade to fisher 4.x from fisher 3.x ?](https://github.com/jorgebucaran/fisher/issues/652)

**Comment by jorgebucaran** [comment]
What about a prominent notice right at the top of the README? 

I like the last (shortest one), what do you think?

> ☝️ Psst! Migrating from v3.x? Check the [migration guide](https://github.com/jorgebucaran/fisher/issues/652) and may the Fish be with you!
> ☝️ Upgrading to Fisher 4.x from 3.x or 2.x? Check out the [migration guide](https://github.com/jorgebucaran/fisher/issues/652).
> ☝️ [How do I upgrade to Fisher 4.x from Fisher 3.x or 2.x?](https://github.com/jorgebucaran/fisher/issues/652)
> ☝️ [How do I upgrade to Fisher 4.x?](https://github.com/jorgebucaran/fisher/issues/652)
> ☝️ [Upgrading to Fisher 4.x?](https://github.com/jorgebucaran/fisher/issues/652)

**Comment by anisse** [comment]
I prefer the third one, but honestly, anything works as long as it has a pointer with word "upgrade" or "update", which is what I was looking for. Thanks a lot for fisher.

**Comment by jorgebucaran** [comment]
Done, thank you for requesting this.
