### ISSUE TITLE
Consider fetching HEAD instead of main/master

### ISSUE THREAD

**Issue by lilyball** [jorgebucaran/fisher#585]
The release notes for [v3.3.0](https://github.com/jorgebucaran/fisher/releases/tag/3.3.0) says that fisher now defaults to `/main` before `/master` if the tag/branch isn't specified.

This seems weird to me. It should just default to whatever `HEAD` is, because the remote `HEAD` declares the default branch. Not only would this more closely match the behavior of other tools that use git, but it also avoids enshrining any particular branch name at all.

**Comment by jorgebucaran** [comment]
I'm not sure we can do that without git.

**Comment by igalic** [comment]
this should, nonetheless, be possible

**Comment by jorgebucaran** [comment]
@igalic Do you happen to know how?

**Comment by igalic** [comment]
example https://github.com/launchbadge/sqlx/archive/HEAD.zip

**Comment by jorgebucaran** [comment]
Thanks @igalic @lilyball, that seems to work TIL! 🎉

**Comment by igalic** [comment]
gitlab example: https://gitlab.com/spritely/goblins/-/archive/HEAD/goblins-master.tar.bz2
gitea example: https://codeberg.org/meena/dotfiles/archive/HEAD.tar.gz

all working.

this should also work on bitbucket… git repos… for hg it's different, for example:

the default branch on hg is called … `default`, and hg's `HEAD` is called `tip`:
so these two:
https://bitbucket.org/runhello/evo/get/default.tar.gz
https://bitbucket.org/runhello/evo/get/tip.tar.gz
should get the same

anyway… why didn't we do this kind of thing like 10 years ago? :O
