### ISSUE TITLE
Terminology inconsistency with package and plugin

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#587]
Hi Jorge, I noticed that you recently changed the readme from calling what is being managed from "package" to "plugin". How come you thought plugin would be better? Not sure but I like plugin better anyway.

Anyway, I think you might've forgotten to change it for fisher.fish and so the help docstring is inconsistent with the readme now. Want me to help you rename?

**Comment by jorgebucaran** [comment]
@patrickf3139 That's right, after advocating for package for a long time, I finally gave in to plugin.

> I think you might've forgotten to change it for fisher.fish and so the help docstring is inconsistent with the readme now. Want me to help you rename?

Absolutely, please do!
