### ISSUE TITLE
Fisher creates completions/fisher.fish.fish

### ISSUE THREAD

**Issue by pikeas** [jorgebucaran/fisher#589]
Contents are `fisher complete`, identical to fisher.fish. If I delete both files and re-run `fisher`, both files are recreated.

**Comment by jorgebucaran** [comment]
@pikeas Fisher will create completions under `completions/fisher.fish` if there are no completions yet as you are aware.

```fish
if test ! -e $fisher_path/completions/fisher.fish
  echo "fisher complete" >$fisher_path/completions/fisher.fish
  _fisher_complete
end
```

I have no idea how it could create a `fisher.fish.fish` file from looking at that code, but I wasn't able to repro either. If you're still have this issue, try adding some `echo $fisher_path` around that code to see if you discover something. This is most likely a problem with your fish configuration and not with fisher.

**Comment by jorgebucaran** [comment]
Fisher will create completions under `completions/fisher.fish` if there are no completions yet as you are already aware.

```fish
if test ! -e $fisher_path/completions/fisher.fish
  echo "fisher complete" >$fisher_path/completions/fisher.fish
  _fisher_complete
end
```

I have no idea how it could create a `fisher.fish.fish` file from looking at that code, but I wasn't able to repro either. If you're still have this issue, try adding some `echo $fisher_path` around that code to see if you discover something. This is most likely a problem with your fish configuration and not with fisher.

**Comment by jorgebucaran** [comment]
@pikeas Fisher [will create completions](https://github.com/jorgebucaran/fisher/blob/c2c091f33ea83cbcb67ac2d8d912c2cfddd5e4a6/fisher.fish#L21-L24) under `completions/fisher.fish` automatically. 

```fish
if test ! -e $fisher_path/completions/fisher.fish
  echo "fisher complete" >$fisher_path/completions/fisher.fish
  _fisher_complete
end
```

I have no idea how that could create a `fisher.fish.fish` file from looking at the code, but I wasn't able to repro either. If you're still having this issue, try adding some `echo $fisher_path` around that code to see if you can discover something. This is most likely a problem with your fish configuration and not with fisher.
