### ISSUE TITLE
Emit plugin name uninstall event, not for every single file

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#590]
Currently fisher emits an event for every file that it removes called `<nameOfFile>_uninstall`. This seems silly to me as an uninstall is always total. Any one of these events would serve the purpose of a whole plugin uninstall event, so an event should simply be emited called `<plugin>_uninstall`.

**Comment by jorgebucaran** [comment]
@IlanCosman Makes sense, but could be considered also an implementation detail. Don't need it, don't use it.

**Comment by IlanCosman** [comment]
Upon further consideration I realize that emitting `<plugin name>_uninstall ` won't work. One can install from a directory that isn't named the same as the github repo/overall plugin.

**Comment by jorgebucaran** [comment]
@IlanCosman As you probably already noticed, we should consider this a feature, not an implementation detail, since we want to allow plugin authors to name their files (which content events) freely.
