### ISSUE TITLE
Add fisher set command for universal variables

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#591]
When fisher adds an `install` event, package authors should transition to setting universal variables on install as opposed to global variables on every shell start--it's the encouraged way of doing things in fish. I'd imagine that many people will use the following pattern:

```fish
# Install script
set -U _plugin_variables
function _plugin_set -a name
    set -a _plugin_variables $name
    set -U $name $argv[2..-1]
end

_plugin_set foo bar
_plugin_set qux quz
_plugin_set ham eggs
```

```fish
function _plugin_uninstall --on-event _plugin_uninstall
    for var in $_plugin_variables
        set -e $var
    end
    set -e _plugin_variables
end
```

This allows one to set and forget variables, as opposed to remembering to add each one to the uninstall function.

I propose that fisher provide this service with some sort of `fisher set` command.

Here's a rough outline of what it might look like:

```fish
# Install script
fisher set plugin foo bar
fisher set plugin qux quz
fisher set plugin ham eggs
```

fisher would have a variable entitled `_fisher_plugin_variables` with all the names of the set variables for the plugin. Then, on `uninstall`, fisher would erase these variables.

`fisher set plugin` is a bit unwieldy, but I'm sure it can be slimmed down.

**Comment by jorgebucaran** [comment]
Hhmm, but it's extremely unlikely that I will add a new command to Fisher. But we can discuss the upcoming install event implementation in detail if you want. Maybe that belongs to a different issue, though? Pinging @joseluisq, as he might want to add his thoughts there as well.

**Comment by joseluisq** [comment]
No so much to say from my side.
Just to mention that as far as I know current Fisher doesn't provide a proper install event (#573) similar to the uninstall one, so I don't know how Fisher should manage assigned variables at runtime on the uninstall event.
Since @jorgebucaran is working on a next Fisher major, this improvement issue could be related to #582.
I hope I have not misunderstood @IlanCosman's concern.

**Comment by IlanCosman** [comment]
It seems there isn't much interest in implementing this, and I think it is perhaps too prescriptive and niche.

**Comment by jorgebucaran** [comment]
@IlanCosman I was just revisiting this.

> When fisher adds an install event, package authors should transition to setting universal variables on install as opposed to global variables on every shell start--it's the encouraged way of doing things in fish.

You have a point, but we don't want to encourage plugin authors to do anything other than the bare minimum, e.g., put their `fish` function files under `functions`, use `conf.d` for snippets, key bindings—that sort of thing.

We should also strive to minimize framework lock-in.
