### ISSUE TITLE
`jorgebucaran/bax.fish` no longer installs because of `main` instead of `master`

### ISSUE THREAD

**Issue by halostatue** [jorgebucaran/fisher#592]
```
% curl https://codeload.github.com/jorgebucaran/bax.fish/zip/master
404: Not Found
```

However, `% curl https://codeload.github.com/jorgebucaran/bax.fish/zip/main` works, which means that `fisher add jorgebucaran/bax.fish@main` works for now, but that seems an awful workaround.

**Comment by jorgebucaran** [comment]
@halostatue Are you using the latest fisher?

**Comment by halostatue** [comment]
I was not. I removed `@main` from my `fishfile` and reran the import and it worked. Thanks.
