### ISSUE TITLE
More consistent subcommand names/terminology

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#593]
We talk about installing and removing plugins, but use `add` and `rm`. `ls` to _list_, and usually just run `fisher` to update (not exactly #527). This can be confusing. Starting in 4.0, I invoke [fish's law of discoverability](https://fishshell.com/docs/2.7/design.html#disc) and plan to deprecate ~~`add`~~, ~~`ls`~~, and ~~`rm`~~, in favor of `install`, `update`, `list`, and `remove`.

- `fisher add` → **`fisher install`**
- `fisher` → **`fisher update`**
- `fisher rm` → **`fisher remove`**
- `fisher ls` → **`fisher list`**

Thank fish for autocompletion, it's not like we have to type all that every time, e.g., `fisher i` + <kbd>Tab</kbd> will autocomplete `install` for you and so on.

**Comment by jorgebucaran** [comment]
Implemented in [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0). :tada:

**Comment by nirvdrum** [comment]
Are the old commands still supposed to work? The [4.0 release notes](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0) say `fish add` was deprecated, but using it errors out with "fisher: unknown flag or command: "add" (see `fisher -h`)".

**Comment by jorgebucaran** [comment]
@nirvdrum I suppose you are using the latest Fisher? `add` and `rm` were deprecated in 4.0, and no longer work on 4.1. 😉

**Comment by nirvdrum** [comment]
Okay. I thought maybe it was a bug because there's no mention in the 4.1 release notes about them being removed. Deprecating in a major version and then removing in the very next minor version (released only five days later) caught me off-guard. I'll update my Ansible config to lock down the fisher version better.

**Comment by jorgebucaran** [comment]
> @nirvdrum there's no mention in the 4.1 release notes about them being removed 

Good point. [Just added](https://github.com/jorgebucaran/fisher/releases/tag/4.1.0) a note. 👍
