### ISSUE TITLE
fisher 4.0 fails bootstrap if the directories aren't already there

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#598]
Steps to reproduce: 

1. `rm -rf ~/.config/fish`
2. exit and restart shell
3. `curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher`
3. `fisher` - works fine because it has been sourced by the previous step
4. exit and restart shell
5. `fisher` - does not work because fisher was never saved in `$__fish_config_dir`

**Comment by jorgebucaran** [comment]
Thank you, @IlanCosman.

Someday after enough people have upgraded to 4.0 I'll simply move `fisher.fish` to `functions/fisher.fish`.
