### ISSUE TITLE
fisher 4.0 should update plugins on install if they are already installed

### ISSUE THREAD

**Issue by IlanCosman** [jorgebucaran/fisher#599]
Install should recognize that a plugin is already installed and just update it, instead of telling the user to use the update command. This
1. is more user friendly
2. prevents this annoying issue: `fisher: "jorgebucaran/fisher" is already installed (try fisher update jorgebucaran/fisher)` when I've deleted my `$__fish_config_dir` but not `$fisher_data` and then try to bootstrap again.

**Comment by jorgebucaran** [comment]
@IlanCosman I'd be cool with this, but I'd like to hear what more people think. It's less code, that's for sure! 👍

Now, why would anyone run `fisher install ...` when they mean to update? We don't `complete` the install command, so you'd have to go out of your way to type it all.

**Comment by IlanCosman** [comment]
Scripts is why. I suppose you could make people use `fisher update plugin || fisher install plugin`, but that's a bit annoying.

**Comment by jorgebucaran** [comment]
Likewise, should we default to install when the user attempts to update a plugin that is _not_ currently installed? I can see how updating plugins already installed would make sense, but I'd find the other a bit surprising.

**Comment by IlanCosman** [comment]
No I don't think so. Install meaning update on already-installed things is pretty standard I believe. `pacman`, `apt`, and `brew` behave this way to my knowledge. Update meaning install on things not-already-installed is not used afaik.
