### ISSUE TITLE
multiple OMF plugins are getting overwritten

### ISSUE THREAD

**Issue by develop7** [jorgebucaran/fisher#605]
Repro:

Install multiple OMF plugins containing files named identically, e.g. `oh-my-fish/plugin-direnv` and `oh-my-fish/plugin-rustup`

Expected: plugin files are not getting overwritten

Instead: subj, see output below

```
develop7@t-rex ~>  fisher install oh-my-fish/plugin-direnv oh-my-fish/plugin-rustup
fetching https://codeload.github.com/oh-my-fish/plugin-direnv/tar.gz/HEAD
fetching https://codeload.github.com/oh-my-fish/plugin-rustup/tar.gz/HEAD
installing oh-my-fish/plugin-direnv
+/home/develop7/.config/fish/functions/init.fish
installing oh-my-fish/plugin-rustup
+/home/develop7/.config/fish/functions/init.fish
2 updated plugin/s
```

Fisher version: 4.1.0 (previously 4.0.0)

**Comment by jorgebucaran** [comment]
@develop7 I've decided to stop supporting `init` and `uninstall` files (finally). OMF should've migrated to `conf.d` snippets already, but the project has been effectively dead for years. 

If you rely on those plugins, I suggest forking, and fixing them. I can lend you a hand if you don't know how to migrate them.

**Comment by jorgebucaran** [comment]
@develop7 Take [plugin-rustup](https://github.com/oh-my-fish/plugin-rustup) for example, all we need is to rename `init.fish` into `conf.d/rustup_init.fish` (or whatever you want, the name is not important, but that one is descriptive) and rewrite the code like so:


```fish
set -g rustup_path ~/.cargo/bin
set -q CARGO_HOME && set rustup_path $CARGO_HOME/bin
contains -- $rustup_path $PATH || set -gx PATH $rustup_path $PATH
```

That should do it for that plugin.
