### ISSUE TITLE
Plugins not stored?

### ISSUE THREAD

**Issue by robdecker** [jorgebucaran/fisher#606]
Using `4.1.0`.

It looks like plugins are no longer being stored at `~/.local/share/fisher/name_of_plugin`. This is problematic in the cases where that plugin references some file other than a `function.fish`. 

For example, [b4b4r07/enhancd](https://github.com/b4b4r07/enhancd) references several files in its `lib` directory. This plugin looks for files at `~/.local/share/fisher/b4b4r07/enhancd/lib` and throws errors since the plugin is not physically stored.

I don't know if this is intentional or not, but it has made the above plugin completely unusable.

**Comment by gazorby** [comment]
@jorgebucaran found something weird while working on b4b4r07/enhancd#139:

Things work properly when setting `fisher_path` to `~/.config/fish`, but when using another location, files in `$fisher_path/conf.d` won't be sourced during shell startup, and some plugins won't be initialized correctly.

Of course I could manually source them in `~/.config/fish/config.fish`, but I'm not sure about side effects

Is this intended or did I miss something?

**Comment by jorgebucaran** [comment]
@gazorby If you set `fisher_path`, you must also put it in your fish function path and manually source `conf.d` snippets. I don't recommend using `fisher_path`, it exists for backward compatibility.

**Comment by jorgebucaran** [comment]
@gazorby If you set `fisher_path`, you must also put it in your fish function path and manually source `conf.d` snippets. I left you a comment in your PR. Let's continue there.
