### ISSUE TITLE
`fisher list` prints nothing, exits with code 1 until I run `fisher update`

### ISSUE THREAD

**Issue by lilyball** [jorgebucaran/fisher#607]
I just updated from fisher 4.0.0 to 4.1.0 using `fisher update jorgebucaran/fisher`. After this, `fisher list` printed nothing and exited with code 1, and `fisher update jorgebucaran/fisher` a second time printed an error.

I tried downgrading back to fisher 4.0.0 and then ran just a bare `fisher update`. Same issue.

After poking around the source for a bit, I finally just ran `fisher update` by itself with 4.1.0 already installed, and at this point `fisher list` started working.

I finally figured out, `fisher list` is using a universal variable, which is only set when installing/updating/removing plugins, but it's also only set if fisher was already version 4.1.0. Updating from 4.0.0 to 4.1.0 leaves this variable unset, and therefore `fisher list` is broken.

Also worth mentioning, the fact that it just shows a universal variable means if I modify my `fish_plugins` file, `fisher list` won't show the modification, and therefore won't tell me what's going to happen if I run `fisher update`. This is particularly an issue if I sync the `fish_plugins` file between machines.

I think fisher needs to make two changes:

1. When upgrading from a version older than 4.1.0, fisher needs to arrange to get the `_fish_plugins` variable set. Probably the best way to do this is to check if the variable is present upon fisher initialization, and if not, figure out some sane default (which could be to simply assume `fish_plugins` reflects the current state). Right now fisher 4.1.0 actually erases this variable if it would otherwise be empty, so it would have to stop doing that.
2. The output of `fisher list` should actually combine both the `fish_plugins` file and the `$_fisher_plugins` variable such that it tells me both what I have installed right now and what I will have installed if I run `fisher update`. I'd expect something like merge the two lists into one (uniquing the values), and show me that list with annotations to indicate what will be installed/removed on `fisher update`.

**Comment by lilyball** [comment]
(side note: fisher's use of the universal variable might be what finally prompts me to sync my universal variables across machines, since I already sync the rest of the fish config. My sync setup dates back to when fish had per-host universal variable files and kept other various cache files in the config dir, and I've never actually evaluated the universal variables to see if they should be synced or not)

**Comment by jorgebucaran** [comment]
> @lilyball When upgrading from a version older than 4.1.0, fisher needs to arrange to get the _fish_plugins variable set. Probably the best way to do this is to check if the variable is present upon fisher initialization

You're right, we should do that. I'll work on something.

> @lilyball The output of fisher list should actually combine both the fish_plugins file and the $_fisher_plugins variable such that it tells me both what I have installed right now and what I will have installed if I run fisher update.

That's a really interesting idea, but unrelated to this issue. If you would like things to work this way instead, please create a new issue and let's discuss it.

> @lilyball Also worth mentioning, the fact that it just shows a universal variable **means** if I modify my fish_plugins file, fisher list won't show the modification, and therefore won't tell me what's going to happen if I run fisher update.

FYI, the behavior of `fisher list` is the same between `3.x` and all `4.x`. Perhaps you were using a really old Fisher that did it differently, but I can't honestly remember Fisher ever working that way.
