### ISSUE TITLE
Cannot run `fisher update` within a script

### ISSUE THREAD

**Issue by jaminthorns** [jorgebucaran/fisher#608]
I want to run `fisher update` from within a bash script, so I do this:

```fish
fish -c "fisher update"
```

This breaks when used with [my `fish_plugins` file](https://github.com/jaminthorns/environment/blob/master/config/fish/fish_plugins) because job control is not enabled for non-interactive scripts, as detailed in this issue: https://github.com/fish-shell/fish-shell/issues/5036

Which is being used in `fisher` here: https://github.com/jorgebucaran/fisher/blob/main/fisher.fish#L106

Like that issue suggests, you can use `(jobs -lp)` as an alternative for `$last_pid`. If I modify `fisher.fish` locally to use `(jobs -lp)`, running `fish -c "fisher update"` works. I can make a PR for the change, but my understanding of `fish` is limited, and I want to be sure this is the correct fix.

**Comment by jorgebucaran** [comment]
Hey @faho, should we avoid `$last_pid` and use `jobs -lp` instead?
