### ISSUE TITLE
Recursively install plugins

### ISSUE THREAD

**Issue by Marsup** [jorgebucaran/fisher#609]
Hello !

I have a small problem upgrading to fisher 4.x but I may be in a niche use case.

Prior to 4.x I used to have a sort of meta plugin that regrouped all my functions and configuration, and also a fishfile that would include all the plugins I typically use, so that on any new environment I would only have to install fisher and my plugin and all would be set up perfectly. 3.x used to apparently recursively install those plugins, but now it doesn't, I've tried renaming it to fish_plugins but it doesn't seem to work.

What would be the right way to go about this pattern with the 4.x version ?

Thanks :slightly_smiling_face:

**Comment by jorgebucaran** [comment]
The way to share your configuration across different systems is to put down the plugins you want in a `fish_plugins` file and save it to your dotfiles repo. Then clone it in every new environment, and run `fisher update` to sync.  

Or put everything in a script and run it on every new system:

```fish
if not functions -q fisher
  curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher foo/bar fuga/hoge piyo/poyo
end
```

Unlike, say, Node.js, where you can have different dependencies on a per-project basis, in fish all your dependencies are global dependencies. Now, you could supply a `conf.d` snippet with your "meta" plugin that uses the [new event system](https://github.com/jorgebucaran/fisher#event-system), and install the plugins you want:

```fish
# Defined in path/to/meta/conf.d/meta.fish

function meta_install --on-event meta_install
  fisher install piyo/poyo
end
```

but I'd find it less surprising to tell the user to do it themself. So, if your plugin requires `piyo/poyo`, just tell the user to install `piyo/poyo` too, preferably in your README#installation's section.

**Comment by Marsup** [comment]
Thanks for the very detailed answer !

I went with the event system as it would work better for me, but got a few troubles with the install.

Here is a log of what happened:
<details>

```
fetching https://codeload.github.com/james2doyle/omf-plugin-fnm/tar.gz/HEAD
fetching https://codeload.github.com/nickeb96/puffer-fish/tar.gz/HEAD
fetching https://codeload.github.com/jethrokuan/z/tar.gz/HEAD
fetching https://codeload.github.com/danhper/fish-ssh-agent/tar.gz/HEAD
~/.config/fish/functions/fisher.fish (line 1): No matches for wildcard “$source/{functions,conf.d,completions}/*”. See `help expand`.
string replace $source $fisher_path $source/{functions,conf.d,completions}/*
                                    ^
in command substitution
        called on line 144 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install jethrokuan/z danhper/fish-ssh-agent nickeb96/puffer-fish james2doyle/omf-plugin-fnm'
        called on line 11 of file ~/.config/fish/conf.d/plugins.fish
in function 'plugins_install'
        called on line 1 of file ~/.config/fish/functions/fisher.fish
in event handler: handler for generic event “plugins_install”
        called on line 155 of file ~/.config/fish/functions/fisher.fish
~/.config/fish/functions/fisher.fish: Unknown error while evaluating command substitution
in function 'fisher' with arguments 'install jethrokuan/z danhper/fish-ssh-agent nickeb96/puffer-fish james2doyle/omf-plugin-fnm'
        called on line 11 of file ~/.config/fish/conf.d/plugins.fish
in function 'plugins_install'
        called on line 1 of file ~/.config/fish/functions/fisher.fish
in event handler: handler for generic event “plugins_install”
        called on line 155 of file ~/.config/fish/functions/fisher.fish
installing jethrokuan/z
installing danhper/fish-ssh-agent
+~/.config/fish/functions/__ssh_agent_is_started.fish
+~/.config/fish/functions/__ssh_agent_start.fish
+~/.config/fish/functions/init.fish
installing nickeb96/puffer-fish
+~/.config/fish/functions/_puffer_fish_expand_bang.fish
+~/.config/fish/functions/_puffer_fish_expand_dots.fish
+~/.config/fish/conf.d/puffer_fish_key_bindings.fish
installing james2doyle/omf-plugin-fnm
+~/.config/fish/completions/fnm.fish
4 installed plugin/s
cp: target '/tmp/tmp.S18WLg8k4L' is not a directory
1 installed plugin/s
```

</details>

The weird thing is that the very same thing works if I do it in a shell, or if I do it one by one in the event function, but if I try to install them all in one call I consistently get this. Could it be an install-inside-install specific problem ?

The remove operation using the same arguments works fine.

**Comment by jorgebucaran** [comment]
@Marsup Are you trying to install a plugin that has no functions, `conf.d` snippets or completions? What plugins are you trying to install? Also, make sure you are running the latest Fisher.

**Comment by jorgebucaran** [comment]
@Marsup Hmm, are you trying to install an empty plugin (one without functions, `conf.d` snippets,  and completions)? What plugins are you trying to install? Can I see how you implemented your "meta" plugin? The error could be there.

Also make sure that you're running the latest Fish and Fisher.

**Comment by Marsup** [comment]
Sure thing, the meta plugin is here: https://github.com/Marsup/dotfiles/blob/master/.fish/conf.d/plugins.fish
I'm not very comfortable with fish scripting yet so it may not be as idiomatic as possible.

I left the for loop in the install event but the error happened when it was written like the uninstall one.

I looked at all the plugins, I don't see any being completely empty, it would likely fail if done one by one, right ?

> fish, version 3.1.2
> fisher, version 4.1.0

**Comment by jorgebucaran** [comment]
@Marsup Your code works, it can be simplified, but there's nothing wrong with it. I was unable to reproduce the same issue either way. Are you still experiencing the problem or did it go away?

Here's what I do:

```console
$ mkdir -p metafish/conf.d
$ nano metafish/conf.d/metafish.fish
```

```fish
set -l metafish_plugins \
    jethrokuan/z \
    danhper/fish-ssh-agent \
    nickeb96/puffer-fish \
    james2doyle/omf-plugin-fnm

function metafish_install --on-event metafish_install
    fisher install $metafish_plugins
end

function metafish_uninstall --on-event metafish_uninstall
    fisher remove $metafish_plugins
end
```

```console
$ fisher install metafish
installing /Users/jb/metafish
+/Users/jb/.config/fish/conf.d/metafish.fish
fetching https://codeload.github.com/jethrokuan/z/tar.gz/HEAD
fetching https://codeload.github.com/danhper/fish-ssh-agent/tar.gz/HEAD
fetching https://codeload.github.com/nickeb96/puffer-fish/tar.gz/HEAD
fetching https://codeload.github.com/james2doyle/omf-plugin-fnm/tar.gz/HEAD
installing jethrokuan/z
+/Users/jb/.config/fish/functions/__z.fish
+/Users/jb/.config/fish/functions/__z_add.fish
+/Users/jb/.config/fish/functions/__z_clean.fish
+/Users/jb/.config/fish/functions/__z_complete.fish
+/Users/jb/.config/fish/functions/uninstall.fish
+/Users/jb/.config/fish/conf.d/z.fish
To completely erase z's data, remove:
/Users/jb/.local/share/z/data
installing danhper/fish-ssh-agent
+/Users/jb/.config/fish/functions/__ssh_agent_is_started.fish
+/Users/jb/.config/fish/functions/__ssh_agent_start.fish
+/Users/jb/.config/fish/functions/init.fish
<W> fish: An error occurred while redirecting file '/Users/jb/.ssh/environment'
open: No such file or directory
chmod: /Users/jb/.ssh/environment: No such file or directory
source: Error encountered while sourcing file '/Users/jb/.ssh/environment':
source: No such file or directory
installing nickeb96/puffer-fish
+/Users/jb/.config/fish/functions/_puffer_fish_expand_bang.fish
+/Users/jb/.config/fish/functions/_puffer_fish_expand_dots.fish
+/Users/jb/.config/fish/conf.d/puffer_fish_key_bindings.fish
installing james2doyle/omf-plugin-fnm
+/Users/jb/.config/fish/completions/fnm.fish
4 installed plugin/s
1 installed plugin/s
```

Notice the error:

```
<W> fish: An error occurred while redirecting file '/Users/jb/.ssh/environment'
open: No such file or directory
chmod: /Users/jb/.ssh/environment: No such file or directory
source: Error encountered while sourcing file '/Users/jb/.ssh/environment':
source: No such file or directory
```

...it's because I am probably missing something you need to use ssh-agent—it's not your issue.

**Comment by jorgebucaran** [comment]
@Marsup Just an experiment, rename `dotfiles/.fish` to `dotfiles/myfish` and try again. 

Also, the `fishfile` is now `fish_plugins`, so rename that as well.

**Comment by Marsup** [comment]
That is really weird, the very same code I was using yesterday now works, some quirk in github maybe ?

The fishfile can probably disappear now as neither are going to be used anyway. I was hoping to use it in the install and uninstall events to avoid having that variable declaration, but I think there's a path issue that will make it very difficult to achieve.

Case closed I guess as I'm unable to reproduce anymore :man_shrugging: Thanks a lot !

**Comment by jorgebucaran** [comment]
@Marsup No worries, if something's broken, it will come up again eventually and I'll fix it. 

>  I was hoping to use it in the install and uninstall events to avoid having that variable declaration...
> [...] I think there's a path issue that will make it very difficult to achieve.

Ah, that explains why you were using a function. 

What about removing your `dotfiles/.fish/conf.d/plugins.fish` file, and just renaming `fishfile` to `fish_plugins`? That way you just need to run `fisher update` to get everything in all your machines?

**Comment by Marsup** [comment]
That's the 1st thing I tried, it installs my own plugin but not the ones in my fish_plugins file, maybe I wasn't clear in my 1st message.

**Comment by jorgebucaran** [comment]
Sorry, no, I wasn't clear myself. I mean, what if you do this:

```js
curl --silent https://codeload.github.com/Marsup/dotfiles/tar.gz/HEAD | tar --extract --gzip --strip-components 1
cp -R $__fish_config_dir/.fish/{functions,conf.d,completions} $__fish_config_dir
fisher update
```

You could then save that script in a repo or a gist, anywhere you like, then just:

```fish
curl url | fish
```
