### ISSUE TITLE
fisher 4.0 no longer installs dependencies

### ISSUE THREAD

**Issue by NotAFile** [jorgebucaran/fisher#614]
after updating to fisher 4.1 from 3.x, fisher no longer installs dependencies properly. E.g:

```fish
fisher install fish-extras/metro
[...]
fish: git_branch_name: command not found...
[...]
```

**Comment by jorgebucaran** [comment]
@NotAFile Dependency support was removed. Want to help port https://github.com/fish-extras/metro to Fisher `4.x`? Just send me a PR to that repo. Otherwise, I'll get around to it in a few days.

**Comment by NotAFile** [comment]
I have to say, usual caveats about not looking into a gift horses mouth aside, I'm pretty disappointed with how this transition has been handled. Through a normal self-update, without any warning, everything is now unexpectedly broken to the point that I had to recreate my fish config directory from scratch and without even the slightest concern for backwards compatibility, existing users or a smooth migration on fisher's end (for example, not aliasing old commands and file names to new ones with a deprecation warning) and now the whole ecosystem of hundreds of plugins is suddenly incompatible overnight.

What was your plan for users here?

**Comment by jorgebucaran** [comment]
There are very few plugins that use dependencies, and metro was one of them. Guess I forgot about that one. I'll get around to it soon enough. 

> I had to recreate my fish config directory from scratch 

I think I've covered all possible upgrade paths already, other than no-support for dependencies, what else was broken for you?

**Comment by NotAFile** [comment]
Ah, I thought it's use was much more widespread. If the feature has been removed because of few users and the themes were forgotten, that makes a lot more sense.

I'm not sure exactly what the other breakage was, but in retrospect it's probably mostly related to the symlink thing. Either way, after the upgrade, I no longer had a `fisher` command, and `z` was throwing wild errors everywhere. I'd have to try and recreate it to know more.

**Comment by jorgebucaran** [comment]
It's so odd you didn't have a `fisher` command. I think I am handling all possible migrations [here](https://github.com/jorgebucaran/fisher/blob/5368e728631d3e885b1d4de843384666a16e2861/fisher.fish#L176-L200). Is this related to #613? In that case, maybe consider helping me, as I haven't been able to reproduce it in my environment, and I won't be able to fix it until I do.

**Comment by zoomido** [comment]
I'm having problem with enhancd as well: https://github.com/b4b4r07/enhancd
I've been struggling with this and googling for hours now trying to debug why that plugin generated an error. Seems that the dependencies are missing and it's working fine on my older machine.
Is there a quick fix here?

**Comment by jorgebucaran** [comment]
@zoomido Depends on https://github.com/b4b4r07/enhancd/pull/139.

**Comment by jorgebucaran** [comment]
@NotAFile I just finished porting [Metro](https://github.com/metrofish/metrofish) (renamed as Metrofish) to Fisher 4.x and Fish 3.x. I no longer use this prompt, but I'm happy to review and merge PRs with bug fixes, and features. Enjoy!

```console
fisher install metrofish/metrofish
```

**Comment by NotAFile** [comment]
@jorgebucaran that's awesome, thanks so much!
