### ISSUE TITLE
Fisher update error

### ISSUE THREAD

**Issue by denningsrogue** [jorgebucaran/fisher#615]
The command "fisher update" has started producing this error:

> fisher: not enough arguments for command: "update"

**Comment by jorgebucaran** [comment]
Hey, @denningsrogue. That part is [here](https://github.com/jorgebucaran/fisher/blob/5368e728631d3e885b1d4de843384666a16e2861/fisher.fish#L31-L33). You don't have a `fish_plugins` file, so Fisher doesn't know what you want to update. 

Do you remember how you upgraded to `4.x`?

**Comment by denningsrogue** [comment]
I ran top grade this morning.

**Comment by denningsrogue** [comment]
Where would the config file have gone and where should it be.

**Comment by jorgebucaran** [comment]
> @denningsrogue I ran top grade this morning.

What command did you enter exactly?

> Where would the config file have gone and where should it be.

It should've been moved to `$__fish_config_dir/fish_plugins`, but if it didn't, then I probably missed something in the migration script.

**Comment by denningsrogue** [comment]
Topgrade is a rust cargo package that updates using a variety of tools. It ran the command fisher upgrade I think. If I run fisher list I get the plugins I installed.  How do I regenerate the plugins file. Reinstall the plugins?

**Comment by denningsrogue** [comment]
Sorry meant to say Topgrade ran fisher update.

**Comment by denningsrogue** [comment]
I reinstalled the packages I had identified using “fisher list” and now “fisher update” works.

**Comment by denningsrogue** [comment]
Thank you for your help.
