### ISSUE TITLE
Fisher does not correctly add key bindings from key_bindings.fish files

### ISSUE THREAD

**Issue by ngmoviedo** [jorgebucaran/fisher#617]
When installing plugins from Oh-my-fish!  containing a key_bindings.fish file, the bindings get temporally sourced, but stop working upon restart or when opening a new shell. I've noticed that the don't get added to the fish_user_key_bindings function nor to conf.d directory. 
Manually adding the key bindings is simple enough, but I understand that this is not the expected behaviour.
I've have experienced this with plugins sudope and budspencer. I have tried reinstalling and updating but the result was the same.

OS: Arch Linux
Fish version: 3.12
Fisher version: 4.1.0 

Just in case it might be relevant, this is the list of plugins I'm using:

> jorgebucaran/fisher
> oh-my-fish/theme-budspencer
> nickeb96/pisces
> jorgebucaran/bax.fish
> oh-my-fish/plugin-thefuck
> oh-my-fish/plugin-sudope

I do not have any other plugin manager installed.

**Comment by jorgebucaran** [comment]
Is the problem this one: plugin https://github.com/oh-my-fish/plugin-sudope?

**Comment by ngmoviedo** [comment]
Ah, alright. Seems like it was a misunderstanding on my part. I thought that fisher was supposed to source those files in some way, but I see now how that could be problematic. I'll probably do a PR for those plugins when I have the time.
Thanks!

**Comment by jorgebucaran** [comment]
@ngmoviedo Fisher will source those files, but it will not move them to `conf.d` as it used to do in `3.x`, thus the key bindings won't be available in future sessions. Cheers.
