### ISSUE TITLE
How to automate fisher plugin installation

### ISSUE THREAD

**Issue by patrickf3139** [jorgebucaran/fisher#621]
Hi @jorgebucaran, love what you did with fisher 4.0! The code feels more lightweight and the features sharper.
My only small issue is I no longer know what the best way to automate installation of fisher and fisher plugins is.
With 3.0, all I had to do was
```sh
curl --create-dirs --location --output ~/.config/fish/functions/fisher.fish https://git.io/fisher
cp fishfile $HOME/.config/fishfile
fish -c fisher
```
Now that the fishfile is gone, I am stuck. I can't just check in `fish_variables` because that actually create the files being used. I'm thinking I'll do
```sh
curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
for plugin in patrickf3139/fzf.fish IlanCosman/tide etc
    fisher install $plugin
end
```
Not too shabby, but my problem is that it won't auto-update when I remove or install new plugins. Any ideas?

**Comment by jorgebucaran** [comment]
> Now that the fishfile is gone, I am stuck

Not gone. Just [renamed to `fish_plugins`](https://github.com/jorgebucaran/fisher#using-your-fish_plugins-file).

> [...]fish_variables

`fish_variables` is handled by Fish, not by Fisher. I don't think we should be messing with that file.

**Comment by patrickf3139** [comment]
Oh my bad, sorry I should have known that. I was involved in that discussion but thought you abandoned it when you switched to universal variables. Thanks!
