### ISSUE TITLE
`fisher: not enough arguments for command: "update"`

### ISSUE THREAD

**Issue by domoritz** [jorgebucaran/fisher#622]
Running `fisher update`. 

fisher, version 4.1.0

**Comment by jorgebucaran** [comment]
@domoritz Do you remember how you upgraded to `4.x`? This could be a failed migration to `4.x`.

**Comment by domoritz** [comment]
I ran `fisher self-update`.

What's the bets way to fix the installation?

**Comment by jorgebucaran** [comment]
@domoritz That's the correct way to upgrade. Did you have `fishfile`?

To fix the installation right now, just install Fisher:

```console
fisher install jorgebucaran/fisher
```

**Comment by domoritz** [comment]
Yes, I did. Here is the diff of my dotfiles.

<img width="1627" alt="Screen Shot 2020-11-15 at 19 14 12" src="https://user-images.githubusercontent.com/589034/99208945-c8989880-2776-11eb-9668-c2936e861569.png">

`fisher install jorgebucaran/fisher` worked btw. Thank you for the easy fix!

**Comment by jorgebucaran** [comment]
@domoritz Did you rename `fishfile` to `fish_plugins` before running `fisher self-update`?

And were you using a customized `$fisher_path`?

**Comment by jorgebucaran** [comment]
@domoritz Did you upgrade to `4.x` from `2.x` rather `3.x`?

**Comment by domoritz** [comment]
I don't use a custom `$fisher_path` but I may have renamed the file manually (don't remember exactly). I'm fairly sure I was using Fisher (`3.x`) beforehand.

**Comment by jorgebucaran** [comment]
@domoritz Interesting. This information should help me debug this specific migration scenario and patch Fisher to prevent faulty migrations in the future. Thank you!
