### ISSUE TITLE
4.1 isn't fish 2.7.1 comptaible

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fisher#623]
**related:** rafaelrinaldi/pure#228, rafaelrinaldi/pure#229 

---

Pure [CI builds are failing with `2.5`, `2.6` and `2.7.1`](https://travis-ci.org/github/rafaelrinaldi/pure/jobs/742982913#L193-L194) due to the use of `||` syntax in the `4.1` install script. 

For `pure`, I'm suggesting to increase minimal supported version to `2.7.1` (cf. https://github.com/rafaelrinaldi/pure/issues/123#issuecomment-727637463). However your install script will continue to fail on `2.7.1`. 

Would you consider reverting to a `2.7.1`-comptaible syntax?
What is your target support for `fisher`?

**Comment by jorgebucaran** [comment]
Fish `3.0` and the answer is probably no, but I'm curious, what's so particular about `2.7.1`? Why not `2.3.1` or `2.3.0`?

**Comment by jorgebucaran** [comment]
Looks like Pure is going to set their lowest supported version to Fish `3.0`, which is great, so we can also close here. 💯 

Thank you, @edouard-lopez!
