### ISSUE TITLE
v4 b4b4r07/enhancd don't work

### ISSUE THREAD

**Issue by ibeex** [jorgebucaran/fisher#625]
install plugin b4b4r07/enhancd

```
❯ cd ~
gawk: fatal: can't open source file `/home/user/.config/fisher/github.com/b4b4r07/enhancd/lib/step_by_step.awk' for reading (No such file or directory)
```
after manually  creating dir `/.config/fisher/github.com/b4b4r07/` and pulling https://github.com/b4b4r07/enhancd plugin works

**Comment by jorgebucaran** [comment]
Depends on https://github.com/b4b4r07/enhancd/pull/139. 

Also, make sure to upgrade to the latest Fisher (https://github.com/jorgebucaran/fisher/issues/620).
