### ISSUE TITLE
Fisher doesn't automatically load when $fisher_path is custom

### ISSUE THREAD

**Issue by x7a** [jorgebucaran/fisher#628]
@jorgebucaran hey again. I have another problem regarding Fisher. My `$fisher_path` is custom and is set to `~/.local/share/fisher`. Because of this, `fisher.fish` isn't in `~/.config/fish/functions` and so it doesn't load automatically. I have to manually source `~/.local/share/fisher/functions/fisher.fish` to load Fisher. I'm pretty sure it works like that. But I'm not sure if it's supposed to be like that. What do you think?

**Comment by owarai** [comment]
Sorry to comment in a closed issue.

> I really don't recommend changing `$fisher_path`, and I've toyed with the possibility to deprecate it in the future. But if you must change it, you'll also need to reproduce Fish configuration inside your custom `$fisher_path`.

I managed my dotfiles in the symbolic link way and use the method you documented to make plugins installed by fisher don't pollute my personal fish configs. If you have a plan to deprecate `$fisher_path`, is there some more preferred workaround to achieve this?

**Comment by jorgebucaran** [comment]
I've thought about deprecating `$fisher_path`, but I hardly see that actually happening. Ever. Feel free to use it if you must! 🙆‍♂️
