### ISSUE TITLE
fisher: invalid plugin name or host unavailable

### ISSUE THREAD

**Issue by edouard-lopez** [jorgebucaran/fisher#631]
Hello @jorgebucaran,
After a mishap in `pure@3.0.0` release where I forgot to bump the version number I tried to re-install use the `repo/name@version` syntax but it failed

```fish
❯ fisher install rafaelrinaldi/pure@3.0.0
fisher install version 4.1.0
type: Could not find “”
fetching https://codeload.github.com/rafaelrinaldi/pure/tar.gz/3.0.0
fisher: invalid plugin name or host unavailable: "rafaelrinaldi/pure@3.0.0"
```

I tried various package versions and get the same issue:
```
❯ fisher install rafaelrinaldi/pure@2.7.0
fisher install version 4.1.0
type: Could not find “”
fetching https://codeload.github.com/rafaelrinaldi/pure/tar.gz/2.7.0
fisher: invalid plugin name or host unavailable: "rafaelrinaldi/pure@2.7.0"
```

Am I missing something here?

**Comment by edouard-lopez** [comment]
My bad, wrong tag I use a prefix `v`:

```diff
- ❯ fisher install rafaelrinaldi/pure@3.0.0
+ ❯ fisher install rafaelrinaldi/pure@v3.0.0
```

**Comment by jorgebucaran** [comment]
Yes, a "v". It's [**v3.0.0**](https://codeload.github.com/rafaelrinaldi/pure/tar.gz/v3.0.0). Check your [tags](https://github.com/rafaelrinaldi/pure/tags). 😄
