### ISSUE TITLE
Fish crashes after installing any plugin

### ISSUE THREAD

**Issue by michaelpitts** [jorgebucaran/fisher#632]
I am running MacOS Big Sur on a new M1 mac mini. The installation of Fisher itself goes smoothly, but I run into some repeating errors after installing any fish plugin using fisher. 

Immediately after I run `fisher install fishpkg/fish-prompt-metro` I get a long screen of errors that repeat the same errors in a loop. If I try to open another fish shell then it displays the same errors. Below is the error output: 

```
fish: Unknown command: pwd_info
~/.config/fish/functions/fish_prompt.fish (line 1): 
pwd_info "/"
^
in command substitution
	called on line 3 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
~/.config/fish/functions/fish_prompt.fish: Unknown error while evaluating command substitution
in function 'fish_prompt'
in command substitution
fish: Unknown command: git_branch_name
~/.config/fish/functions/fish_prompt.fish (line 1): 
git_branch_name
^
in command substitution
	called on line 33 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
~/.config/fish/functions/fish_prompt.fish: Unknown error while evaluating command substitution
in function 'fish_prompt'
in command substitution
fish: Unknown command: segment
~/.config/fish/functions/fish_prompt.fish (line 76): 
    segment $base_color " $dir"(set_color white)"$base "
    ^
in function 'fish_prompt'
in command substitution
fish: Unknown command: last_job_id
~/.config/fish/functions/fish_prompt.fish (line 94): 
    else if last_job_id > /dev/null
            ^
in function 'fish_prompt'
in command substitution
fish: Unknown command: segment_close
~/.config/fish/functions/fish_prompt.fish (line 119): 
    segment_close
    ^
in function 'fish_prompt'
in command substitution
fish: Unknown command: pwd_info
~/.config/fish/functions/fish_prompt.fish (line 1): 
pwd_info "/"
^
in command substitution
	called on line 3 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
~/.config/fish/functions/fish_prompt.fish: Unknown error while evaluating command substitution
in function 'fish_prompt'
in command substitution
fish: Unknown command: git_branch_name
...
```

**Comment by jorgebucaran** [comment]
Hey, @michaelpitts, yes, this plugin was moved to https://github.com/jorgebucaran/powerline.fish and I haven't finished porting it to the latest architecture yet, meaning it's not compatible with Fisher 4 at this time.

**Comment by michaelpitts** [comment]
@jorgebucaran understood. Thank you for the quick reply!  (I did confirm that my fish was built native for arm64)

**Comment by jorgebucaran** [comment]
Thanks, it will take me a while to port it, so may I suggest you try a different prompt, [Tide](https://github.com/IlanCosman/tide) is pretty good.

**Comment by jorgebucaran** [comment]
@michaelpitts I just finished porting [Metro](https://github.com/metrofish/metrofish) (renamed as Metrofish) to Fisher 4.x and Fish 3.x. I no longer use this prompt, but I still can look into and fix critical bugs when they're found, as well as reviewing and merging PRs. Enjoy!

```console
fisher install metrofish/metrofish
```
