### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by someshkoli** [jorgebucaran/fisher#634]
I'm constantlt getting this error while installing ~~packages~~ plugins. Happening for all packages
![image](https://user-images.githubusercontent.com/41543649/101605101-cbaa4000-3a27-11eb-827c-a99c91852ab6.png)
What could be the reason ?

**Comment by jorgebucaran** [comment]
@someshkoli 

Maybe the host is unavailable? Are you behind a firewall? Or maybe curl is acting out. Do you have a `.curlrc` file? What's your operating system? Do you have a reason to believe you're using an old version of `tar` or one that doesn't support any of these flags: `-x` `-z`, `-f` or `-C`.

The only reason this could happen is if this line fails:

https://github.com/jorgebucaran/fisher/blob/ae423be7256d5797efcd79007935da96e2b7379d/fisher.fish#L93-L98

**Comment by jorgebucaran** [comment]
Maybe the host is unavailable? Are you behind a firewall? Maybe curl is acting out. Do you have a `.curlrc` file? What's your operating system? Do you have a reason to believe you could be using an old version of `tar` or one that doesn't support any of these flags: `-x` `-z`, `-f` or `-C`?

The only reason this could happen is if we fail here:

https://github.com/jorgebucaran/fisher/blob/ae423be7256d5797efcd79007935da96e2b7379d/fisher.fish#L93-L98

**Comment by jorgebucaran** [comment]
@someshkoli Can you answer the questions?

**Comment by someshkoli** [comment]
Hey @jorgebucaran, thanks for quick update. I checked the link and the tar was downloadable. Im running on arch linux `Linux kasper 5.4.77-1-lts #1 SMP Tue, 10 Nov 2020 22:42:03 +0000 x86_64 GNU/Linux`. and yes my tar does have above flags. 

And about .curlrc, what should be the contents of that file ? I dont have rc for that

**Comment by jorgebucaran** [comment]
How did you install Fisher? Please note that I only support the installation method described in the README. If that's how you installed Fisher, please use `fisher update` to get the latest changes and try again. 

Where did you start having this problem? Have you ever been able to install anything with Fisher at all?

**Comment by jorgebucaran** [comment]
Could you also answer the question about the `tar` command?

**Comment by someshkoli** [comment]
I installed it from AUR and regarding tar command then all of the flags are operational.
Also fisher update gives the following:
![image](https://user-images.githubusercontent.com/41543649/101650984-9111c900-3a62-11eb-937e-426c3460a87f.png)

**Comment by jorgebucaran** [comment]
@someshkoli Ah, you're using an older version of Fisher. I know because that's an old bug. Please upgrade to the latest Fisher and let me know if you still encounter this issue. Remove the AUR package and use:

```
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
```

**Comment by someshkoli** [comment]
![image](https://user-images.githubusercontent.com/41543649/101655448-a3dacc80-3a67-11eb-8846-a239d6d423b3.png)

**Comment by jorgebucaran** [comment]
@someshkoli You're still not using the latest Fisher. I know because "fisher: invalid plugin name..." should be "fisher: Invalid plugin name..." instead. 

See, it's right here:

https://github.com/jorgebucaran/fisher/blob/ae423be7256d5797efcd79007935da96e2b7379d/fisher.fish#L96

**Comment by someshkoli** [comment]
How to clean previous versions completely ? :)

**Comment by jorgebucaran** [comment]
Yes, I think that might be the issue here. To remove Fisher you can simply: `fisher remove jorgebucaran/fisher". But if you installed Fisher via the AUR package with `pacman` (which I don't support), you'll need to refer to your user manual. I don't know, how about `pacman -Rns fisher`?

**Comment by someshkoli** [comment]
I removed everything and installed via above method, Now even the version number is correct yet its giving me same error 
![image](https://user-images.githubusercontent.com/41543649/101657010-68410200-3a69-11eb-8ddf-934593879647.png)

**Comment by jorgebucaran** [comment]
@someshkoli Could you try again? I made some changes.

**Comment by someshkoli** [comment]
still not working :) maybe its something specific for my system

**Comment by jorgebucaran** [comment]
@someshkoli It could be. Try running this? 

```fish
set --local temp (mktemp -d)
set --local url https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD
curl --silent --write-out "" $url | tar --extract --gzip --directory $temp
ls $temp
```

**Comment by igalic** [comment]
i get:

```
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```

after removing `--silent`.

**Comment by jorgebucaran** [comment]
Does that mean --silent doesn't work on FreeBSD? @igalic

**Comment by igalic** [comment]
it does work, but i had to remove it to see what's failing

**Comment by jorgebucaran** [comment]
> Warning: Binary output can mess up your terminal. Use "--output -" to tell 

That's why we pipe it to `tar`.

Do you know how to make this work on FreeBSD? Or do you know how to set up a FreeBSD box free so I can test this?

**Comment by jorgebucaran** [comment]
@igalic Do you have a `.curlrc` file adding a new line to the output? 

We shouldn't need to use `--write-out ""`.

Why do we need to use `--output -`? It's not needed on macOS or Linux. Is this a FreeBSD thing?

Why do we need to add `-f -` to `tar`? Is this also a FreeBSD thing?

**Comment by igalic** [comment]
it seems the only thing necessary we need is `-f -`, otherwise, FreeBSD tries to read from a Tape device :D 

```
meena@beastix ~> curl --silent https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD | tar --extract --gzip --directory $temp -f -
meena@beastix ~> rm -rf /tmp/tmp.MW0chCId/fisher-HEAD/
meena@beastix ~> curl --silent https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD | tar --extract --gzip --directory $temp 
tar: Error opening archive: Failed to open '/dev/sa0'
meena@beastix ~ [23|1]> 
```

**Comment by igalic** [comment]
re, 

> And do you know how to set up a FreeBSD box free so I can test this?

https://www.freebsd.org/where.html → https://download.freebsd.org/ftp/releases/VM-IMAGES/12.2-RELEASE/amd64/Latest/
see https://download.freebsd.org/ftp/releases/VM-IMAGES/README.txt for which image to get

if you wanna integrate FreeBSD into fisher's CI, Cirrus CI offers FreeBSD support: https://cirrus-ci.org/guide/FreeBSD/

**Comment by jorgebucaran** [comment]
I think we're good now @igalic @someshkoli. Please try one more time! 🙏

**Comment by igalic** [comment]
works! (for me ;)

**Comment by someshkoli** [comment]
> @someshkoli It could be. Try running this?
> 
> ```fish
> set --local temp (mktemp -d)
> set --local url https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD
> curl --silent --write-out "" $url | tar --extract --gzip --directory $temp
> ls $temp
> ```

Still not working :"") some gzip error
![image](https://user-images.githubusercontent.com/41543649/101779355-2d97a200-3b1b-11eb-90b1-1ddfa289502c.png)

**Comment by igalic** [comment]
> Still not working :"") some gzip error

can you remove `--silent` so we can better see what's going on?

**Comment by jorgebucaran** [comment]
@someshkoli Answer this:

- OS name and version
- Fish version
- curl version
- tar version

**Comment by someshkoli** [comment]
OS: 
    LSB Version:	1.4
    Distributor ID:	Arch
    Description:	Arch Linux
    Release:	rolling
    Codename:	n/a
Fish: fish, version 3.1.2
CURL: curl 7.71.1
tar: tar (GNU tar) 1.32
XD

**Comment by someshkoli** [comment]
Got this error fixed with @jorgebucaran 's help <3. 
My conda env was somehow messing with my normal env and curl was unable to fetch CA certs

**Comment by jorgebucaran** [comment]
@someshkoli fixed this 1on1. Thank you, Somesh! Turns out he had a similar problem to the one described [here](https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url).

Basically, all we had to do was:

```fish
set --export --global CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt
```

🎉

**Comment by jorgebucaran** [comment]
Thank you, Somesh! Turns out he had a similar problem to the one described [here](https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url). It was a local issue with curl and SSL certs.

This fixed it.

```fish
set --export --global CURL_CA_BUNDLE /etc/ssl/certs/ca-certificates.crt
```

**Comment by akhiljalagam** [comment]
I just removed my ~/.curlrc with backup and it worked.

**Comment by cosmojg** [comment]
Leaving a tip here for future me: make sure that you have `gzip` installed! 😵‍💫

**Comment by jorgebucaran** [comment]
Gzip or tar? 🤔

**Comment by jorgebucaran** [comment]
Why gzip? Fisher doesn't use gzip as far as I know, and I wrote the code. I could be missing something, though.

**Comment by hknguyenvu** [comment]
My case:

When I run:
```
set --local temp (mktemp -d)
set --local url https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD
curl --write-out "" $url | tar --extract --gzip --directory $temp
```

I see:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to codeload.github.com port 443 after 11 ms: Couldn't connect to server

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

That's because my server just have IPv6 so it cannot connect to codeload.github.com. I must buy more IPv4 and assign it on my server.
