### ISSUE TITLE
Mono Prompt Compatibility

### ISSUE THREAD

**Issue by heywoodlh** [jorgebucaran/fisher#636]
When trying to install [mono](https://github.com/jorgebucaran/mono.fish), the install command fails due to `fisher add` being deprecated. 

I've been able to get it working if I manually `fisher install` everything in the `fishfile`.

I love Mono as my prompt, mainly I'm just reporting that Mono and Fisher don't work together anymore.

**Comment by jorgebucaran** [comment]
Yes, I'm aware Mono is currently not compatible with Fisher 4.x. I still haven't finished porting all my prompts and plugins. I'll get around to it sooner than later. You're always free to send me a PR fixing the errors in the meantime, otherwise, please wait for a while. 👋

**Comment by jorgebucaran** [comment]
@heywoodlh  [Fly.fish](https://github.com/jorgebucaran/fly.fish) is the continuation of and successor to Mono. It's rather different from old Mono, hence the new name. I'm afraid you'll need to use a fork if you want to keep using old Mono instead. Cheers.

**Comment by jorgebucaran** [comment]
[Fly.fish](https://github.com/jorgebucaran/fly.fish) is the continuation of and successor to Mono. It's rather different from old Mono, hence the new name. I'm afraid you'll need to use a fork if you want to keep using old Mono instead. Cheers.
