### ISSUE TITLE
"update" command restore symlink to normal file

### ISSUE THREAD

**Issue by kosukemori** [jorgebucaran/fisher#637]
Hi!
I'm using mackup, so I change `~/.config/fish/fish_variables` as a symlink file.
However, `fisher update` command restores the symlink file to normal file.

For example,
```
# OS: macOS Big Sur (11.0.1)

# After install fisher, (no need to install mackup for reproducing)
mv ~/.config/fish/fish_variables ~/fish_variables
ln -sfn ~/fish_variables ~/.config/fish/fish_variables
ls -la ~/.config/fish/ # fish_variables is a symlink file

fisher update
ls -la ~/.config/fish/ # fish_variables becomes a normal (not symlink) file
```

I found that if I comment out the below line, this problem is solved. But I don't know why, because this line only erases an local environmental value...
https://github.com/jorgebucaran/fisher/blob/f5b6254833f432101e4deaf7663995fd69a1a4fd/fisher.fish#L134

**Comment by jorgebucaran** [comment]
@kosukemori Please state your Fish and Fisher version.

**Comment by kosukemori** [comment]
@jorgebucaran 
Oh, sorry,
```
$ fish -v
fish, version 3.1.2

$ fisher --version
fisher, version 4.1.0
```

**Comment by jorgebucaran** [comment]
@kosukemori Can one normally create and erase universal variables if `fish_variables` is as symlink?

**Comment by kosukemori** [comment]
@jorgebucaran 
I see, I can create or erase universal variables, but `fish_variables` always becomes a normal file from symlink.
It seems an fish shell's problem.

**Comment by jorgebucaran** [comment]
@kosukemori Exactly. You can read more about universal variables [here](https://fishshell.com/docs/current/#more-on-universal-variables).

> Universal variables are stored in the file .config/fish/fish_variables. **Do not edit this file directly, as your edits may be overwritten**. Edit the variables through fish scripts or by using fish interactively instead.

Emphasis is mine.

**Comment by jorgebucaran** [comment]
@kosukemori Or symlink the entire directory. See: https://github.com/fish-shell/fish-shell/issues/7466

**Comment by kosukemori** [comment]
Thanks @jorgebucaran !
I'll symlink the entire directory by configuring mackup.
(Actually mackup's default configuration of fish & fisher seems to be old.)

**Comment by jorgebucaran** [comment]
You may also run into https://github.com/jorgebucaran/fisher/issues/611, so please be aware.

**Comment by jorgebucaran** [comment]
@kosukemori You may be interested in https://github.com/fish-shell/fish-shell/pull/7728. 👋

**Comment by kosukemori** [comment]
@jorgebucaran Thanks! It looks great. I'll try the HEAD version of fish.
