### ISSUE TITLE
Restore default mode prompt after removing a plugin that overrides fish_mode_prompt

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#638]
The default is always in `$__fish_data_dir/functions/fish_mode_prompt.fish`. Just source it.

**Comment by edouard-lopez** [comment]
Also I don't think that's the responsibility of the plug-ins manager to backup/restore states.

**Comment by jorgebucaran** [comment]
Agreed. Prompts could also handle this.

**Comment by jorgebucaran** [comment]
Agreed. A solution for #624 will likely improve the situation here as well.  Prompts could also handle this using the event system. Closing.
