### ISSUE TITLE
Add the ability to disable plugins

### ISSUE THREAD

**Issue by tuxiqae** [jorgebucaran/fisher#642]
From what I can tell, at currently, Fisher only allows removing plugins from the system, but it won't let you disable and re-enable plugins.

I think that it would be a neat feature, sometimes people don't have an active internet connection but want to disable a plugin temporarily (for example there's a bug in the shell, the user would like to start disabling plugins in order to find the culprit)

**Comment by jorgebucaran** [comment]
> sometimes people don't have an active internet connection 

Sometimes we are offline for some reason, but it's rare. This could be addressed by re-introducing the fallback cache if the `curl | tar` pipeline fails.

**Comment by jorgebucaran** [comment]
We could address this use case by re-introducing a cache fallback if the `curl | tar` pipeline fails, instead of introducing new dedicated commands.

> sometimes people don't have an active internet connection 

Sometimes we are offline for some reason, but it's rare.

**Comment by IlanCosman** [comment]
I'd say this shouldn't be added. Being offline is quite rare these days, so that point is a minor one. It also takes at most a few seconds to install/uninstall a plugin since they are so small. 

As Jorge said, Fisher already had this with the cache fallback. It was determined, for the reasons stated above, that it was cruft.

**Comment by jorgebucaran** [comment]
Re-introducing a cache fallback would certainly here, but that should be discussed on a different issue. Feel free to request back the cache but be prepared to justify why. I won't be adding any specialized commands to enable and disable plugins at this time so I'm closing here.
