### ISSUE TITLE
fisher update fails

### ISSUE THREAD

**Issue by mordax777** [jorgebucaran/fisher#646]
When running `fisher update` I expected it to update all the plugins, but it fails.

Output:
```
❯ fisher update
fisher: Not enough arguments for command: "update"
```

**Comment by jorgebucaran** [comment]
How did you install Fisher and what version are you using?

**Comment by mordax777** [comment]
I installed fisher with fisher, like it is described in the `README.md`.

Version:
```
❯ fisher --version
fisher, version 4.1.0
```

**Comment by jorgebucaran** [comment]
Were you using Fisher before or is this your first time?

**Comment by mordax777** [comment]
I did use it before.

**Comment by jorgebucaran** [comment]
This may be due to a wrong migration. I guess our migration script isn't quite there yet. 

Remove everything, including your `fish_plugins` and `fishfile` if there if one, reinstall and you should be good.

**Comment by jorgebucaran** [comment]
This may be due to a wrong migration. I guess our migration script isn't quite there yet. 

Remove everything, including your `fish_plugins` and `fishfile` if there is one, reinstall, and you should be good.

**Comment by jorgebucaran** [comment]
`fisher: Not enough arguments for command: "update"` is not very helpful, so I'm going to change this error message to something more useful. The problem is that you don't have a `fish_plugins` file for some reason. Maybe you removed it by mistake. Maybe the migration didn't create it when you upgraded to the 4.x line. We'll never know.

If you reinstall Fisher the problem should go away.

**Comment by mordax777** [comment]
To anyone who is coming across this:
My problem was that I did not have a plugin installed over fisher. After I installed one, it worked perfectly fine.
The fisher log is a bit misleading.
CC: @jorgebucaran

**Comment by jorgebucaran** [comment]
@mordax777 https://github.com/jorgebucaran/fisher/commit/3edac36e3832858b890a416bf5e6c98917fba390
