### ISSUE TITLE
Remove support for .fish files outside a functions directory

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#651]
Functions to `functions/`. Completions to `completions/`. Shell startup snippets to `conf.d/`. That leaves top-level `.fish` files out of place. Very much in line with Python's "there should be one—and preferably only one—obvious way to do it", and Fish's [law of orthogonality](https://fishshell.com/docs/current/design.html#the-law-of-orthogonality), I want to drop support for top-level `.fish` files on principle.

I'm thinking of doing this in the following steps:

- [x] Move Fisher's top-level `fisher.fish` to `functions/fisher.fish`.
- [x] Update `4.x` upgrade guide (#620). Because we'll break old Fisher installations.
- [x] Remove support in 4.2.0 with a warning.

If a plugin suddenly stops working, nicely ask the maintainers to modernize it, or even better, send them a PR moving all top-level `.fish` files into the `functions` directory.

**Comment by domoritz** [comment]
Hi @jorgebucaran. I got a warning about https://github.com/oh-my-fish/plugin-pyenv and https://github.com/oh-my-fish/plugin-cd not being supported anymore. I guess it's because of the `init.fish` files, right? Is it enough to just move them to `conf.d/` or somewhere else? What about `uninstall.fish` in `plugin-cd`?

**Comment by jorgebucaran** [comment]
The correct way to port Oh My Fish! plugins to Fish is:
- Move `init.fish` to <code>conf.d/<i>plugin_name</i>.fish</code>
- Copy top-level functions `./*.fish` to `functions`.
- Erase `uninstall.fish`. Use [event system](https://github.com/jorgebucaran/fisher#event-system) instead.

**Comment by jorgebucaran** [comment]
To port Oh My Fish! plugins to Fish:
1. Move `init.fish` to <code>conf.d/<i>plugin_name</i>.fish</code>
2. Copy top-level functions `./*.fish` to `functions`.
3. Erase `uninstall.fish`. Use [event system](https://github.com/jorgebucaran/fisher#event-system) instead.

**Comment by jorgebucaran** [comment]
To modernize an Oh My Fish! plugin:
1. Move `init.fish` to <code>conf.d/<i>plugin_name</i>.fish</code>
2. Copy top-level functions `./*.fish` to `functions`.
3. Erase `uninstall.fish`. Use [event system](https://github.com/jorgebucaran/fisher#event-system) instead.

**Comment by domoritz** [comment]
Done in https://github.com/oh-my-fish/plugin-cd/pull/15 and https://github.com/oh-my-fish/plugin-pyenv/pull/9.

**Comment by joseluisq** [comment]
I don't know if you have thought about it but how about script (.fish) files that you don't want to pack to users like testing or automation intended ones? How do we tell Fisher about it? Is not suitable to just skip "top-level" script files? 

Those are some concerns since newer Fisher breaks plugin installations that contains .fish script files outside Fish dirs.

**Comment by jorgebucaran** [comment]
When installing plugins, in addition to `.fish` files, we also copy any files and directories inside your plugin `functions/`, `conf.d/`, and `completions/` to $fisher_path under `functions/`, `conf.d`, and `completions` respectively, allowing you to access these resources easily (#581).

**Comment by jorgebucaran** [comment]
When installing plugins, in addition to `.fish` files, we also copy any files and directories inside your plugin `functions/`, `conf.d/`, and `completions/` to $fisher_path under `functions/`, `conf.d`, and `completions` respectively, allowing you to access these resources easily (#581).

You can also place `.fish` files in directories in the top-level, for example, I put Fisher tests in [`tests/`](https://github.com/jorgebucaran/fisher/tree/main/tests).

**Comment by joseluisq** [comment]
> I put Fisher tests in [`tests/`](https://github.com/jorgebucaran/fisher/tree/main/tests).

I did the same and now no more messages but my question is more about what do we need to care about "top-level" script files? Can Fisher just skip them since Fish dirs are well known.

**Comment by jorgebucaran** [comment]
Fisher ignores top-level `.fish` files. I think the error message is confusing and makes people think Fisher won't install the plugin. I am just going to remove that warning in the next minor bump (#666). 🤘

**Comment by jorgebucaran** [comment]
Fisher ignores top-level `.fish` files. I think the error message is confusing and makes people mistakenly think Fisher won't install the plugin. I am just going to remove the warning in the next minor bump (#666). 🤘
