### ISSUE TITLE
How do I upgrade to Fisher 4.x?

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#652]
If you're upgrading from `3.x` or older:

1. Upgrading will remove installed plugins, so make a list of the current state for later:

```fish
set --local plugins (read --null <~/.config/fish/fishfile)
```

2. Uninstall the old Fisher:

```console
$ fisher self-uninstall
```

3. Install the latest Fisher and restore previously installed plugins:

```console
$ curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher $plugins
```

**Comment by hedefalk** [comment]
Self-uninstall doesn't seem to work?

❯ fisher self-uninstall
fisher: Unknown command: "self-uninstall"

❯ fish --version
fish, version 3.1.2
