### ISSUE TITLE
Fisher self-update is broken

### ISSUE THREAD

**Issue by edheltzel** [jorgebucaran/fisher#656]
Any time I run `fisher self-update` the response:

```shell
fetching https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish
fisher: cannot update fisher -- are you offline?
```
Both URLs listed below return a 404
https://raw.githubusercontent.com/jorgebucaran/fisher/main/fisher.fish
OR
https://raw.githubusercontent.com/jorgebucaran/fisher/master/fisher.fish

Looks like it should be
https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish

**Comment by jorgebucaran** [comment]
We have instructions you can follow to upgrade from Fisher 3.x in the migration guide: https://github.com/jorgebucaran/fisher/issues/652. 💁‍♂️✨

Let me know if you need more help. 👋

**Comment by edheltzel** [comment]
@jorgebucaran thanks - though I find it very odd that setting up my new mac and using the 
`curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher` it would be install an old version. But none the less thank you.

**Comment by jorgebucaran** [comment]
That's odd, indeed. What happens when you go to https://git.io/fisher now?

**Comment by edheltzel** [comment]
Takes me there - which looks correct `https://raw.githubusercontent.com/jorgebucaran/fisher/HEAD/functions/fisher.fish`

Though I'm having all kind of issues with the apple ARM but that's unrelated to this - Your sets from issue #652 worked so thanks for that!
