### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by ainmosni** [jorgebucaran/fisher#657]
Right now, install tries to use `codeload.github.com` to fetch any non-local package. This makes it impossible for fisher to install plugins from GitLab or any other hosts. I found #337, which indicates that gitlab was supported at one point, can support for gitlab (and potentially other hosts)  be restored?

**Comment by jorgebucaran** [comment]
We could if it's not a lot of work. Do you want to send a PR?

[Here](https://github.com/jorgebucaran/fisher/blob/56c629a3a9086f33eeae801598b2046cab9bea6b/functions/fisher.fish#L85) is where we set the URL before attempting to curl-download it.

**Comment by ainmosni** [comment]
Yeah I already found that, what would the preferred syntax be? To keep the rest of the logic intact, I could go gitlab specific and make it gitlab:user/repo, and then someone else can add more generic support later.

**Comment by Scrumplex** [comment]
fisher used to have `gitlab.com/user/repo` before iirc.

**Comment by ainmosni** [comment]
That's also fine, I have no strong feelings tbh.

**Comment by jorgebucaran** [comment]
`gitlab.com/user/repo` would be the least surprising way to go about this IMO.

**Comment by jorgebucaran** [comment]
Something like this might do it. All the escaping is because we happen to calculate the URL inside the background job. 🤖

```fish
switch $plugin
    case gitlab\\*
        set url https://\$name[1]/-/archive/\$name[2]/(string replace --all --regex -- '^.*/' '' \$name[1])-\$name[2].tar.gz
    case \\*
        set url https://codeload.github.com/\$name[1]/tar.gz/\$name[2]
end
```

**Comment by ainmosni** [comment]
@jorgebucaran I went a bit different, and yeah the escaping  broke my head for a bit. :)

**Comment by jorgebucaran** [comment]
Just to let you know that this is still on my radar. I am just letting it cook for a while.

**Comment by TeddyDD** [comment]
While you at it, why not to add support for fetching arbitrary tar.gz? This would enable users to use any code hosting (as long it allows downloading branch as tarball). So Sourcehut, Gitea, HTTP server running on the toaster etc. would be supported.
