### ISSUE TITLE
install or add?

### ISSUE THREAD

**Issue by askhat** [jorgebucaran/fisher#660]
Hey,

I'm confused, the [readme says](https://github.com/jorgebucaran/fisher#installing-plugins), installation of a plugin is initiated trough `install` command, while the help message says is `add`. Clearly, only `add` works, but before I rush into editing readme, I thought I might raise an issue and sort things out in case I'm missing something.

So, which one is it `add` or `install`?

<img width="1002" alt="Screenshot 2021-02-19 at 11 56 59" src="https://user-images.githubusercontent.com/3759947/108481714-9339a480-72a9-11eb-89a8-224bffb5c218.png">

Related issue: https://github.com/edc/bass/pull/96

**Comment by jorgebucaran** [comment]
Hey! 👋 

`install` is the answer.

Just upgrade to the latest Fisher (https://github.com/jorgebucaran/fisher/issues/652) and you'll be good.

**Comment by jorgebucaran** [comment]
`install`. Just upgrade to the latest Fisher (https://github.com/jorgebucaran/fisher/issues/652) and you'll be good. 👋
