### ISSUE TITLE
Suppress top-level file deprecation warning

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/fisher#666]
Fish common directories are well-known. Let's remove the warning (or make it less confusing).

```console
$ fisher install pipo
fisher: Plugin not supported: "/home/jb/pipo"
Support for .fish files outside a functions directory is deprecated https://github.com/jorgebucaran/fisher/issues/651
Installing /home/jb/pipo
           /home/jb/.config/fish/functions/pipo.fish
Updated 1 plugin/s
```

**Comment by joseluisq** [comment]
Great,
The motivation comes really from https://github.com/joseluisq/gitnow/issues/34

**Comment by joseluisq** [comment]
Just a comment:
Do you mean `fisher: Plugin not supported:` or `fisher: Plugin file not supported:` ? Because Fisher installs the plug-in anyway.

**Comment by jorgebucaran** [comment]
I decided to go ahead and remove the warning. As you said, Fish dirs are well-known. 🎉
