### ISSUE TITLE
Fetch arbitrary tar.gz as plugin

### ISSUE THREAD

**Issue by TeddyDD** [jorgebucaran/fisher#667]
Proposal, generalization of #657

`install` command should allow installing plugins from arbitrary URL

So if `install` argument is not Github short form or Gitlab URL then `install` should just assume that argument is a URL that points to tar.gz file. 

This would enable users to install plugins form

- Sourcehut
- Gitea
- Codeberg
- Fossil
- HTTP servers

without any changes in Fisher code.

**Comment by jorgebucaran** [comment]
Cool, but can we get the namespace and name from the URL alone? Fisher needs a way to identify plugins, e.g., `piyo/poyo`.

**Comment by TeddyDD** [comment]
With heuristics - not reliably. This information would have to be passed by the use explicitly or the requirement to have namespace/name would have to be relaxed.

**Comment by jorgebucaran** [comment]
It's tricky then. Particularly difficult is implementing updating and removing, since we can't rely on the URL to generate the plugin/name, not to mention error handling.

**Comment by jorgebucaran** [comment]
Closing as I won't be implementing this and I'm not looking to add this to Fisher any time soon.
