### ISSUE TITLE
failed writing body

### ISSUE THREAD

**Issue by thernstig** [jorgebucaran/fisher#672]
Is this maybe the same issue as you had with nvm.fish if you remember?

```sh
~/code> fisher install jorgebucaran/nvm.fish
fisher install version 4.3.0
Fetching https://codeload.github.com/jorgebucaran/nvm.fish/tar.gz/HEAD
Installing jorgebucaran/nvm.fish
           /home/userA/.config/fish/functions/_nvm_index_update.fish
           /home/userA/.config/fish/functions/_nvm_list.fish
           /home/userA/.config/fish/functions/_nvm_version_activate.fish
           /home/userA/.config/fish/functions/_nvm_version_deactivate.fish
           /home/userA/.config/fish/functions/nvm.fish
           /home/userA/.config/fish/conf.d/nvm.fish
           /home/userA/.config/fish/completions/nvm.fish
Downloading the Node distribution index for the first time...
(23) Failed writing body
Installed 1 plugin/s
~/code> fisher --version
fisher, version 4.3.0
```

I am on Ubuntu 20.04.

**Comment by jorgebucaran** [comment]
I think it's nvm, not Fisher, but the fact that you are installing nvm in this log makes it difficult to know. Can you get a repro by installing a different plugin?

**Comment by thernstig** [comment]
Tried to repro with uninstalling/installing another plugin, but it worked fine everytime. So maybe it is nvm afterall. Not sure it is important enough to care about, I was just hoping it was because of a missing thing in fisher.

**Comment by jorgebucaran** [comment]
Sounds like nvm is at it again! Care to open a new issue over there? I'll look into it.

**Comment by thernstig** [comment]
https://github.com/jorgebucaran/nvm.fish/issues/154
