### ISSUE TITLE
updating packages from fish_plugins

### ISSUE THREAD

**Issue by bdarcus** [jorgebucaran/fisher#673]
I'm wondering about this section of the README on updating via the fish_plugins file.

https://github.com/jorgebucaran/fisher#using-your-fish_plugins-file

I was expecting that if I moved/symlinked that version-controlled file to my fish dir, that fisher would install packages missing from that list upon running `fisher update`.

So two questions:

1. Am I correct that's not currently possible?
2. Is there a reason it wouldn't be in the future?

Thanks for this project, BTW; it's really elegant in its simplicity and flexibility.

**Comment by jorgebucaran** [comment]
Fisher will install plugins missing **in your system** listed in `fish_plugins` upon running `fisher install`. That's exactly what Fisher does. It will also remove if they are not on the list.

Fisher knows which plugins it should install, update, or remove by diffing the content of `$__fish_config_dir/fish_plugins` against its global state, e.g.:

```console
$ printf "%s\n" $_fisher_plugins
/home/jb/Code/fisher
/home/jb/Code/nvm.fish
/home/jb/Code/hydro.fish
/home/jb/Code/autopair.fish
/home/jb/Code/spark.fish
/home/jb/Code/replay.fish
```

Those are the plugins I currently have installed. If I modify `fish_plugins` as follows and run `fisher install`:

```diff
jorgebucaran/fisher
jorgebucaran/nvm.fish
+ ilancosman/tide
- jorgebucaran/hydro.fish
- jorgebucaran/autopair.fish
- jorgebucaran/spark.fish
- jorgebucaran/replay.fish
```

Fisher will update Fisher and nvm.fish (because they are still on the list), remove everything else, and install Tide.

**Comment by bdarcus** [comment]
Got it.

I was missing that was a diff.

Sorry, and thanks for taking the time to explain.

**Comment by jorgebucaran** [comment]
My pleasure! 👍

**Comment by jorgebucaran** [comment]
Correction: `fisher update`, not `install`.

**Comment by bdarcus** [comment]
> Correction: `fisher update`, not `install`.

That makes sense :-)

This bit in that section is what confused me:

"You can also edit this file and run fisher update to commit changes. Here's an example:"

As I said above, in retrospect I should have understood the example below was referring to a diff of the file, but this might be more clear?

"You can also edit this file and run fisher update to commit changes. Here's an example diff that represents such an edit:"

**Comment by bdarcus** [comment]
Hmm .. I so I added the autopair plugin to the end of the list so that I now have 11, but running `fisher update` did not include it.

![Screenshot from 2021-04-20 07-46-01](https://user-images.githubusercontent.com/1134/115390773-a46d3780-a1ac-11eb-885b-ebd5cbd1870b.png)

**Comment by jorgebucaran** [comment]
It's hard to say without a full log and a dump of your set environment. Check `$__fish_config_dir/fish_plugins`.

**Comment by jorgebucaran** [comment]
> As I said above, in retrospect I should have understood the example below was referring to a diff of the file, but this might be more clear?

> "You can also edit this file and run fisher update to commit changes. Here's an example diff that represents such an edit:"

You are welcome to open a PR.

**Comment by jorgebucaran** [comment]
> As I said above, in retrospect I should have understood the example below was referring to a diff of the file, but this might be more clear?

> "You can also edit this file and run fisher update to commit changes. Here's an example diff that represents such an edit:"

You are welcome to open a PR. 😄

**Comment by bdarcus** [comment]
> You are welcome to open a PR.

Just wanted conformation before doing that. 

PR is at #674.

> It's hard to say without a full log and a dump of your set environment. Check $__fish_config_dir/fish_plugins.

So I had setup that file as a symlink. 

If I instead copy over the actual file, it works.

Should I not use a symlink, or is there some nuance I'm missing on how best to do that?

**Comment by jorgebucaran** [comment]
Maybe Fisher doesn't know how to write to fish_plugins if it's a symlink.

Here's the relevant code:

https://github.com/jorgebucaran/fisher/blob/b9b1eda07a9325e7641f3f79f9c7a08d8de3b357/functions/fisher.fish#L184-L186

**Comment by bdarcus** [comment]
> Maybe Fisher doesn't know how to write to fish_plugins if it's a symlink.

I'm new to fish also and so learning how it deals with symlinks and such.

But I just did some testing, and it seems like it should work.

I'll do some more experimenting. Worst case I'll just copy over the file, rather than symlink.
