### ISSUE TITLE
How can I edit the path in fisher

### ISSUE THREAD

**Issue by kisira** [jorgebucaran/fisher#677]
How do I edit the path in fisher? I installed a new program that requires me to edit the path, how can I do this?

**Comment by jorgebucaran** [comment]
You can set `$fisher_path` to your preferred location. But that means you'll also need to take care of:

- setting `fish_function_path`
- setting `fish_complete_path`, and
- sourcing `*.fish` files in `$fisher_path`

Here's an example of how to do that. 

> You may need to tweak this code depending on your specific needs.

```fish
set fisher_path # new/fisher/path

set fish_function_path $fish_function_path[1] $fisher_path/functions $fish_function_path[2..-1]
set fish_complete_path $fish_complete_path[1] $fisher_path/completions $fish_complete_path[2..-1]

for file in $fisher_path/conf.d/*.fish
    source $file
end
```

**Comment by kisira** [comment]
I don't meant the fisher path, I am trying to edit the system path. Meaning where can I change how programs are found. For example I install a program, like say pro2cmake(a script) and I want to be able to execute it from anywhere in the the shell, how can I edit the system path so that this program is found whenever I want to execute it in the shell

**Comment by jorgebucaran** [comment]
Can be done by editing the `$PATH`: https://fishshell.com/docs/current/tutorial.html#path.
