### ISSUE TITLE
Issue with omf plugin mgoodness/plugin-asp

### ISSUE THREAD

**Issue by yongyili** [jorgebucaran/fisher#680]
Hi,
I have installed [https://github.com/m-radzikowski/omf-plugin-asp](https://github.com/m-radzikowski/omf-plugin-asp) by using below command:
`fisher install mgoodness/plugin-asp`
but when I tried to set profile, I received below error:
```bash
$asp aws_profile_name
__fish_print_aws_profiles: command not found
in command substitution
        called on line 2 of file ~/.config/fish/functions/asp.fish
in function 'asp' with arguments 'aws_profile_name'
~/.config/fish/functions/asp.fish (line 2): Unknown command
  set available_profiles (__fish_print_aws_profiles)
                         ^
in function 'asp' with arguments 'aws_profile_name'
Profile "aws_profile_name" not found
Available profiles:
```

**Comment by jorgebucaran** [comment]
Hi @yongyili. They need to move `init.fish` to `conf.d/asp.fish`, then it should work. Possibly. 😄

**Comment by yongyili** [comment]
But If I used omf to install it, it worked well.

**Comment by jorgebucaran** [comment]
Maybe OMF still supports plugins with `.fish` files outside canonical locations: `functions`, `conf.d`, or `completions`.

We don't. See https://github.com/jorgebucaran/fisher/issues/651 for more info.
