### ISSUE TITLE
Fisher not autoloading plugins?

### ISSUE THREAD

**Issue by jasonhan-vassar** [jorgebucaran/fisher#681]
Hi, so I've installed `bass` using the command `fisher install edc/bass`. After installation, I can use the `bass` command. However, after restarting my terminal, the CLI does not recognize `bass` as a command. Should this be happening? I am under the impression that installing a plugin meant also autoloading it. Thanks for reading.

### System Info
fish 3.3.1
fisher 4.1.0

**Comment by Scrumplex** [comment]
Autoloading is handled by fish, not fisher.
When you run `fisher install edc/bass` it prints out the path where bass will be placed into (in my case it's `$HOME/.config/fish/functions/bass.fish`).
Make sure that that path is in your `$fish_function_path`

**Comment by jasonhan-vassar** [comment]
I see. So `bass` is just a way to copy the plugins into the functions folder and nothing more?

**Comment by Scrumplex** [comment]
> Also, `fisher` seems to copy the scripts into `$HOME/.config/fish/fisher/functions`, and not `fish/functions`. I'm not sure if I set this up a long time ago or if this is default behavior.

That is probably the issue. I think the variable responsible for that is `$fisher_path`. So just unset it universally and you should be fine: `set -Ue fisher_path`

**Comment by jorgebucaran** [comment]
> I am under the impression that installing a plugin meant also autoloading it

Definitely.

@jasonhan-vassar I just tried `fisher install edc/bass` and I was able to use `bass` in the same tab, as well as new tabs or upon restarting the terminal.

How did you install Fisher?

**Comment by jasonhan-vassar** [comment]
I'm not too sure, it's been a while. I believe I added `fisher.fish` to my `fish/functions` folder, and somehow set `$fisher_path`? From above, you can see it's been set to `$HOME/.config/fish/fisher`, so that already explains things. Actually, I'm pretty sure I set this to separate `fisher`'s installs from my other functions. I'm going to keep it like this and just autoload fish/fisher/functions.

**Comment by jorgebucaran** [comment]
The only supported installation method is described in the README.

**Comment by jorgebucaran** [comment]
If you put Fisher in a directory that is not in your Fish function path, you'll need to autoload it yourself, obviously.
