### ISSUE TITLE
[Feature Request] A proper, declerative way to install plugins

### ISSUE THREAD

**Issue by drishal** [jorgebucaran/fisher#687]
Can a feature be implemented so that one can directly declare the needed plugins in the config.fish file instead of a separate fish_plugin file? Something like how zplug works, (for eg one can declare the pluins using `fisher plug <plugin_name>` and update/install plugins with `fisher update`..then one can also remove the plugin by just deleting the line

**Comment by jorgebucaran** [comment]
That way is the `fish_plugins` file. What don't you like about it?

**Comment by drishal** [comment]
> That way is the `fish_plugins` file. What don't you like about it?

maybe just add a way to simply declare the fish plugins right to config.fish, so one does not need to backup multiple files to the git repository

**Comment by thernstig** [comment]
Does it have any practical sense @drishal? Usually questions like "I want to do it this way because it organizes my files better" bloats software, to accommodate all users. But if there are valid reasons that solves a real problem, I'd say the issue would get better recognition. Backing up multiples files to git is what everyone does, so what is the problem with that?

**Comment by drishal** [comment]
tbh it would be even better to have a variable to set the path of fish_plugins file, so I can directly point it to my dotfiles repo. (I actually document my fish config in Emacs org mode, thats maximum reproducibility would be really great

**Comment by jorgebucaran** [comment]
Your plugins need to be declared somewhere. If that was your `config.fish`, we could get away with just one file, which is nice, but it would come at the cost of mixing it up with other code that we may be running at startup. It'd also be harder to parse than `fish_plguins`, obviously. Or force users to run `fisher` at startup, which may not be desirable for some people.
