### ISSUE TITLE
Installation script blocked

### ISSUE THREAD

**Issue by eliax1996** [jorgebucaran/fisher#688]
After entering in my fish shell the following command: `curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher` the installation script stays locked after displaying the following:
```bash

fisher install version 4.3.0
Fetching https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD

```

It isn't a problem of connection or proxy because launching: `wget https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD` the file is correctly downloaded on my machine.

**Comment by jorgebucaran** [comment]
What version of Fish are you on? Do you have a `.curlrc` or is your curl configured unusually?

**Comment by willrogers** [comment]
I see exactly the same. Fish 3.3.1 installed with Homebrew on MacOS Monterey. No custom Curl configuration. `curl` and `wget` work fine.

**Comment by jorgebucaran** [comment]
Think you can create a Docker image where we can reproduce the problem? 

Works for me. Fish 3.3.1 installed with brew on macOS Monterey, M1 chip.

**Comment by eliax1996** [comment]
> Think you can create a Docker image where we can reproduce the problem?
> 
> Works for me. Fish 3.3.1 installed with brew on macOS Monterey, M1 chip.

Can you suggest me a starting docker image for Monterey? I don't know what image use for start building the docker image.

```docker
FROM ???

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
RUN brew install fish
RUN curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

WORKDIR /root

CMD ["bash"]
```

**Comment by eliax1996** [comment]
Ok, I built a docker image and all seems be working:

```
# syntax=docker/dockerfile:1
FROM homebrew/brew

SHELL ["/bin/bash", "-c"]

RUN brew install fish

SHELL ["/home/linuxbrew/.linuxbrew/bin/fish", "-c"]

RUN curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

WORKDIR /root

CMD ["bash"]
```

if you save it as Dockerfile and then you write: `docker image build -t my-image && docker run -it my-image /home/linuxbrew/.linuxbrew/bin/fish` all seems be working

**Comment by eliax1996** [comment]
Another hint is the following, if I try to exit from the fish session the shell print the following:
```bash
There are still jobs active:

   PID  Command
 39688  fish --command "
                    if test -e $plugin
                        command cp -Rf $plugin/* $source
                    else
                        set temp (command mktemp -d)
                        set name (string split \@ $plugin) || set name[2] HEAD
                        set url https://codeload.github.com/\$name[1]/tar.gz/\$name[2]

                        echo Fetching (set_color --underline)\$url(set_color normal)

                        if curl --silent \$url | tar -xzC \$temp -f - 2>/dev/null
                            command cp -Rf \$temp/*/* $source
                        else
                            echo fisher: Invalid plugin name or host unavailable: \\\"$plugin\\\" >&2
                            command rm -rf $source
                        end
                        command rm -rf \$temp
                    end

                    set files $source/* && string match --quiet --regex -- .+\.fish\\\$ \$files
                " &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.

```

**Comment by jorgebucaran** [comment]
So, it's working as expected inside the container.

**Comment by eliax1996** [comment]
Yes, but I cannot understand what doesn't work in my machine

**Comment by jorgebucaran** [comment]
Let's have a look at your `config.fish`. Can you copy-paste it here? Perhaps something in it causes Fisher to block.

**Comment by eliax1996** [comment]
I don't think can be that, but here's my config file:
```bash
set -x LANG en_US.UTF-8

[ -f /usr/local/share/autojump/autojump.fish ];
source /opt/homebrew/share/autojump/autojump.fish

if status is-interactive
    # Commands to run in interactive sessions can go here
end
```

**Comment by jorgebucaran** [comment]
Did you try commenting out `source /opt/homebrew/share/autojump/autojump.fish`? And if not, could you?

**Comment by eliax1996** [comment]
I'll try right now and update you

**Comment by eliax1996** [comment]
nope, commented, saved, opened another session and the result is always the same.

**Comment by jorgebucaran** [comment]
What terminal are you using? Do you also happen to have any Fish scripts running in the background?

**Comment by eliax1996** [comment]
I use `iTerm2 3.4.13 (OS 10.14+)`, regarding the background running script the output of the `ps` command is the following:
```bash
@ ps -A | grep fish
36470 ttys001    0:00.03 fish (figterm)
36473 ttys002    0:00.12 /opt/homebrew/Cellar/fish/3.3.1/bin/fish --login
36543 ttys002    0:00.00 grep --color=auto fish
```

**Comment by willrogers** [comment]
Might it be fig? I am also running fig.

**Comment by eliax1996** [comment]
No, tried to kill fig and install it again but the problem is present even if fig isn’t running

**Comment by jorgebucaran** [comment]
Could you try again on macOS Terminal?

**Comment by eliax1996** [comment]
Tried right now, always the same, locked on:
```bash

@ curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install version 4.3.0
Fetching https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD



```

**Comment by jorgebucaran** [comment]
Sorry, I'm out of ideas.

**Comment by eliax1996** [comment]
Ahahah mee too. Do you want that I close the issue or we leave it open until someone will (maybe) realise how to fix it?

**Comment by jorgebucaran** [comment]
Let's leave it open then! 👍

**Comment by willrogers** [comment]
I just uninstalled fig and then fisher works as expected.

**Comment by jorgebucaran** [comment]
What is Fig?

**Comment by willrogers** [comment]
https://fig.io/

**Comment by willrogers** [comment]
I reinstalled Fig. It does not seem to have modified my Fish configuration files in my home directory.

`fisher update` is blocking again.

I will uninstall Fig again, I don't seem to get much benefit from it.

**Comment by jorgebucaran** [comment]
I'll give Fig a try and see if I can find out what's going on.

**Comment by jorgebucaran** [comment]
Are you using Fig too?

**Comment by roddc** [comment]
> Are you using Fig too?

No

**Comment by jorgebucaran** [comment]
Can you reproduce the issue inside a container? L

**Comment by jorgebucaran** [comment]
Can you reproduce the issue inside a container?

**Comment by eliax1996** [comment]
Try to launch in local the instructions that I have written up they contains the source of the   Docker image and how to launch it to verify if the installer works well

**Comment by dideler** [comment]
So I just ran into this as well. Installed fig a few days ago. First noticed issues with fish in the VSCode terminal after installing fig, a newly opened terminal would not have a clean prompt. Then with fish-spin, the `spin "sleep 1"` command would give me an infinite spinner with a hanging process in the background. Then with `fisher update` which would silently hang.

Uninstall fig after seeing @willrogers's comment and everything works again :)

**Comment by eliax1996** [comment]
I tried again and now the script works, I don't know why...

**Comment by jorgebucaran** [comment]
It seems like this has been fixed upstream! 🎉
