### ISSUE TITLE
Add a man page

### ISSUE THREAD

**Issue by KeithScheiwiller** [jorgebucaran/fisher#691]
It looks like there was a man page at one point but it was maybe removed?
I know fisher aims to be zero-conf and simple, but it's always causes some discomfort when _any_ package doesn't include even a really brief man page.
For example, I had initially shied away from fisher because I didn't like it installing things directly into my .config/fish directory. I see there is now a `$fisher_path` variable for this, but unless you come here or read the installed sources you'd never know it exists.

**Comment by jorgebucaran** [comment]
We could improve `fisher --help` too. What did you have in mind?

**Comment by jorgebucaran** [comment]
Just added information about `$fisher_path` to `fisher -h`. Hopefully, this makes things a bit nicer.
