### ISSUE TITLE
Fisher not working behind proxy

### ISSUE THREAD

**Issue by zbindenren** [jorgebucaran/fisher#692]
Hi

At on a system of mine fisher does not work, but if I execute the related commands manually it works:

```
❯ fisher install jethrokuan/fzf
fisher install version 4.3.0
Fetching https://codeload.github.com/jethrokuan/fzf/tar.gz/HEAD
fisher: Invalid plugin name or host unavailable: "jethrokuan/fzf"

user on hostname ~ 
[🔴 ERROR] ❯ set temp (command mktemp -d)

user on hostname ~ 
❯ set url https://codeload.github.com/jethrokuan/fzf/tar.gz/HEAD

user on hostname ~ 
❯ curl --silent $url | tar -xzC $temp -f -

user on hostname ~ 
❯ 
```

In your script you prefix `$url` and `$temp` with `\`. If I do that it does not work. Releated script:

```
if curl --silent \$url | tar -xzC \$temp -f - 2>/dev/null
    command cp -Rf \$temp/*/* $source
else
    echo fisher: Invalid plugin name or host unavailable: \\\"$plugin\\\" >&2
    command rm -rf $source
end
```

**Comment by jorgebucaran** [comment]
Ping @zbindenren 👋

**Comment by zbindenren** [comment]
Sorry for the late answer. I can create a PR with the `\` removed. But I wonder why they are there in the firstplace (I am not a fish specialist).

**Comment by jorgebucaran** [comment]
Escaping, since that code is inside double quotes.

**Comment by zbindenren** [comment]
It was a proxy miss configuration. To debug I hat to remove --silent. It is working now.

**Comment by jorgebucaran** [comment]
Good to know! Thanks, @zbindenren.
