### ISSUE TITLE
git.io/fisher returning heroku "Application Error"

### ISSUE THREAD

**Issue by jamiewildehk** [jorgebucaran/fisher#693]
Installation is blocked as git.io/fisher is down
<img width="620" alt="image" src="https://user-images.githubusercontent.com/2277177/147092830-85845a49-7a9d-4585-a37f-cea30edcbcc8.png">

Wish I had known this before I removed v3 :(

**Comment by jamiewildehk** [comment]
ok, googling suggests that heroku is down and that I should check HN before opening an issue. :)

**Comment by jorgebucaran** [comment]
You are right, it's down! 🤦‍♂️

I'll be monitoring this.
