### ISSUE TITLE
fisher plugin names should be case insensitive

### ISSUE THREAD

**Issue by PatrickF1** [jorgebucaran/fisher#694]
One problem I noticed is that fisher treats IlanCosman/tide and ilancosman/tide differently. If I change the casing, even though GitHub treats the two urls exactly the same (all user/repo combos are case insensitive as far as I can tell), fisher will think it's a new plugin and uninstall one and try to install the other. Perhaps fisher should treat GitHub plugins case insensitively?

**Comment by jorgebucaran** [comment]
Agreed. Should be an easy task with our friend the `string` builtin.

**Comment by jorgebucaran** [comment]
Since https://github.com/jorgebucaran/fisher/issues/624 Fisher can't install a plugin that would make it overwrite existing user files. So, trying to install `IlanCosman/tide` when `ilancosman/tide` is already installed will fail now.
