### ISSUE TITLE
Add link of home-brew formula Fischer to README

### ISSUE THREAD

**Issue by Anselmoo** [jorgebucaran/fisher#696]
Add link of home-brew formula Fischer to README

[https://formulae.brew.sh/formula/fisher](https://formulae.brew.sh/formula/fisher)

**Comment by jorgebucaran** [comment]
Hi @Anselmoo, thanks! Could you walk me through the formula? Where does Fisher get installed exactly?

**Comment by Anselmoo** [comment]
@jorgebucaran thx for the feedback! To be sure, I didn't develop the bottle, so I assume:

1. Download the latest release and compare `sha256`
2. Copy the two `fisher.fish` to dir
3. Make a test in `env`

[fisher.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fisher.rb)

In summary, I thoughts it might help to conclude README??

```ruby
class Fisher < Formula
  desc "Plugin manager for the Fish shell"
  homepage "https://github.com/jorgebucaran/fisher"
  url "https://github.com/jorgebucaran/fisher/archive/4.3.1.tar.gz"
  sha256 "be4313076a57d05fe2e49a7bd1c2fa8fa2f041af837a31974cd1d8d1f397bf29"
  license "MIT"

  bottle do
    sha256 cellar: :any_skip_relocation, all: "06b0c91b96b21c90c38022f9365a72e2c6fcbfe544cdb4c46f43b347df750bbd"
  end

  depends_on "fish"

  def install
    fish_function.install "functions/fisher.fish"
    fish_completion.install "completions/fisher.fish"
  end

  test do
    system "#{Formula["fish"].bin}/fish", "-c", "fisher install jethrokuan/z"
    assert_equal File.read(testpath/".config/fish/fish_plugins"), "jethrokuan/z\n"
  end
end
```

**Comment by jorgebucaran** [comment]
Thanks @Anselmoo. Do you have any idea where (what directory) Fisher would get installed by this?

**Comment by Anselmoo** [comment]
> Thanks @Anselmoo. Do you have any idea where (what directory) Fisher would get installed by this?

```shell
/usr/local/share/fish/vendor_completions.d
/usr/local/share/fish/vendor_functions.d
```

Which links to `\loca\lCellar\fisher` but plugins are located at `.config`

**Comment by jorgebucaran** [comment]
Hmm, wouldn't that affect Fisher self-update during `fisher update`? I need to try this setup. 

@Anselmoo Have you had any issues?

**Comment by Anselmoo** [comment]
No, it's fine, it looks like that after `fisher update`, it updates regularly. Just `fisher` will be updated by `brew`.

**Comment by jorgebucaran** [comment]
Fisher will self-update every time you `fisher update`.

**Comment by Anselmoo** [comment]
Ic, therefore `fisher.fish `will come back to `~.config/fish`. If the homebrew formula is not matching, close the PR and issue

**Comment by jorgebucaran** [comment]
There's a similar situation with the arch package, Pacman puts it in a similar location, but then `fisher update` self-updates and puts Fisher files in your `$fisher_path`.
