### ISSUE TITLE
fisher list should have a little description of the plugins

### ISSUE THREAD

**Issue by zim0369** [jorgebucaran/fisher#698]
I really don't remember what a plugin does just by looking at it's name so a
little description with fisher list would be really nice.

Make it a different color tho.

Thanks btw. I love fisher. I'm a fisher myself ; )

**Comment by jorgebucaran** [comment]
Plugin publishers don't have a way to include metadata with plugins. It used to be possible, but not anymore.

**Comment by zim0369** [comment]
Well, would be nice if they're able to add a limited characters metadata. Would
be very convenient you know.

**Comment by jorgebucaran** [comment]
That would probably work via a meta file a-la package.json. We had something only remotely similar in the now defunct fishfile. We moved away from that to keep everything simple.

**Comment by jorgebucaran** [comment]
I don't want to add this functionality to Fisher at this time. Implementing this is an invitation for complications.
