### ISSUE TITLE
fisher uses a seemingly undocumented github api endpoint

### ISSUE THREAD

**Issue by anakimluke** [jorgebucaran/fisher#699]
Fisher makes a request to `codeload.github.com` to retrieve the tarball of the desired plugin. Upon research(basically googling for `+"codeload.github.com" +site:docs.github.com`), I couldn't find proper documentation for this endpoint.

As there are no guarantees this will work indefinitely or that I'll have consistent behavior, I suggest moving to the well-documented rest api. Then I'd also feel more comfortable with advanced usage of the api, such as the ability to specify a "tag, branch, or commit". 

Relevant section: https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-tar

**Comment by jorgebucaran** [comment]
That makes a lot of sense @anakimluke, thank you for digging that up. Is this something you'd like to work on? Migrating the endpoints and making sure it still gives us what Fisher needs.

**Comment by jorgebucaran** [comment]
Thank you, @anakimluke! I'll include this in the next release. 🎉
