### ISSUE TITLE
Can't install fisher

### ISSUE THREAD

**Issue by JiantingFeng** [jorgebucaran/fisher#701]
Hi, I have an issue installing fisher.
The command `curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher` doesn't work.
<img width="762" alt="Screen Shot 2022-01-23 at 9 40 31 PM" src="https://user-images.githubusercontent.com/36693163/150681268-6809d7bc-5c0d-434d-b8c5-213b561dccac.png">
My fish is the latest version and I'm using Mac OS 12 on MacBook Pro.

**Comment by madeleinerandall** [comment]
I have the same issue, 
```
source: not enough arguments
(23) Failed writing body
```

**Comment by jorgebucaran** [comment]
Is the git.io URL down?

**Comment by jorgebucaran** [comment]
The git.io URL seems fine. This must be a local issue with your curl. Got a curlrc file? Do you have a custom curl function?

**Comment by JiantingFeng** [comment]
> The git.io URL seems fine. This must be a local issue with your curl. Got a curlrc file? Do you have a custom curl function?

Hi, I solved the problem. Maybe because of the GFW(Great Fire Wall) in China, the short URL you provided in `curl -sL https://git.io/fisher | source` doesn't work, and I replace the short URL with the original: https://raw.githubusercontent.com/jorgebucaran/fisher/HEAD/functions/fisher.fish, this problem is solved.

Again. thank you for your reply!

**Comment by khwerhahn** [comment]
I have the same problem. Monterey 12.1. MacBook Pro. 
```
source: not enough arguments
```

**Comment by jorgebucaran** [comment]
Are you using the latest Fish?

**Comment by khwerhahn** [comment]
Trying to install it on a fresh mac.

**Comment by jorgebucaran** [comment]
You must install Fish first in order to use Fisher.

**Comment by khwerhahn** [comment]
I have installed fish via brew already.

**Comment by jorgebucaran** [comment]
What version of Fish?

**Comment by hxl1116** [comment]
Hi, I'm having the same `source: not enough arguments` issue. I have Fish 3.3.1 installed and I've tried replacing the short URL with the original one as well.

**Comment by hxl1116** [comment]
> Hi, I'm having the same `source: not enough arguments` issue. I have Fish 3.3.1 installed and I've tried replacing the short URL with the original one as well.

Nevermind, I ran the install command you provided within the Fish shell and it worked!

**Comment by jorgebucaran** [comment]
Yes. It must be run from Fish.

**Comment by Preet-Sojitra** [comment]
> Hi, I have an issue installing fisher. The command `curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher` doesn't work. <img alt="Screen Shot 2022-01-23 at 9 40 31 PM" width="762" src="https://user-images.githubusercontent.com/36693163/150681268-6809d7bc-5c0d-434d-b8c5-213b561dccac.png"> My fish is the latest version and I'm using Mac OS 12 on MacBook Pro.

I am facing same issue in my ubuntu 22.04. I am using fish 3.6.1. Any ways to solve this?

**Comment by jorgebucaran** [comment]
Up-to-date instructions are listed in the README:

```console
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
```

If that's not functioning properly, there might be an issue with `curl`. Do you happen to have a `.curlrc` file?

**Comment by Preet-Sojitra** [comment]
> Up-to-date instructions are listed in the README:
> 
> ```
> curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
> ```
> 
> If that's not functioning properly, there might be an issue with `curl`. Do you happen to have a `.curlrc` file?

It seems I don't have a `.curlrc` file. Can u guide me or share some resources about where to create one and what content to put inside it.

**Comment by jorgebucaran** [comment]
You don't require a `.curlrc` file. If that still doesn't work for you, just move [this file](https://github.com/jorgebucaran/fisher/blob/main/functions/fisher.fish) to your `~/.config/fish/functions` and start a new shell. That should do the trick.

**Comment by jorgebucaran** [comment]
You don't need a `.curlrc` file. Download [this file](https://github.com/jorgebucaran/fisher/blob/main/functions/fisher.fish) somewhere and then run:

```
source somewhere/to/fisher.fish && fisher install jorgebucaran/fisher
```

And you're good to go.
