### ISSUE TITLE
Autocompletions don't work when passing variables on the command line

### ISSUE THREAD

**Issue by alexrutar** [jorgebucaran/fisher#703]
Autocompletions don't work when, (for example) manually specifying `$fisher_path`:
```
fisher_path=/some/nice/path fisher [TAB]
```
does not offer the usual options.

This should be easy to fix: the [fish completion tutorial](https://fishshell.com/docs/current/completions.html) seems to suggest something like `set --local fisher_subcommands install update remove list` and then using
```
not __fish_seen_subcommand_from $fisher_subcommands
```
as the condition, instead of `__fish_use_subcommand`.

However, I am inclined to see this as an upstream issue with [`__fish_use_subcommand`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_use_subcommand.fish).

**Comment by jorgebucaran** [comment]
I'm keen on fixing this for our use-case here this time. Nice catch!

**Comment by alexrutar** [comment]
I'm not sure if this is the fix you necessarily want, but for convenience I've added this pull request with what I stated in the first comment!

**Comment by jorgebucaran** [comment]
Welp, can't reproduce this issue. Fisher completions work just fine.

<img width="1496" alt="スクリーンショット 2022-04-12 20 31 40" src="https://user-images.githubusercontent.com/56996/163071017-5892179f-8540-4b73-ba88-22e7f7b42a76.png">
<img width="1496" alt="スクリーンショット 2022-04-12 20 32 46" src="https://user-images.githubusercontent.com/56996/163071104-050f1dde-629b-4a75-9f61-e1e7a8555922.png">

**Comment by alexrutar** [comment]
Tested it too on my device, looks like fish has fixed the upstream issue. Thanks!
