### ISSUE TITLE
[Suggestion] Install plugins to seperate directories

### ISSUE THREAD

**Issue by NextAlone** [jorgebucaran/fisher#709]
Such ad install a plugin with struct below
```
functions/foo.fish
completions/foo.fish
```

Install these to fisher dir with this struct, create a dir with plugin name
```
~/.config/fish/functions/foo/foo.fish
~/.config/fish/completions/foo/foo.fish
```

**Comment by jorgebucaran** [comment]
I don't understand what you are saying.

**Comment by jorgebucaran** [comment]
No can do, I'm afraid that would make it harder to autoload functions and completions on startup.
