### ISSUE TITLE
`git.io` redirections will stop on April 29th, 2022

### ISSUE THREAD

**Issue by joseluisq** [jorgebucaran/fisher#712]
Recently I was advised about [Github is going to stop `git.io` redirections](https://github.blog/changelog/2022-04-25-git-io-deprecation/) next Friday.
After that, urls like `git.io/fisher` should not work anymore. 

So it should be necessary for the project to opt for another solution.

**Comment by jorgebucaran** [comment]
Ay, caramba! Okay, let's default to use the long URL instead.

**Comment by fosemberg** [comment]
Could you type this
> long URL

? :)

**Comment by fosemberg** [comment]
okay, i find it :)
```
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
```

**Comment by fosemberg** [comment]
done PR:
https://github.com/jorgebucaran/fisher/pull/713

**Comment by joseluisq** [comment]
Looks like Github has taken the proper approach rather than just kill a wide-used service.

> **2022-04-27 Update:**
> While the git.io url redirection service is [read-only](https://github.blog/2011-11-10-git-io-github-url-shortener/) and use of the service is limited, we have received feedback from developers and academic researchers who have published git.io links in print documentation and research papers. In order to preserve the integrity of these historical documents, we have decided to archive the current git.io links in a new read-only service that will allow us to serve redirects for those links longer term.
> 
> As we continue our analysis, we may remove individual links that point to spammy, malicious or 404 links. Our goal is to not break links relied on for legitimate use, especially by the academic community, while preserving the security of developers on GitHub.
> 
> That said, we still encourage users to make use of one of the many URL shortening services available with greater functionality than the git.io service provided. GitHub support will not be able to update or edit redirection records served by the git.io archive service.

**Comment by joseluisq** [comment]
Since https://github.com/jorgebucaran/fisher/pull/713 is done, I close this issue.

**Comment by jorgebucaran** [comment]
> we have decided to archive the current git.io links in a new read-only service 

In light of this, methinks it would be harmless to go back to the more memorable https://git.io/fisher. Objections? 🤓
