### ISSUE TITLE
Can't install fisher or any plugin (WSL) (curl ?)

### ISSUE THREAD

**Issue by Vincent-HD** [jorgebucaran/fisher#718]
Fish version: `3.4.1`
Curl version: `7.81.0 (x86_64-pc-linux-gnu)`
OS: `Ubuntu 22.04 LTS`
Via WSL 2 using this tarball: [Ubuntu tar gz file](https://partner-images.canonical.com/oci/jammy/current/ubuntu-jammy-oci-amd64-root.tar.gz) from this [link](https://partner-images.canonical.com/oci/) found on this [repo](https://github.com/tianon/docker-brew-ubuntu-core)

Error: `fisher: Invalid plugin name or host unavailable: "IlanCosman/tide@v5"` when running fisher install cmd `fisher install IlanCosman/tide@v5`

Same during the installation process:
```
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher: Invalid plugin name or host unavailable: "jorgebucaran/fisher"
```

I have no curlrc file or any custom configuration, it's a brand new WSL install, just installed curl wget etc ...

A weird file appeared in cwd after running the command which seems to be the output of curl:
`''$'\001\020''3@pu'$'\001''@8'$'\r''@'$'\036\035\006\004''@@@'$'\357\277\275\002\357\277\275\002\b\003\004\030\003\030\003\030\003\034\034\001\001\004\357\277\275\037\357\277\275\037\020\001\005'`

I tried two times, I'll try with another tarball

**Comment by StewartThomson** [comment]
I am also seeing this on Ubuntu 18.04

Fish version: 3.3.1
Curl version: 7.58.0 (x86_64-pc-linux-gnu)
OS: Ubuntu 18.04 LTS

```
fisher install jorgebucaran/nvm.fish

fisher install version 4.3.0
Fetching https://codeload.github.com/jorgebucaran/nvm.fish/tar.gz/HEAD
fisher: Invalid plugin name or host unavailable: "jorgebucaran/nvm.fish"
```

Something similar is also happening to the plugin itself

```
nvm use 17

curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
nvm: invalid mirror index -- is "https://nodejs.org/dist" a valid host?
```

**Comment by chvolkmann** [comment]
This seems to be related to WSL, see [microsoft/vscode-remote-release#1856](https://github.com/microsoft/vscode-remote-release/issues/1856).

In my case, the described workaround worked. The `gzip` binary on WSL seem to be faulty.

So either [patch it directly](https://github.com/microsoft/WSL/issues/4461#issuecomment-1132360882)
```bash
echo -en '\x10' | sudo dd of=/usr/bin/gzip count=1 bs=1 conv=notrunc seek=$((0x189))
```

or [install a proper version](https://github.com/microsoft/WSL/issues/4461#issuecomment-547491959)
```bash
wget http://ftp.debian.org/debian/pool/main/g/gzip/gzip_1.12-1_amd64.deb   
sudo dpkg -i ./gzip_1.12-1_arm64.deb
```

**Comment by jorgebucaran** [comment]
Thank you, @chvolkmann. 🙌

**Comment by milhauzindahauz** [comment]
Faced the similar issue. I had to patch the script to use **wget**. I purpose to add a switch to use wget instead of the curl.

Should I create new issue for this?

**Comment by jorgebucaran** [comment]
Alternatively, could you install curl on your device, no?
