### ISSUE TITLE
Can't install fisher on kitty terminal

### ISSUE THREAD

**Issue by federicotorrielli** [jorgebucaran/fisher#720]
As title. It happens only on kitty terminal. When I run the script, it's stuck there and it does not move or terminate.

**Comment by jorgebucaran** [comment]
Can't repro on macOS 12.4 with kitty 0.25.2. Everything worked as it should. 

![](https://user-images.githubusercontent.com/56996/174446175-eec772e9-1ed8-449c-a1e9-4318cfd2eae3.jpg)

**Comment by federicotorrielli** [comment]
I'm on Pop_OS 22.04 and it gets stuck every time

**Comment by jorgebucaran** [comment]
Maybe it's something in your config.fish that you should only run in interactive mode. Can you post your config here?

**Comment by federicotorrielli** [comment]
![image](https://user-images.githubusercontent.com/31370059/174796876-c2ac0bc7-8fc7-452a-bd02-7ac0c4d7ba2b.png)

**Comment by jorgebucaran** [comment]
Run that pokemon script and initializing zoxide only when interactive. 

```
if status is-interactive
  # ...
end
```

**Comment by jorgebucaran** [comment]
Run that pokemon script and initializing zoxide only when interactive. 

```fish
if status is-interactive
  # ...
end
```

**Comment by federicotorrielli** [comment]
My bad, now it works! Thanks a lot.
