### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by justinbalaguer** [jorgebucaran/fisher#721]
```
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
```

why does this output
```
bash: source: filename argument required
source: usage: source filename [arguments]
```

works perfectly on wsl but on my ubuntu laptop it shows that error.

**Comment by jorgebucaran** [comment]
Are you running that in bash or Fish?

**Comment by justinbalaguer** [comment]
forgot to close this. It's working apparently after restarting 🤷‍♂️😅

**Comment by jorgebucaran** [comment]
Restarting had nothing to do with it. You can't install Fisher from bash.
