### ISSUE TITLE
7c4024da667a889c7b4e2146040324f763c33c86 breaks local plugins on case-sensitive filesystems

### ISSUE THREAD

**Issue by nathanchance** [jorgebucaran/fisher#723]
After 7c4024da667a889c7b4e2146040324f763c33c86, I can no longer install a local plugin that has a capital letter in the path, as `test -e $plugin` will always fail and attempt to download the plugin from GitHub.

```
$ fisher install $HOME/Dev/github/env/fish
fisher install version 4.4.2
Fetching https://api.github.com/repos//home/nathan/dev/github/env/fish/tarball/HEAD
fisher: Invalid plugin name or host unavailable: "/home/nathan/dev/github/env/fish"
```

**Comment by jorgebucaran** [comment]
Thanks for the bug report! I think I just fixed it. Please update and try again. 🙏

**Comment by nathanchance** [comment]
Looks good to me, thank you a lot for the quick response and fix!
