### ISSUE TITLE
Fisher hanging whilst installing

### ISSUE THREAD

**Issue by faesel** [jorgebucaran/fisher#724]
Fisher seems to hang for me when im trying to install it using the command
```
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
```
i just get `fisher install version 4.4.2` appear on my console window and nothing else.

I'm running ubuntu 22.04, with fish version 3.5.0, please help

**Comment by faesel** [comment]
Thanks for replying, my config  is mostly empty, ive just done a clean install. 
```
set -g -x fish_greeting 'Greetings Faesel'
ssh-add ~/.ssh/id_rsa
```

**Comment by jorgebucaran** [comment]
What happens if you comment everything out? Still hung?

**Comment by faesel** [comment]
Ha! that worked thank you so much!
