### ISSUE TITLE
Check requirements and give hint what is missing

### ISSUE THREAD

**Issue by rominf** [jorgebucaran/fisher#728]
I propose to check requirements (`curl`, `gzip`, `tar`, ?) and give a hint what is missing. I've figured out about `curl` and `tar` quite quickly. However, it took a few minutes to understand that `gzip` was missing since the error message was wrong (`fisher: Invalid plugin name or host unavailable: "jorgebucaran/fisher"`) and stderr was redirected to `/dev/null`.

**Comment by jorgebucaran** [comment]
We do require `curl` and `tar`, so checking if those exist prior to using them is a great suggestion, thanks!

We no longer use `gzip`, though, so you must be running an old version of Fisher. 🤓

**Comment by rominf** [comment]
I've followed the instructions just today. Here is the line copied from the bootstrap script with redirection to `/dev/null` deleted.

```
rominf@tumbleweed /tmp> curl --silent -L https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD | tar -xzC tmp -f -
tar (grandchild): gzip: Cannot exec: No such file or directory
tar (grandchild): Error is not recoverable: exiting now
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
```

**Comment by jorgebucaran** [comment]
I don't know what instructions or bootstrap script you are referring to, but those aren't Fisher installation instructions.

To install Fisher see: https://github.com/jorgebucaran/fisher#installation

**Comment by jorgebucaran** [comment]
I wouldn't expect this code to work while inside the `tmp` directory. 

```console
rominf@tumbleweed /tmp> curl .../tarball/HEAD | tar -xzC tmp -f -
```
