### ISSUE TITLE
M1 Mac zsh fails install

### ISSUE THREAD

**Issue by ktwbc** [jorgebucaran/fisher#729]
Install command provided on home page:
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

results in:

source: not enough arguments

**Comment by jorgebucaran** [comment]
The installation instructions are only for Fish, not zsh (or any other shell).

**Comment by ktwbc** [comment]
Yes, fish is installed:

```
~ brew install fish
Warning: fish 3.5.1 is already installed and up-to-date.
To reinstall 3.5.1, run:
  brew reinstall fish
➜  ~ fish -v
fish, version 3.5.1
➜  ~ curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
source: not enough arguments
➜  ~
```

**Comment by jorgebucaran** [comment]
Did you run the installation command from Fish or zsh? 

And why did you write zsh in the title of this issue? What does this have to do with zsh?

**Comment by ktwbc** [comment]
I've just been trying to follow directions on https://sebastiancarlos.medium.com/youre-missing-out-on-the-best-terminal-experience-36a7aeecc6de and installing about four new pieces of software, all of which have one-line installs with little information when the one-liner doesn't work, and I got as far as Tide which needs fisher which led me to trying to install this. I mentioned the shell because that's the tutorial I'm in and I don't know what's relevant and not at this point.  Just trying to figure out a bunch of new stuff.

**Comment by jorgebucaran** [comment]
Gotcha! 👍 

When you run the installation command from zsh, it fails because zsh doesn't understand Fish syntax, which is what the installation command is written in. 

Set Fish as your default shell first, see: <https://fishshell.com/docs/current/#default-shell>. 

Then start a new Fish shell session and [install Fisher as usual](https://github.com/jorgebucaran/fisher#installation).

**Comment by ktwbc** [comment]
Awesome! Brew actually changed locations with the M1 mac and MacOS update so the commands worked as

```
echo /opt/homebrew/bin/fish | sudo tee -a /etc/shells
chsh -s /opt/homebrew/bin/fish
```

but that did work. Thank you for your help!

**Comment by jorgebucaran** [comment]
My pleasure. 🙇‍♂️
