### ISSUE TITLE
Unable to install plugins from Git URL

### ISSUE THREAD

**Issue by yonkeltron** [jorgebucaran/fisher#732]
Hi,

I am a huge fan of Fisher and looking to use it even more. In trying to adopt it, I have noticed that I'm unable to install plugins from private Git hosts, even when providing a full Git URL. For example, my company has a private git host but the following command yields an error:

```fish
❯ fisher install https://private.git.host/project/plugin
Fetching https://api.github.com/repos/https://private.git.host/project/plugin/tarball/HEAD
fisher: Invalid plugin name or host unavailable: "https://private.git.host/project/plugin"
```

Some crucial info about my environment, since I am running macOS Monterey (12.5):

```fish
❯ fish --version
fish, version 3.5.1
❯ fisher --version
fisher, version 4.4.2
```

If there is any other info I can provide, please let me know. Also happy to test any fixes or some such! Thanks so much for all your hard work, and I look forward to your reply.

Thanks,
+Jonathan

**Comment by jorgebucaran** [comment]
Hi @yonkeltron, unfortunately, we don't support that anymore. We had some (poor) support for this a few years ago, but it was laboriously tricky to implement, so I ended up removing it in Fisher 4. I'm not against giving it another shot if done properly this time.
