### ISSUE TITLE
fisher install "fisher: command not found"

### ISSUE THREAD

**Issue by rolandweibel** [jorgebucaran/fisher#734]
Trying to install on Ubuntu on Windows Subsystem for linux. I have fish set as my prompt, and when I execute:
`curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher `
I get:
`fisher: command not found `

I can manually get the fisher command with:
`wget git.io/fisher --no-check-certificate `

And then source the fisher script downloaded:
`. fisher`
Then I can issue:
`fisher install jorgebucaran/fisher`
and I get the following error, "Fetching https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD                                                  fisher: Invalid plugin name or host unavailable: "jorgebucaran/fisher" "

Opening up fisher, I notice we're getting a tar file from the above url, so again I issue:
`wget https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD --no-check-certificate`

And I get HEAD, which is a tarred file, so:
`tar -xvf HEAD`
untars the file. And I can fisher install by relative path
`fisher install jorgebucaran-fisher-d431f45/ `
and it looks like success:
"Installing /home/roland/jorgebucaran-fisher-d431f45                                                                                /home/roland/.config/fish/functions/fisher.fish                                                                         /home/roland/.config/fish/completions/fisher.fish "

`fisher install pure-fish/
[pure](https://github.com/pure-fish/pure)`

Fetching https://api.github.com/repos/pure-fish/pure/tarball/HEAD                                                       fisher: Invalid plugin name or host unavailable: "pure-fish/pure"

You're starting to get the idea. I can continue and download the tarred pure-fish and install manually.

Maybe --no-check-certificates or its equivalent needs to be added to curl?

**Comment by jorgebucaran** [comment]
Does adding that flag fix the issue you had? Want to send me a PR?

**Comment by rolandweibel** [comment]
Yes, you need to add the --insecure flag to the curl call. That should fix the issue. I'm not sure how to create a PR, but I have changes on a local branch.

**Comment by 2-4601** [comment]
Maybe not a good idea to disable certificate checks for all users.

Do you have CA certificates installed properly in WSL or does your network require a custom certificate?

**Comment by jorgebucaran** [comment]
See also https://github.com/jorgebucaran/fisher/pull/735#issuecomment-1237796339
