### ISSUE TITLE
fisher is using fish incompatible commands?

### ISSUE THREAD

**Issue by JeremyCaron** [jorgebucaran/fisher#736]
I can't get fisher to run, every time I try, I get this (complaining about the double pipes):

> Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
~/.config/fish/functions/fisher.fish (line 2):     set --query fisher_path || set --local fisher_path $__fish_config_dir
>                                                                            ^
from sourcing file ~/.config/fish/functions/fisher.fish
        called on standard input
in command substitution
        called on standard input
source: Error while reading file “/home/jeremy/.config/fish/functions/fisher.fish”

For what it's worth I get the same complaint about the && in the install command when running it in fish.  

> curl -sL https://git.io/fisher --insecure | source && fisher install jorgebucaran/fisher

Please help, what am I doing wrong?

**Comment by jorgebucaran** [comment]
Hey @JeremyCaron! Fish version?

**Comment by JeremyCaron** [comment]
Hey! 2.4.0 @jorgebucaran 

Happen to be in Debian in WSL2 on Win 10 in case it matter.

**Comment by jorgebucaran** [comment]
Ah, just upgrade to Fish >=3.

I should also update the README to indicate system requirements. 😅

**Comment by JeremyCaron** [comment]
Ah, thanks!!

**Comment by JeremyCaron** [comment]
The cause of my outdatedness, for anyone else who might find this, was a result of installing Debian in WSL2 the wrong way, which resulted in Debian 9 being installed.  Apparently you need to get distros from the app store and not the command line, who knew :(

More info here: https://superuser.com/questions/1722935/wsl-debian-is-still-on-oldoldstable-any-way-to-get-latest

**Comment by jorgebucaran** [comment]
Thank you for sharing! Good to know. 👍
