### ISSUE TITLE
fisher: Plugin not installed message after removing a plugin

### ISSUE THREAD

**Issue by guilhermedeandrade** [jorgebucaran/fisher#739]
I realized that after removing a plugin installed with `fisher` the message `fisher: Plugin not installed: "{plugin-name}"`is displayed.

```sh
~/.c/fish | 1 ❱ fisher ls
jorgebucaran/fisher
jethrokuan/z
jorgebucaran/autopair.fish
danhper/fish-ssh-agent
jorgebucaran/hydro
catppuccin/fish
~/.c/fish ❱ fisher remove catppucin/fish
fisher: Plugin not installed: "catppucin/fish"
```

Is this the expected behavior?

**Comment by jorgebucaran** [comment]
Hmmm sounds like you might've wound up in an illogical state. Perhaps you upgraded from an ancient Fisher version or mucked with Fisher state? What else can you share?

**Comment by jorgebucaran** [comment]
Perhaps you upgraded from an ancient Fisher version or mucked with Fisher state? What else can you share?

**Comment by guilhermedeandrade** [comment]
Sorry for the late reply! I was indeed in a weird state. After reinstalling `fisher` everything started to behave as expected.

**Comment by jorgebucaran** [comment]
No worries! 👍
