### ISSUE TITLE
Committing plugin source files (completions, conf.d, functions, themes) is not supported

### ISSUE THREAD

**Issue by charego** [jorgebucaran/fisher#741]
I would like to track not only the list of plugins (`fish_plugins` file) but also the source code of those plugins, for a few reasons. Typically when you run "fisher update" you don't know if anything changed in your plugins. Tracking the files in git makes it easier to review changes after you pull them in, and commit them to your dotfiles once you "approve" them. Secondly, it makes provisioning a new machine easier because you don't need to install Fisher manually, the code is already in your dotfiles.

The problem emerges when you want to run "fisher update" because the universal variables expected by Fisher are missing (I would prefer not to track the `fish_variables` file). Rather than suggest a duplicate of https://github.com/jorgebucaran/fisher/issues/611 ("Fisher should stop using universal variables for plugin state"), I wonder if it would be possible for Fisher to create the universal variables on startup if they don't exist?

```fish
if ! set --query _fisher_plugins
    # setup the Fisher universal variables by inspecting fish_plugins, etc.
end
```

Here is a minimal example: https://git.sr.ht/~crg/fishy

```
> docker container run --rm -it fishy
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@59bd29f2ca3c /# fisher update
fisher update version 4.4.3
Fetching https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD
Fetching https://api.github.com/repos/jorgebucaran/replay.fish/tarball/HEAD
fisher: Cannot install "jorgebucaran/fisher": please remove or move conflicting files first:
        /root/.config/fish/functions/fisher.fish
        /root/.config/fish/completions/fisher.fish
fisher: Cannot install "jorgebucaran/replay.fish": please remove or move conflicting files first:
        /root/.config/fish/functions/replay.fish
        /root/.config/fish/completions/replay.fish
```

**Comment by jorgebucaran** [comment]
> I wonder if it would be possible for Fisher to create the universal variables on startup if they don't exist?

Maybe, why not. Would you like to send me PR with a fix that works for you?

**Comment by jorgebucaran** [comment]
I have been addressing and investigating issues all weekend, so I am taking a break for now. However, I wanted to let you know that I will certainly look into this matter soon and will incorporate this change (or a similar one, as I'm not certain this will be merged as is) before Fisher 5. This should occur in the not-too-distant future.

**Comment by arkag** [comment]
I'm not exactly sure if this is the same issue I'm dealing with, but I would like the ability to ensure that when I switch to a new computer, I can run `fisher update` without getting errors because the files from my plugins already exist. 

An alternative idea would be to enable specifying locations to put plugin files so that I can deliberately avoid sourcing `$__fish_config_dir/functions/fisher` or something.

**Comment by jorgebucaran** [comment]
How did files from your plugins end up on the new machine?

**Comment by arkag** [comment]
I've had them committed to my dotfiles repo for a while now. I can
definitely remove them manually and ignore them, but I do use the functions
directory for my own functions and I'd prefer to not gitignore all of the
plugin files individually.

**Comment by lianghx-319** [comment]
suffering same issue. When I want to recover plugins on new machine.

**Comment by jorgebucaran** [comment]
@lianghx-319 Describe the issue, please.

**Comment by lianghx-319** [comment]
> @lianghx-319 Describe the issue, please.

@jorgebucaran I just found that the latest version of fisher will create a fish_plugins file to store the plugin list. It's seem works when `fisher update` in other machine which sync the fish_plugins

**Comment by lianghx-319** [comment]
I think this issue can be closed, after update the document about the file `fish_plugins`
