### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by noah-nuebling** [jorgebucaran/fisher#743]
Hi! 

Running `fisher list | fisher remove` to uninstall fisher does not work for me. The output is `fisher: Not enough arguments for command: "remove"`. 

Just running `fisher list` gives no output at all:

<img width="392" alt="CleanShot 2022-10-19 at 00 22 16@2x" src="https://user-images.githubusercontent.com/40808343/196556226-fbf13aae-27fd-4d08-a0b4-56e1a9a585cf.png">

Is there anything I can do to solve this?

**Comment by jorgebucaran** [comment]
Someone or something messed up your Fisher state (Fisher variables). Reinstall Fisher to attempt to fix the state, and then remove it. 

Or delete `fisher.fish` from your Fish config.
