### ISSUE TITLE
fisher install and fisher update both edit the fish_plugins file in unexpected ways.

### ISSUE THREAD

**Issue by LinuxIsCool** [jorgebucaran/fisher#744]
Is there a way to install plugins from the fish_plugins file without changing that file? This is the essentially the same concern as #705 and I'm not sure why that issue is closed as the suggested fix https://github.com/jorgebucaran/fisher/issues/705#issuecomment-1100675765
has not been implemented. I left some comments at the bottom of that issue: https://github.com/jorgebucaran/fisher/issues/705#issuecomment-1294265189

**Comment by jorgebucaran** [comment]
If you manually added/removed plugins to/from fish_plugins and want to commit those changes, you must use fisher update, see:  https://github.com/jorgebucaran/fisher#using-your-fish_plugins-file.

I addressed your comment there as well, but if you prefer to reply here you are certainly welcome to do that.

**Comment by jorgebucaran** [comment]
If you manually added/removed plugins to/from fish_plugins and want to commit those changes, you must use fisher update, see:  https://github.com/jorgebucaran/fisher#using-your-fish_plugins-file.

I addressed your comment in #705 as well, but if you prefer to reply here, you are certainly welcome to do that.

**Comment by LinuxIsCool** [comment]
Thank you for your reply. I'll close this issue and comment in the other thread as it's essentially the same issue.
