### ISSUE TITLE
Autoinstall

### ISSUE THREAD

**Issue by Susensio** [jorgebucaran/fisher#748]
How can I configure `~/.config/fish/config.fish` to autoinstall **fisher**, just like **fundle** does?

Fundle proposes adding `if not functions -q fundle; eval (curl -sfL https://git.io/fundle-install); end` to `config.d`. I've tried something similar with fisher with no luck.

**Comment by Susensio** [comment]
I'm trying to figure out what's happening. Here goes a MRE:

conf.d/fisher.fish
```fish
if not functions -q fisher
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
end
```

and the output is
```
fisher install version 4.4.3
fisher install version 4.4.3
fisher install version 4.4.3
fisher install version 4.4.3
```

So it seem to be entering a infinite loop when calling `fisher install`, where it sources `conf.d/fisher.fish` again.

**Comment by Susensio** [comment]
I found the problem: `fisher install` spawns `fish` subprocesses with `fish --command` that read configuration files, hence the infinite loop.
I've solved it checking if running from interactive session with `status is-interactive`.

This is the solution I've implemented (maybe this could be added to documentation):

```fish
if not functions -q fisher; and status is-interactive
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
end

I think this is a workaround and maybe `fisher install` should call `fish --command --no-config`, but I don't know for sure if this change could cause any problems.

**Comment by jorgebucaran** [comment]
Close, but you'd still need to check for interactivity. So, that's the best solution we know of. 

You can use && instead of ; and in modern Fish, by the way.

**Comment by jorgebucaran** [comment]
A PR to improve the docs is always welcome! 🙆‍♂️
