### ISSUE TITLE
Update subcommand removes local directories

### ISSUE THREAD

**Issue by daleeidd** [jorgebucaran/fisher#751]
In fish_plugins I had:
```
…
~/Developer/Fish/natural-selection
…
```

Executing `fisher update` produced the following output:

```cmd
fisher update version 4.4.3
…
fisher: Invalid plugin name or host unavailable: "~/developer/fish/natural-selection"
Removing /Users/Dale/Developer/Fish/natural-selection
…
```

The files are now gone.

**Comment by daleeidd** [comment]
Actually this might be a false positive. I remember now that I removed this directory months ago when doing some housekeeping. So I must of forgotten to update the fish_plugins file to the git repository.

"fisher: Invalid plugin name or host unavailable:" must be fisher not finding the directory and the subsequent "Removing" means it is removing the entry from fish_plugins. I think the messaging could be improved as it gave me the wrong impression that fisher removed a local directory which was quite a scare.

**Comment by jorgebucaran** [comment]
Suggestions?

**Comment by daleeidd** [comment]
"Removing" could be "Uninstalling" or "Removing entry" and print the entry name (above it expanded the path).

Could go further with the error message being specific (ie only mentioning either invalid plugin name, host unavailable or file not found etc).

**Comment by jorgebucaran** [comment]
Cool, thanks! If you send me a PR I can take a look.
