### ISSUE TITLE
Plugins Missing After Restart Terminal

### ISSUE THREAD

**Issue by ajmeireles** [jorgebucaran/fisher#755]
Hey, @jorgebucaran ! First of all thank you for your work.

Can you help me? I'm having a strange problem. Whenever I install a plugin it gets removed when I restart the terminal. I'm installing the plugin: https://github.com/jhillyerd/plugin-git and when I close the terminal it doesn't exist anymore in the abbreviations, and I need to install again (using Fisher).

What am I doing wrong?

**Comment by jorgebucaran** [comment]
Hey, @ajmeireles! Maybe it's something in your config.fish. Paste it here please?

**Comment by zephaniahong** [comment]
I'm having a similar issue. But rather than the plugin being removed, I think it's just that the abbreviations don't work.

config.fish
```fish
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
status is-interactive && eval /Users/zephaniahong/opt/anaconda3/bin/conda "shell.fish" "hook" $argv | source
# <<< conda initialize <<<

if status --is-login
    set -gx PATH $PATH /opt/homebrew/bin
end
```

**Comment by jorgebucaran** [comment]
@zephaniahong I don't think your config is interfering with Fisher, so your issue might be something else.

**Comment by zephaniahong** [comment]
If I run 
```fish
echo $fisher_path
```
Should I be expecting an output? Mine seems to be blank.

**Comment by jorgebucaran** [comment]
What plugins are you currently using?

**Comment by zephaniahong** [comment]
Just these:
jorgebucaran/fisher
jethrokuan/z
ilancosman/tide@v5
jhillyerd/plugin-git

**Comment by jorgebucaran** [comment]
What happens if you uninstall that git plug-in and start a new shell? Do your abbreviations work now? Also try commenting everything in your config.

**Comment by zephaniahong** [comment]
Nope! The abbreviations come from the plugin so they are gone when I uninstall.
These are the files that get downloaded.![Screenshot 2023-01-27 at 6 27 51 PM](https://user-images.githubusercontent.com/33389011/215064727-3e94e61e-eab6-431f-a07c-3fd2070a7359.png)
All the functions work. But the abbreviations that exist in the __git.init.fish file don't seem to work when I open another shell.

**Comment by jorgebucaran** [comment]
Maybe that plugin doesn't work well with Fisher. See also https://github.com/jhillyerd/plugin-git/pull/49

**Comment by faho** [comment]
This is https://github.com/jhillyerd/plugin-git/pull/88.

The underlying issue is that fish 3.6.0's new and improved abbreviations won't be stored in universal variables anymore, so the plugin creates global abbreviations and then doesn't re-add them in subsequent shells.

I don't believe it has anything to do with fisher.

**Comment by jorgebucaran** [comment]
Thanks for chiming in, @faho.
