### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by thistlillo** [jorgebucaran/fisher#758]
It is likely that his is a very silly question, but I would rather ask.

How do I "uninstall" fisher? Even if may be there is not an actual program to remove, how do I revert back to how things were before installing fisher?

I was not able to find any reference to its removal...

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/fisher#removing-plugins

> ### Removing plugins
>
> Remove installed plugins using the `remove` command.
>
> ```console
> fisher remove jorgebucaran/nvm.fish
> ```
>
> You may want to remove everything, including Fisher.
>
> ```console
> fisher list | fisher remove
> ```
