### ISSUE TITLE
Replace git.io link in README with IPv6-compatible link.

### ISSUE THREAD

**Issue by kotx** [jorgebucaran/fisher#760]
Git.io doesn't support IPv6. This causes an obscure error on installation of fish:
```
kot@pom ~> curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fish: Unknown command: fisher
fish:
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
                                           ^~~~~^
```
This is because `git.io` cannot be resolved:
```
kot@pom ~ [7]> ping git.io
ping: connect: Network is unreachable
```

**Comment by kotx** [comment]
Actually I just replaced the url with https://raw.githubusercontent.com/jorgebucaran/fisher/HEAD/functions/fisher.fish
but then GitHub doesn't support IPv6 so Fisher wouldn't work anyway:
```
kot@pom ~ [1]> curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/HEAD/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install version 4.4.3
Fetching https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD
fisher: Invalid plugin name or host unavailable: "jorgebucaran/fisher"
```

This would require more changes than just to the README.

**Comment by jorgebucaran** [comment]
How can I reproduce this? (Link works fine for me). Are you using an exotic terminal?

**Comment by kotx** [comment]
> How can I reproduce this? (Link works fine for me). Are you using an exotic terminal?
```
~ ❱ dig +short git.io AAAA
~ ❱ dig +short git.io A
140.82.113.22
```

**Comment by jorgebucaran** [comment]
Who is affected by this? I am able to install Fisher using the instructions in the README.

**Comment by igalic** [comment]
am increasing number of people who's ISPs only provide IPv6, because IPv4 shortage _is real_.

**Comment by jorgebucaran** [comment]
We should be good now 67bec738dbec2442d05d09ef72b2be82acb1d774. Thank you, @igalic and @kotx.
