### ISSUE TITLE
[Question] Is it possible to have python syntax highlighting inside fish terminal?

### ISSUE THREAD

**Issue by FilipeMarch** [jorgebucaran/fisher#762]
Sometimes I open fish terminal, type `python` and press enter to test something quickly.
Is it possible to activate syntax highlighting for python code inside fish terminal, while running the python interpreter inside it?

Thanks.

**Comment by jorgebucaran** [comment]
Hey there, @FilipeMarch! You're looking for this repo: https://github.com/fish-shell/fish-shell. Just a heads up, Fisher is just the plugin manager. 😄

**Comment by faho** [comment]
To cut this off at the pass: No need to file a fish question either, because fish is *not a terminal*.

Once `python` runs, fish is out of the loop. Fish starts it and hands it control of the terminal.

Anyway, what you want is https://ipython.org/ - an alternative python interface.

**Comment by FilipeMarch** [comment]
> Hey there, @FilipeMarch! You're looking for this repo: https://github.com/fish-shell/fish-shell. Just a heads up, Fisher is just the plugin manager. 😄

Thanks, I thought I would find a fisher plugin that would accomplish what I was looking for.

**Comment by FilipeMarch** [comment]
> To cut this off at the pass, @FilipeMarch: No need to file a fish question either, because fish is *not a terminal*.
> 
> Once `python` runs, fish is out of the loop. Fish starts it and hands it control of the terminal.
> 
> Anyway, what you want is https://ipython.org/ - an alternative python interface.

Ok, brother. Thank you for your response. I really believed fish was a terminal 😂. And I have been using it for years! I love it. 

I will take a look on alternative python interfaces. Thanks!
