### ISSUE TITLE
Install plugins in `$__fish_user_data_dir`

### ISSUE THREAD

**Issue by Bekaboo** [jorgebucaran/fisher#768]
Hi, first of all thanks for making this plugin!

As said in #568, I think it makes more sense to install fisher and other plugins under `$XDG_DATA_DIR`/`$__fish_user_data_dir` instead of `$XDG_CONFIG_DIR`/`$__fish_config_dir`.

It seems that fisher implemented this in #571, but after calling `fisher install xxx`, I find the plugin is installed under my config dir.

How can I install plugins under my data dir? Thanks!

**Comment by jorgebucaran** [comment]
If we modify the directory as you suggested, various elements like functions, completions, conf.d won't automatically load in new shells without an additional startup script (there's nothing fundamentally flawed with that, but I really appreciate how Fisher "just works" now). The PR you're talking about primarily adjusted the location of Fisher's internal data to `$__fish_user_data_dir`, it didn't change the plugin installation location (`$fisher_path`). 

If you're looking to change where Fisher installs plugins, follow the instructions [here](https://github.com/jorgebucaran/fisher/issues/640).
