### ISSUE TITLE
Fisher broken after mac update

### ISSUE THREAD

**Issue by pcriv** [jorgebucaran/fisher#769]
After an update to macOS 13.5 `fisher` cmd stopped working.

Tried reinstalling but I get the following error:

```sh
❯ curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
fisher install version 4.4.3
Fetching https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD
fish: No matches for wildcard '$temp/*/*'. See `help wildcards-globbing`.
                            command cp -Rf $temp/*/* /var/folders/zv/1phkpmk17z7_9cmhds0176140000gp/T/tmp.OSiHwdAt
                                           ^~~~~~~~^
Installing jorgebucaran/fisher
Updated 1 plugin/s
```

**Comment by jorgebucaran** [comment]
Is there any additional information you can provide? Without further details, we're at a standstill since the issue isn't reproducible.

**Comment by jorgebucaran** [comment]
Friendly ping. @pcriv

**Comment by pcriv** [comment]
Hi @jorgebucaran! sorry I'm on holidays but I'll try to add any extra info I can find asap

**Comment by pcriv** [comment]
So... grabbed my laptop after a few days, tried installing againg and now it works 🤷🏽

**Comment by alper** [comment]
For me the same. It seems it was a transient issue.
