### ISSUE TITLE
Issue with recent MacOS update?

### ISSUE THREAD

**Issue by crcastle** [jorgebucaran/fisher#776]
I'm just getting an error every time a new command line is shown: `realpath: illegal option -- -`.

<img width="914" alt="CleanShot 2023-09-11 at 18 08 32@2x" src="https://github.com/jorgebucaran/fisher/assets/275734/d0154598-ecc3-4efb-af59-0a947d26e559">

It looks like it has something to do with fisher because the error references `realpath` which I can only find being called in `fisher.fish`.

Any idea what's going on here? I'm not sure with what arguments `realpath` is being called, so I'm not sure how to debug.

EDIT: I'm on a MacBook Pro with the M1 Pro CPU. OS is 13.5.2, which came out around Sept 7.

**Comment by toabi** [comment]
I just noticed the same here after I upgraded _all_ my brew+macOS things after some holidays.

I tried to edit this line and add some debug printing but actually nothing got printed… so I wonder if fisher really is to blame here…

So now I went to check  if some of my other tools which are used in the fish/config file maybe use some realpath wrong (direnv, starship, thefuck, asdf) … and it looks like asdf is to blame in my case. Maybe you also use it?

**Comment by crcastle** [comment]
I think you are correct @toabi. I found [this comment](https://github.com/asdf-vm/asdf/pull/1637#issuecomment-1714510210) in `asdf` PR https://github.com/asdf-vm/asdf/pull/1637. It looks like [version 0.13.1 was released](https://github.com/asdf-vm/asdf/pull/1638) with this fix a few hours ago, but this new version hasn't made it to homebrew yet. I used homebrew to install asdf, so I'll just wait a day or two until the homebrew formula for asdf is updated.

Closing this issue. Sorry for the misdirection folks.

**Comment by huntr3ssArt3mis** [comment]
@crcastle this issue and @toabi's answer pointed me in the right direction. So no worries :)

**Comment by Sinderella** [comment]
@crcastle there you go 😄 https://github.com/Homebrew/homebrew-core/pull/142183
