### ISSUE TITLE
Error installing fisher in macOS Sonoma

### ISSUE THREAD

**Issue by cmxela** [jorgebucaran/fisher#781]
I am trying to install fisher in a fresh install of macOS Sonoma and I am getting the following error

```curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

fisher install version 4.4.4
Fetching https://api.github.com/repos/jorgebucaran/fisher/tarball/HEAD
fish: No matches for wildcard '$temp/*/*'. See `help wildcards-globbing`.
                            command cp -Rf $temp/*/* /var/folders/km/8cyqh0hs66l64sprfz6kb9g80000gn/T/tmp.AhGp7HTYuP
                                           ^~~~~~~~^
Installing jorgebucaran/fisher
Updated 1 plugin/s
```

when I close the session and open again, fisher is not available, neither the plugins installed after.

**Comment by cmxela** [comment]
The problem has appeared in a totally fresh installation of MacOS and fisher, I have deleted the partition and installed MacOS sonoma in a Macbook Air M1 from an usb. I like to install the new versions from scratch to do some housecleaning of my laptop. Installed Homebrew to install fish, and just after, I installed fisher and I got this message, I have executed the command again to copy/paste in the issue and this is why you saw the Updated 1 plugin/s

**Comment by jorgebucaran** [comment]
Can you reproduce the issue? Are you still having the issue?

**Comment by cmxela** [comment]
I have manually placed fisher.fish in ~/.config/fish functions and worked

**Comment by alper** [comment]
I just got the same issue as well.
