### ISSUE TITLE
Fisher installation through command line failed

### ISSUE THREAD

**Issue by xiaohuipoi** [jorgebucaran/fisher#782]
Why do I use the command line provided in the installation and after entering it in the terminal, it displays
bash: source: requires filename argument
source: Usage: source filename [parameter]
Then the installation failed
System: ubuntu20.04, anaconda3 is installed, the command is executed in the base environment of anaconda

**Comment by jorgebucaran** [comment]
Are you trying to instal Fisher from Bash or Fish?

**Comment by xiaohuipoi** [comment]
thx bro,I forgot to open the fish terminal. The installation failed in the base environment.

**Comment by xiaohuipoi** [comment]
thx bro,I forgot to open the fish terminal. The installation failed in the base environment.
