### ISSUE TITLE
Update project with username change

### ISSUE THREAD

**Issue by thesilican** [jorgebucaran/fisher#783]
Seems like the maintainer's username was changed from `jorgebucaran` to `joxji`, but the installation instructions in [README.md](./README.md) and other files in this project still reference the old username. GitHub redirects the old links, but this will break if someone else happens to register with the old username.

**Comment by joxji** [comment]
I'm still holding onto the old name, so that won't be a problem. Thanks for opening this up, though.  I'll keep it open until I sort things out. Also, thanks for the PR – no need to close it. I'll merge it when I'm ready.
