### ISSUE TITLE
Manually source plugins

### ISSUE THREAD

**Issue by BoManev** [jorgebucaran/fisher#785]
Fisher is great! I have been using it for more than an year, without any issues.

I installed https://github.com/lilyball/nix-env.fish, however I noticed an issue.
In my fish config, I completely overwrite the default PATH.
```
set PATH /usr/local/sbin/
set PATH $PATH ...
```
However, this breaks the nix-env plugin, because my config overwrites the PATH set by the plugin.
If I don't overwrite the PATH in my config, everything works as expected.

Is there any way to tell fisher, when to source/initialize the plugins?
Essentially, I want to do some setup in my config and at some point invoke fisher to source the plugins.

Thank you!

**Comment by jorgebucaran** [comment]
Could you use [`fish_add_path`](https://fishshell.com/docs/current/cmds/fish_add_path.html) to interactively set your PATH? This way, you wouldn't need to directly modify the PATH in your config.fish.
