### ISSUE TITLE
How do I install plugins conditionally?

### ISSUE THREAD

**Issue by gaerfield** [jorgebucaran/fisher#786]
I share my dotfiles on several machines. Some of them having installed skdman, some of them haven't. Can I configure my fish_plugins in a way that it includes some plugins only on specific conditions?

```
jorgebucaran/fisher
if type -q sdk
  reitzig/sdkman-for-fish
end
```

**Comment by jorgebucaran** [comment]
Nope, you can't do that right now. fish_plugins isn't code you can run; it's just a manifest of plugins you want to install or update. But you might be able to pull it off in your config.fish.
